#ifndef GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
#define GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H

#define FRONTIER_MON_BUTTERFREE                 0
#define FRONTIER_MON_BEEDRILL                   1
#define FRONTIER_MON_PIDGEOT                    2
#define FRONTIER_MON_RATICATE                   3
#define FRONTIER_MON_RATICATE_ALOLAN            4
#define FRONTIER_MON_FEAROW                     5
#define FRONTIER_MON_ARBOK                      6
#define FRONTIER_MON_RAICHU                     7
#define FRONTIER_MON_RAICHU_ALOLAN              8
#define FRONTIER_MON_SANDSLASH                  9
#define FRONTIER_MON_SANDSLASH_ALOLAN           10
#define FRONTIER_MON_NIDOQUEEN                  11
#define FRONTIER_MON_NIDOKING                   12
#define FRONTIER_MON_NINETALES                  13
#define FRONTIER_MON_NINETALES_EMERIBIAN        14
#define FRONTIER_MON_WIGGLYTUFF                 15
#define FRONTIER_MON_VILEPLUME                  16
#define FRONTIER_MON_VILEPLUME_EMERIBIAN        17
#define FRONTIER_MON_PARASECT                   18
#define FRONTIER_MON_VENOMOTH                   19
#define FRONTIER_MON_DUGTRIO                    20
#define FRONTIER_MON_DUGTRIO_ALOLAN             21
#define FRONTIER_MON_PERSIAN                    22
#define FRONTIER_MON_PERSIAN_ALOLAN             23
#define FRONTIER_MON_GOLDUCK                    24
#define FRONTIER_MON_ARCANINE                   25
#define FRONTIER_MON_POLIWRATH                  26
#define FRONTIER_MON_MACHAMP                    27
#define FRONTIER_MON_VICTREEBEL                 28
#define FRONTIER_MON_GOLEM                      29
#define FRONTIER_MON_GOLEM_ALOLAN               30
#define FRONTIER_MON_GOLEM_FRIBIAN              31
#define FRONTIER_MON_RAPIDASH                   32
#define FRONTIER_MON_RAPIDASH_GALARIAN          33
#define FRONTIER_MON_SLOWBRO_GALARIAN           34
#define FRONTIER_MON_FARFETCHD                  35
#define FRONTIER_MON_DODRIO                     36
#define FRONTIER_MON_DEWGONG                    37
#define FRONTIER_MON_MUK                        38
#define FRONTIER_MON_MUK_ALOLAN                 39
#define FRONTIER_MON_HYPNO                      40
#define FRONTIER_MON_KINGLER                    41
#define FRONTIER_MON_ELECTRODE                  42
#define FRONTIER_MON_EXEGGUTOR                  43
#define FRONTIER_MON_EXEGGUTOR_ALOLAN           44
#define FRONTIER_MON_MAROWAK                    45
#define FRONTIER_MON_MAROWAK_ALOLAN             46
#define FRONTIER_MON_HITMONLEE                  47
#define FRONTIER_MON_HITMONCHAN                 48
#define FRONTIER_MON_WEEZING                    49
#define FRONTIER_MON_KANGASKHAN                 50
#define FRONTIER_MON_SEAKING                    51
#define FRONTIER_MON_MR_MIME                    52
#define FRONTIER_MON_JYNX                       53
#define FRONTIER_MON_PINSIR                     54
#define FRONTIER_MON_TAUROS                     55
#define FRONTIER_MON_TAUROS_PALDEAN             56
#define FRONTIER_MON_LAPRAS                     57
#define FRONTIER_MON_DITTO                      58
#define FRONTIER_MON_VAPOREON                   59
#define FRONTIER_MON_JOLTEON                    60
#define FRONTIER_MON_FLAREON                    61
#define FRONTIER_MON_OMASTAR                    62
#define FRONTIER_MON_KABUTOPS                   63
#define FRONTIER_MON_AERODACTYL                 64
#define FRONTIER_MON_FURRET                     65
#define FRONTIER_MON_NOCTOWL                    66
#define FRONTIER_MON_NOCTOWL_EMERIBIAN          67
#define FRONTIER_MON_LEDIAN                     68
#define FRONTIER_MON_ARIADOS_EMERIBIAN          69
#define FRONTIER_MON_CROBAT                     70
#define FRONTIER_MON_LANTURN                    71
#define FRONTIER_MON_XATU                       72
#define FRONTIER_MON_AMPHAROS                   73
#define FRONTIER_MON_BELLOSSOM                  74
#define FRONTIER_MON_BELLOSSOM_EMERIBIAN        75
#define FRONTIER_MON_SUDOWOODO                  76
#define FRONTIER_MON_JUMPLUFF                   77
#define FRONTIER_MON_SUNFLORA                   78
#define FRONTIER_MON_ESPEON                     79
#define FRONTIER_MON_WOBBUFFET                  80
#define FRONTIER_MON_FORRETRESS                 81
#define FRONTIER_MON_STEELIX                    82
#define FRONTIER_MON_GRANBULL                   83
#define FRONTIER_MON_QWILFISH                   84
#define FRONTIER_MON_HERACROSS                  85
#define FRONTIER_MON_MAGCARGO                   86
#define FRONTIER_MON_MAGCARGO_EMERIBIAN         87
#define FRONTIER_MON_CORSOLA                    88
#define FRONTIER_MON_OCTILLERY                  89
#define FRONTIER_MON_OCTILLERY_FRIBIAN          90
#define FRONTIER_MON_DELIBIRD                   91
#define FRONTIER_MON_MANTINE                    92
#define FRONTIER_MON_HOUNDOOM                   93
#define FRONTIER_MON_KINGDRA                    94
#define FRONTIER_MON_SMEARGLE                   95
#define FRONTIER_MON_HITMONTOP                  96
#define FRONTIER_MON_MILTANK                    97
#define FRONTIER_MON_MIGHTYENA                  98
#define FRONTIER_MON_BEAUTIFLY                  99
#define FRONTIER_MON_DUSTOX                     100
#define FRONTIER_MON_LUDICOLO                   101
#define FRONTIER_MON_SHIFTRY                    102
#define FRONTIER_MON_SWELLOW                    103
#define FRONTIER_MON_GARDEVOIR                  104
#define FRONTIER_MON_GARDEVOIR_EMERIBIAN        105
#define FRONTIER_MON_MASQUERAIN                 106
#define FRONTIER_MON_SLAKING                    107
#define FRONTIER_MON_NINJASK                    108
#define FRONTIER_MON_SHEDINJA                   109
#define FRONTIER_MON_EXPLOUD                    110
#define FRONTIER_MON_HARIYAMA                   111
#define FRONTIER_MON_DELCATTY                   112
#define FRONTIER_MON_SABLEYE                    113
#define FRONTIER_MON_MAWILE                     114
#define FRONTIER_MON_AGGRON                     115
#define FRONTIER_MON_MEDICHAM                   116
#define FRONTIER_MON_MANECTRIC                  117
#define FRONTIER_MON_PLUSLE                     118
#define FRONTIER_MON_MINUN                      119
#define FRONTIER_MON_VOLBEAT                    120
#define FRONTIER_MON_ILLUMISE                   121
#define FRONTIER_MON_SWALOT                     122
#define FRONTIER_MON_SHARPEDO                   123
#define FRONTIER_MON_WAILORD                    124
#define FRONTIER_MON_CAMERUPT                   125
#define FRONTIER_MON_GRUMPIG                    126
#define FRONTIER_MON_SPINDA                     127
#define FRONTIER_MON_CACTURNE                   128
#define FRONTIER_MON_ALTARIA                    129
#define FRONTIER_MON_ZANGOOSE                   130
#define FRONTIER_MON_SEVIPER                    131
#define FRONTIER_MON_LUNATONE                   132
#define FRONTIER_MON_SOLROCK                    133
#define FRONTIER_MON_WHISCASH                   134
#define FRONTIER_MON_CLAYDOL                    135
#define FRONTIER_MON_CRADILY                    136
#define FRONTIER_MON_ARMALDO                    137
#define FRONTIER_MON_CASTFORM                   138
#define FRONTIER_MON_KECLEON                    139
#define FRONTIER_MON_BANETTE                    140
#define FRONTIER_MON_TROPIUS                    141
#define FRONTIER_MON_CHIMECHO                   142
#define FRONTIER_MON_ABSOL                      143
#define FRONTIER_MON_GLALIE                     144
#define FRONTIER_MON_WALREIN                    145
#define FRONTIER_MON_HUNTAIL                    146
#define FRONTIER_MON_GOREBYSS                   147
#define FRONTIER_MON_RELICANTH                  148
#define FRONTIER_MON_LUVDISC                    149
#define FRONTIER_MON_KRICKETUNE                 150
#define FRONTIER_MON_LUXRAY                     151
#define FRONTIER_MON_RAMPARDOS                  152
#define FRONTIER_MON_BASTIODON                  153
#define FRONTIER_MON_WORMADAM                   154
#define FRONTIER_MON_MOTHIM                     155
#define FRONTIER_MON_VESPIQUEN                  156
#define FRONTIER_MON_PACHIRISU                  157
#define FRONTIER_MON_FLOATZEL                   158
#define FRONTIER_MON_CHERRIM                    159
#define FRONTIER_MON_AMBIPOM                    160
#define FRONTIER_MON_DRIFBLIM                   161
#define FRONTIER_MON_DRIFBLIM_EMERIBIAN         162
#define FRONTIER_MON_LOPUNNY                    163
#define FRONTIER_MON_MISMAGIUS                  164
#define FRONTIER_MON_HONCHKROW                  165
#define FRONTIER_MON_PURUGLY                    166
#define FRONTIER_MON_SKUNTANK                   167
#define FRONTIER_MON_BRONZONG                   168
#define FRONTIER_MON_CHATOT                     169
#define FRONTIER_MON_SPIRITOMB                  170
#define FRONTIER_MON_DRAPION                    171
#define FRONTIER_MON_TOXICROAK                  172
#define FRONTIER_MON_CARNIVINE                  173
#define FRONTIER_MON_LUMINEON                   174
#define FRONTIER_MON_LICKILICKY                 175
#define FRONTIER_MON_ELECTIVIRE                 176
#define FRONTIER_MON_MAGMORTAR                  177
#define FRONTIER_MON_YANMEGA                    178
#define FRONTIER_MON_LEAFEON                    179
#define FRONTIER_MON_GLACEON                    180
#define FRONTIER_MON_PORYGON_Z                  181
#define FRONTIER_MON_PROBOPASS                  182
#define FRONTIER_MON_DUSKNOIR                   183
#define FRONTIER_MON_ROTOM                      184
#define FRONTIER_MON_PHIONE                     185
#define FRONTIER_MON_WATCHOG                    186
#define FRONTIER_MON_STOUTLAND                  187
#define FRONTIER_MON_LIEPARD                    188
#define FRONTIER_MON_SIMISAGE                   189
#define FRONTIER_MON_SIMISEAR                   190
#define FRONTIER_MON_SIMIPOUR                   191
#define FRONTIER_MON_MUSHARNA                   192
#define FRONTIER_MON_UNFEZANT                   193
#define FRONTIER_MON_ZEBSTRIKA                  194
#define FRONTIER_MON_GIGALITH                   195
#define FRONTIER_MON_GIGALITH_FRIBIAN           196
#define FRONTIER_MON_SWOOBAT                    197
#define FRONTIER_MON_AUDINO                     198
#define FRONTIER_MON_THROH                      199
#define FRONTIER_MON_SAWK                       200
#define FRONTIER_MON_LEAVANNY                   201
#define FRONTIER_MON_MARACTUS                   202
#define FRONTIER_MON_CRUSTLE                    203
#define FRONTIER_MON_SCRAFTY                    204
#define FRONTIER_MON_SIGILYPH                   205
#define FRONTIER_MON_COFAGRIGUS                 206
#define FRONTIER_MON_CARRACOSTA                 207
#define FRONTIER_MON_ARCHEOPS                   208
#define FRONTIER_MON_GARBODOR                   209
#define FRONTIER_MON_ZOROARK                    210
#define FRONTIER_MON_CINCCINO                   211
#define FRONTIER_MON_SWANNA                     212
#define FRONTIER_MON_SAWSBUCK                   213
#define FRONTIER_MON_EMOLGA                     214
#define FRONTIER_MON_ESCAVALIER                 215
#define FRONTIER_MON_KLINKLANG                  216
#define FRONTIER_MON_EELEKTROSS                 217
#define FRONTIER_MON_BEHEEYEM                   218
#define FRONTIER_MON_BEARTIC                    219
#define FRONTIER_MON_CRYOGONAL                  220
#define FRONTIER_MON_ACCELGOR                   221
#define FRONTIER_MON_STUNFISK                   222
#define FRONTIER_MON_STUNFISK_GALARIAN          223
#define FRONTIER_MON_DRUDDIGON                  224
#define FRONTIER_MON_GOLURK                     225
#define FRONTIER_MON_BOUFFALANT                 226
#define FRONTIER_MON_BRAVIARY                   227
#define FRONTIER_MON_HEATMOR                    228
#define FRONTIER_MON_VIVILLON                   229
#define FRONTIER_MON_PYROAR                     230
#define FRONTIER_MON_GOGOAT                     231
#define FRONTIER_MON_GOGOAT_EMERIBIAN           232
#define FRONTIER_MON_PANGORO                    233
#define FRONTIER_MON_FURFROU                    234
#define FRONTIER_MON_MEOWSTIC                   235
#define FRONTIER_MON_MEOWSTIC_FEMALE            236
#define FRONTIER_MON_AROMATISSE                 237
#define FRONTIER_MON_SLURPUFF                   238
#define FRONTIER_MON_MALAMAR                    239
#define FRONTIER_MON_CLAWITZER                  240
#define FRONTIER_MON_TYRANTRUM                  241
#define FRONTIER_MON_AURORUS                    242
#define FRONTIER_MON_DEDENNE                    243
#define FRONTIER_MON_CARBINK                    244
#define FRONTIER_MON_GOODRA                     245
#define FRONTIER_MON_TREVENANT                  246
#define FRONTIER_MON_TREVENANT_EMERIBIAN        247
#define FRONTIER_MON_GOURGEIST                  248
#define FRONTIER_MON_AVALUGG                    249
#define FRONTIER_MON_AVALUGG_HISUIAN            250
#define FRONTIER_MON_TOUCANNON                  251
#define FRONTIER_MON_GUMSHOOS                   252
#define FRONTIER_MON_VIKAVOLT                   253
#define FRONTIER_MON_CRABOMINABLE               254
#define FRONTIER_MON_ORICORIO                   255
#define FRONTIER_MON_LYCANROC                   256
#define FRONTIER_MON_LYCANROC_MIDNIGHT          257
#define FRONTIER_MON_LYCANROC_DUSK              258
#define FRONTIER_MON_WISHIWASHI                 259
#define FRONTIER_MON_MUDSDALE                   260
#define FRONTIER_MON_ARAQUANID                  261
#define FRONTIER_MON_LURANTIS                   262
#define FRONTIER_MON_SHIINOTIC                  263
#define FRONTIER_MON_BEWEAR                     264
#define FRONTIER_MON_COMFEY                     265
#define FRONTIER_MON_ORANGURU                   266
#define FRONTIER_MON_PASSIMIAN                  267
#define FRONTIER_MON_PALOSSAND                  268
#define FRONTIER_MON_PYUKUMUKU                  269
#define FRONTIER_MON_SILVALLY                   270
#define FRONTIER_MON_MINIOR                     271
#define FRONTIER_MON_KOMALA                     272
#define FRONTIER_MON_TURTONATOR                 273
#define FRONTIER_MON_TOGEDEMARU                 274
#define FRONTIER_MON_MIMIKYU_EMERIBIAN          275
#define FRONTIER_MON_BRUXISH                    276
#define FRONTIER_MON_DRAMPA                     277
#define FRONTIER_MON_GUZZLORD                   278
#define FRONTIER_MON_STAKATAKA                  279
#define FRONTIER_MON_GREEDENT                   280
#define FRONTIER_MON_ORBEETLE                   281
#define FRONTIER_MON_THIEVUL                    282
#define FRONTIER_MON_ELDEGOSS                   283
#define FRONTIER_MON_DUBWOOL                    284
#define FRONTIER_MON_DUBWOOL_FRIBIAN            285
#define FRONTIER_MON_DREDNAW                    286
#define FRONTIER_MON_BOLTUND                    287
#define FRONTIER_MON_COALOSSAL                  288
#define FRONTIER_MON_FLAPPLE                    289
#define FRONTIER_MON_APPLETUN                   290
#define FRONTIER_MON_SANDACONDA                 291
#define FRONTIER_MON_CRAMORANT                  292
#define FRONTIER_MON_CENTISKORCH                293
#define FRONTIER_MON_GRAPPLOCT                  294
#define FRONTIER_MON_PERRSERKER                 295
#define FRONTIER_MON_CURSOLA                    296
#define FRONTIER_MON_SIRFETCHD                  297
#define FRONTIER_MON_MR_RIME                    298
#define FRONTIER_MON_RUNERIGUS                  299
#define FRONTIER_MON_ALCREMIE                   300
#define FRONTIER_MON_FALINKS                    301
#define FRONTIER_MON_FALINKS_EMERIBIAN          302
#define FRONTIER_MON_PINCURCHIN                 303
#define FRONTIER_MON_FROSMOTH                   304
#define FRONTIER_MON_STONJOURNER                305
#define FRONTIER_MON_EISCUE                     306
#define FRONTIER_MON_MORPEKO                    307
#define FRONTIER_MON_COPPERAJAH                 308
#define FRONTIER_MON_ARCTOVISH                  309
#define FRONTIER_MON_DURALUDON                  310
#define FRONTIER_MON_WYRDEER                    311
#define FRONTIER_MON_OINKOLOGNE                 312
#define FRONTIER_MON_SPIDOPS                    313
#define FRONTIER_MON_DACHSBUN                   314
#define FRONTIER_MON_ARBOLIVA                   315
#define FRONTIER_MON_SQUAWKABILLY               316
#define FRONTIER_MON_BELLIBOLT                  317
#define FRONTIER_MON_MABOSSTIFF                 318
#define FRONTIER_MON_GRAFAIAI                   319
#define FRONTIER_MON_BRAMBLEGHAST               320
#define FRONTIER_MON_KLAWF                      321
#define FRONTIER_MON_SCOVILLAIN                 322
#define FRONTIER_MON_RABSCA                     323
#define FRONTIER_MON_WUGTRIO                    324
#define FRONTIER_MON_BOMBIRDIER                 325
#define FRONTIER_MON_REVAVROOM                  326
#define FRONTIER_MON_ORTHWORM                   327
#define FRONTIER_MON_HOUNDSTONE                 328
#define FRONTIER_MON_FLAMIGO                    329
#define FRONTIER_MON_CETITAN                    330
#define FRONTIER_MON_VELUZA                     331
#define FRONTIER_MON_TATSUGIRI                  332
#define FRONTIER_MON_FARIGIRAF                  333
#define FRONTIER_MON_DUDUNSPARCE                334
#define FRONTIER_MON_EVALEON                    335
#define FRONTIER_MON_AEREON                     336
#define FRONTIER_MON_CONTAGEON                  337
#define FRONTIER_MON_LANEON                     338
#define FRONTIER_MON_TITANEON                   339

#define FRONTIER_MON_VENUSAUR                   340
#define FRONTIER_MON_CHARIZARD                  341
#define FRONTIER_MON_CHARIZARD_EMERIBIAN        342
#define FRONTIER_MON_BLASTOISE                  343
#define FRONTIER_MON_CLEFABLE                   344
#define FRONTIER_MON_NINETALES_ALOLAN           345
#define FRONTIER_MON_ARCANINE_HISUIAN           346
#define FRONTIER_MON_ALAKAZAM                   347
#define FRONTIER_MON_TENTACRUEL                 348
#define FRONTIER_MON_SLOWBRO                    349
#define FRONTIER_MON_CLOYSTER                   350
#define FRONTIER_MON_CLOYSTER_FRIBIAN           351
#define FRONTIER_MON_GENGAR                     352
#define FRONTIER_MON_ELECTRODE_HISUIAN          353
#define FRONTIER_MON_WEEZING_GALARIAN           354
#define FRONTIER_MON_STARMIE                    355
#define FRONTIER_MON_TAUROS_PALDEAN_AQUA_BREED  356
#define FRONTIER_MON_TAUROS_PALDEAN_BLAZE_BREED 357
#define FRONTIER_MON_GYARADOS                   358
#define FRONTIER_MON_SNORLAX                    359
#define FRONTIER_MON_ARTICUNO                   360
#define FRONTIER_MON_ARTICUNO_GALARIAN          361
#define FRONTIER_MON_ZAPDOS                     362
#define FRONTIER_MON_ZAPDOS_GALARIAN            363
#define FRONTIER_MON_MOLTRES                    364
#define FRONTIER_MON_MOLTRES_GALARIAN           365
#define FRONTIER_MON_DRAGONITE                  366
#define FRONTIER_MON_MEGANIUM                   367
#define FRONTIER_MON_TYPHLOSION                 368
#define FRONTIER_MON_TYPHLOSION_HISUIAN         369
#define FRONTIER_MON_FERALIGATR                 370
#define FRONTIER_MON_ARIADOS                    371
#define FRONTIER_MON_AZUMARILL                  372
#define FRONTIER_MON_POLITOED                   373
#define FRONTIER_MON_QUAGSIRE                   374
#define FRONTIER_MON_UMBREON                    375
#define FRONTIER_MON_SLOWKING                   376
#define FRONTIER_MON_SLOWKING_GALARIAN          377
#define FRONTIER_MON_SCIZOR                     378
#define FRONTIER_MON_SHUCKLE                    379
#define FRONTIER_MON_SHUCKLE_FRIBIAN            380
#define FRONTIER_MON_SKARMORY                   381
#define FRONTIER_MON_SKARMORY_FRIBIAN           382
#define FRONTIER_MON_DONPHAN                    383
#define FRONTIER_MON_BLISSEY                    384
#define FRONTIER_MON_RAIKOU                     385
#define FRONTIER_MON_ENTEI                      386
#define FRONTIER_MON_SUICUNE                    387
#define FRONTIER_MON_TYRANITAR                  388
#define FRONTIER_MON_SCEPTILE                   389
#define FRONTIER_MON_BLAZIKEN                   390
#define FRONTIER_MON_SWAMPERT                   391
#define FRONTIER_MON_LINOONE                    392
#define FRONTIER_MON_PELIPPER                   393
#define FRONTIER_MON_BRELOOM                    394
#define FRONTIER_MON_BRELOOM_FRIBIAN            395
#define FRONTIER_MON_TORKOAL                    396
#define FRONTIER_MON_FLYGON                     397
#define FRONTIER_MON_CRAWDAUNT                  398
#define FRONTIER_MON_MILOTIC                    399
#define FRONTIER_MON_SALAMENCE                  400
#define FRONTIER_MON_METAGROSS                  401
#define FRONTIER_MON_REGIROCK                   402
#define FRONTIER_MON_REGICE                     403
#define FRONTIER_MON_REGISTEEL                  404
#define FRONTIER_MON_LATIAS                     405
#define FRONTIER_MON_LATIOS                     406
#define FRONTIER_MON_TORTERRA                   407
#define FRONTIER_MON_INFERNAPE                  408
#define FRONTIER_MON_EMPOLEON                   409
#define FRONTIER_MON_STARAPTOR                  410
#define FRONTIER_MON_BIBAREL                    411
#define FRONTIER_MON_ROSERADE                   412
#define FRONTIER_MON_GASTRODON                  413
#define FRONTIER_MON_GARCHOMP                   414
#define FRONTIER_MON_LUCARIO                    415
#define FRONTIER_MON_HIPPOWDON                  416
#define FRONTIER_MON_ABOMASNOW                  417
#define FRONTIER_MON_WEAVILE                    418
#define FRONTIER_MON_MAGNEZONE                  419
#define FRONTIER_MON_RHYPERIOR                  420
#define FRONTIER_MON_TANGROWTH                  421
#define FRONTIER_MON_TOGEKISS                   422
#define FRONTIER_MON_GLISCOR                    423
#define FRONTIER_MON_MAMOSWINE                  424
#define FRONTIER_MON_GALLADE                    425
#define FRONTIER_MON_FROSLASS                   426
#define FRONTIER_MON_UXIE                       427
#define FRONTIER_MON_MESPRIT                    428
#define FRONTIER_MON_AZELF                      429
#define FRONTIER_MON_HEATRAN                    430
#define FRONTIER_MON_CRESSELIA                  431
#define FRONTIER_MON_SERPERIOR                  432
#define FRONTIER_MON_EMBOAR                     433
#define FRONTIER_MON_SAMUROTT                   434
#define FRONTIER_MON_SAMUROTT_HISUIAN           435
#define FRONTIER_MON_EXCADRILL                  436
#define FRONTIER_MON_CONKELDURR                 437
#define FRONTIER_MON_SEISMITOAD                 438
#define FRONTIER_MON_SCOLIPEDE                  439
#define FRONTIER_MON_WHIMSICOTT                 440
#define FRONTIER_MON_LILLIGANT                  441
#define FRONTIER_MON_LILLIGANT_HISUIAN          442
#define FRONTIER_MON_KROOKODILE                 443
#define FRONTIER_MON_DARMANITAN                 444
#define FRONTIER_MON_DARMANITAN_GALARIAN        445
#define FRONTIER_MON_ZOROARK_HISUIAN            446
#define FRONTIER_MON_GOTHITELLE                 447
#define FRONTIER_MON_REUNICLUS                  448
#define FRONTIER_MON_VANILLUXE                  449
#define FRONTIER_MON_AMOONGUSS                  450
#define FRONTIER_MON_JELLICENT                  451
#define FRONTIER_MON_ALOMOMOLA                  452
#define FRONTIER_MON_GALVANTULA                 453
#define FRONTIER_MON_FERROTHORN                 454
#define FRONTIER_MON_CHANDELURE                 455
#define FRONTIER_MON_HAXORUS                    456
#define FRONTIER_MON_MIENSHAO                   457
#define FRONTIER_MON_BRAVIARY_HISUIAN           458
#define FRONTIER_MON_MANDIBUZZ                  459
#define FRONTIER_MON_DURANT                     460
#define FRONTIER_MON_HYDREIGON                  461
#define FRONTIER_MON_VOLCARONA                  462
#define FRONTIER_MON_COBALION                   463
#define FRONTIER_MON_TERRAKION                  464
#define FRONTIER_MON_VIRIZION                   465
#define FRONTIER_MON_TORNADUS                   466
#define FRONTIER_MON_TORNADUS_THERIAN           467
#define FRONTIER_MON_THUNDURUS                  468
#define FRONTIER_MON_THUNDURUS_THERIAN          469
#define FRONTIER_MON_KELDEO                     470
#define FRONTIER_MON_CHESNAUGHT                 471
#define FRONTIER_MON_DELPHOX                    472
#define FRONTIER_MON_GRENINJA                   473
#define FRONTIER_MON_GRENINJA_2                 474
#define FRONTIER_MON_DIGGERSBY                  475
#define FRONTIER_MON_TALONFLAME                 476
#define FRONTIER_MON_FLORGES                    477
#define FRONTIER_MON_AEGISLASH                  478
#define FRONTIER_MON_AEGISLASH_EMERIBIAN        479
#define FRONTIER_MON_BARBARACLE                 480
#define FRONTIER_MON_DRAGALGE                   481
#define FRONTIER_MON_HELIOLISK                  482
#define FRONTIER_MON_SYLVEON                    483
#define FRONTIER_MON_HAWLUCHA                   484
#define FRONTIER_MON_GOODRA_HISUIAN             485
#define FRONTIER_MON_KLEFKI                     486
#define FRONTIER_MON_NOIVERN                    487
#define FRONTIER_MON_DECIDUEYE                  488
#define FRONTIER_MON_DECIDUEYE_HISUIAN          489
#define FRONTIER_MON_INCINEROAR                 490
#define FRONTIER_MON_PRIMARINA                  491
#define FRONTIER_MON_RIBOMBEE                   492
#define FRONTIER_MON_TOXAPEX                    493
#define FRONTIER_MON_SALAZZLE                   494
#define FRONTIER_MON_TSAREENA                   495
#define FRONTIER_MON_GOLISOPOD                  496
#define FRONTIER_MON_MIMIKYU                    497
#define FRONTIER_MON_DHELMISE                   498
#define FRONTIER_MON_KOMMO_O                    499
#define FRONTIER_MON_TAPU_KOKO                  500
#define FRONTIER_MON_TAPU_LELE                  501
#define FRONTIER_MON_TAPU_BULU                  502
#define FRONTIER_MON_TAPU_FINI                  503
#define FRONTIER_MON_NIHILEGO                   504
#define FRONTIER_MON_BUZZWOLE                   505
#define FRONTIER_MON_PHEROMOSA                  506
#define FRONTIER_MON_XURKITREE                  507
#define FRONTIER_MON_CELESTEELA                 508
#define FRONTIER_MON_KARTANA                    509
#define FRONTIER_MON_NAGANADEL                  510
#define FRONTIER_MON_BLACEPHALON                511
#define FRONTIER_MON_RILLABOOM                  512
#define FRONTIER_MON_CINDERACE                  513
#define FRONTIER_MON_INTELEON                   514
#define FRONTIER_MON_CORVIKNIGHT                515
#define FRONTIER_MON_BARRASKEWDA                516
#define FRONTIER_MON_TOXTRICITY                 517
#define FRONTIER_MON_POLTEAGEIST                518
#define FRONTIER_MON_HATTERENE                  519
#define FRONTIER_MON_GRIMMSNARL                 520
#define FRONTIER_MON_OBSTAGOON                  521
#define FRONTIER_MON_INDEEDEE                   522
#define FRONTIER_MON_DRACOZOLT                  523
#define FRONTIER_MON_ARCTOZOLT                  524
#define FRONTIER_MON_DRACOVISH                  525
#define FRONTIER_MON_DRAGAPULT                  526
#define FRONTIER_MON_URSHIFU_RAPID_STRIKE_STYLE 527
#define FRONTIER_MON_URSHIFU                    528
#define FRONTIER_MON_REGIELEKI                  529
#define FRONTIER_MON_REGIDRAGO                  530
#define FRONTIER_MON_GLASTRIER                  531
#define FRONTIER_MON_SPECTRIER                  532
#define FRONTIER_MON_CALYREX                    533
#define FRONTIER_MON_KLEAVOR                    534
#define FRONTIER_MON_URSALUNA                   535
#define FRONTIER_MON_URSALUNA_BLOODMOON         536
#define FRONTIER_MON_BASCULEGION                537
#define FRONTIER_MON_SNEASLER                   538
#define FRONTIER_MON_OVERQWIL                   539
#define FRONTIER_MON_ENAMORUS                   540
#define FRONTIER_MON_ENAMORUS_THERIAN           541
#define FRONTIER_MON_MEOWSCARADA                542
#define FRONTIER_MON_SKELEDIRGE                 543
#define FRONTIER_MON_QUAQUAVAL                  544
#define FRONTIER_MON_LOKIX                      545
#define FRONTIER_MON_PAWMOT                     546
#define FRONTIER_MON_MAUSHOLD                   547
#define FRONTIER_MON_GARGANACL                  548
#define FRONTIER_MON_ARMAROUGE                  549
#define FRONTIER_MON_CERULEDGE                  550
#define FRONTIER_MON_KILOWATTREL                551
#define FRONTIER_MON_TOEDSCRUEL                 552
#define FRONTIER_MON_ESPATHRA                   553
#define FRONTIER_MON_TINKATON                   554
#define FRONTIER_MON_PALAFIN                    555
#define FRONTIER_MON_CYCLIZAR                   556
#define FRONTIER_MON_GLIMMORA                   557
#define FRONTIER_MON_DONDOZO                    558
#define FRONTIER_MON_ANNIHILAPE                 559
#define FRONTIER_MON_CLODSIRE                   560
#define FRONTIER_MON_KINGAMBIT                  561
#define FRONTIER_MON_GREAT_TUSK                 562
#define FRONTIER_MON_SCREAM_TAIL                563
#define FRONTIER_MON_BRUTE_BONNET               564
#define FRONTIER_MON_FLUTTER_MANE               565
#define FRONTIER_MON_SLITHER_WING               566
#define FRONTIER_MON_SANDY_SHOCKS               567
#define FRONTIER_MON_IRON_TREADS                568
#define FRONTIER_MON_IRON_BUNDLE                569
#define FRONTIER_MON_IRON_HANDS                 570
#define FRONTIER_MON_IRON_JUGULIS               571
#define FRONTIER_MON_IRON_MOTH                  572
#define FRONTIER_MON_IRON_THORNS                573
#define FRONTIER_MON_BAXCALIBUR                 574
#define FRONTIER_MON_GHOLDENGO                  575
#define FRONTIER_MON_WO_CHIEN                   576
#define FRONTIER_MON_CHIEN_PAO                  577
#define FRONTIER_MON_TING_LU                    578
#define FRONTIER_MON_CHI_YU                     579
#define FRONTIER_MON_ROARING_MOON               580
#define FRONTIER_MON_IRON_VALIANT               581
#define FRONTIER_MON_WALKING_WAKE               582
#define FRONTIER_MON_IRON_LEAVES                583
#define FRONTIER_MON_DIPPLIN                    584
#define FRONTIER_MON_SINISTCHA                  585
#define FRONTIER_MON_OKIDOGI                    586
#define FRONTIER_MON_MUNKIDORI                  587
#define FRONTIER_MON_FEZANDIPITI                588
#define FRONTIER_MON_OGERPON                    589
#define FRONTIER_MON_SCALEON                    590

#define FRONTIER_MONS_HIGH_TIER     339 // Mons above this point can only appear > level 50

#define NUM_FRONTIER_MONS           591

#endif //GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
