
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE                  0
#define PARTNER_STEVEN_MOSSDEEP       1
#define PARTNER_MAY_METEOR_FALLS      2
#define PARTNER_BRENDAN_METEOR_FALLS  3
#define PARTNER_RAYQUAZA              4
#define PARTNER_STEVEN_GRANITE_CAVE   5

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
