#ifndef GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
#define GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H

#define FRONTIER_MON_BUTTERFREE                 0
#define FRONTIER_MON_BEEDRILL                   1
#define FRONTIER_MON_PIDGEOT                    2
#define FRONTIER_MON_RATICATE                   3
#define FRONTIER_MON_RATICATE_ALOLAN            4
#define FRONTIER_MON_FEAROW                     5
#define FRONTIER_MON_ARBOK                      6
#define FRONTIER_MON_RAICHU                     7
#define FRONTIER_MON_RAICHU_ALOLAN              8
#define FRONTIER_MON_SANDSLASH                  9
#define FRONTIER_MON_SANDSLASH_ALOLAN           10
#define FRONTIER_MON_NIDOQUEEN                  11
#define FRONTIER_MON_NIDOKING                   12
#define FRONTIER_MON_NINETALES                  13
#define FRONTIER_MON_WIGGLYTUFF                 14
#define FRONTIER_MON_VILEPLUME                  15
#define FRONTIER_MON_PARASECT                   16
#define FRONTIER_MON_VENOMOTH                   17
#define FRONTIER_MON_DUGTRIO                    18
#define FRONTIER_MON_DUGTRIO_ALOLAN             19
#define FRONTIER_MON_PERSIAN                    20
#define FRONTIER_MON_PERSIAN_ALOLAN             21
#define FRONTIER_MON_GOLDUCK                    22
#define FRONTIER_MON_ARCANINE                   23
#define FRONTIER_MON_POLIWRATH                  24
#define FRONTIER_MON_MACHAMP                    25
#define FRONTIER_MON_VICTREEBEL                 26
#define FRONTIER_MON_GOLEM                      27
#define FRONTIER_MON_GOLEM_ALOLAN               28
#define FRONTIER_MON_GOLEM_FRIBIAN              29
#define FRONTIER_MON_RAPIDASH                   30
#define FRONTIER_MON_RAPIDASH_GALARIAN          31
#define FRONTIER_MON_SLOWBRO_GALARIAN           32
#define FRONTIER_MON_FARFETCHD                  33
#define FRONTIER_MON_DODRIO                     34
#define FRONTIER_MON_DEWGONG                    35
#define FRONTIER_MON_MUK                        36
#define FRONTIER_MON_MUK_ALOLAN                 37
#define FRONTIER_MON_HYPNO                      38
#define FRONTIER_MON_KINGLER                    39
#define FRONTIER_MON_ELECTRODE                  40
#define FRONTIER_MON_EXEGGUTOR                  41
#define FRONTIER_MON_EXEGGUTOR_ALOLAN           42
#define FRONTIER_MON_MAROWAK                    43
#define FRONTIER_MON_MAROWAK_ALOLAN             44
#define FRONTIER_MON_HITMONLEE                  45
#define FRONTIER_MON_HITMONCHAN                 46
#define FRONTIER_MON_WEEZING                    47
#define FRONTIER_MON_KANGASKHAN                 48
#define FRONTIER_MON_SEAKING                    49
#define FRONTIER_MON_MR_MIME                    50
#define FRONTIER_MON_JYNX                       51
#define FRONTIER_MON_PINSIR                     52
#define FRONTIER_MON_TAUROS                     53
#define FRONTIER_MON_TAUROS_PALDEAN             54
#define FRONTIER_MON_LAPRAS                     55
#define FRONTIER_MON_DITTO                      56
#define FRONTIER_MON_VAPOREON                   57
#define FRONTIER_MON_JOLTEON                    58
#define FRONTIER_MON_FLAREON                    59
#define FRONTIER_MON_OMASTAR                    60
#define FRONTIER_MON_KABUTOPS                   61
#define FRONTIER_MON_AERODACTYL                 62
#define FRONTIER_MON_FURRET                     63
#define FRONTIER_MON_NOCTOWL                    64
#define FRONTIER_MON_LEDIAN                     65
#define FRONTIER_MON_CROBAT                     66
#define FRONTIER_MON_LANTURN                    67
#define FRONTIER_MON_XATU                       68
#define FRONTIER_MON_AMPHAROS                   69
#define FRONTIER_MON_BELLOSSOM                  70
#define FRONTIER_MON_SUDOWOODO                  71
#define FRONTIER_MON_JUMPLUFF                   72
#define FRONTIER_MON_SUNFLORA                   73
#define FRONTIER_MON_ESPEON                     74
#define FRONTIER_MON_WOBBUFFET                  75
#define FRONTIER_MON_FORRETRESS                 76
#define FRONTIER_MON_STEELIX                    77
#define FRONTIER_MON_GRANBULL                   78
#define FRONTIER_MON_QWILFISH                   79
#define FRONTIER_MON_HERACROSS                  80
#define FRONTIER_MON_MAGCARGO                   81
#define FRONTIER_MON_CORSOLA                    82
#define FRONTIER_MON_OCTILLERY                  83
#define FRONTIER_MON_OCTILLERY_FRIBIAN          84
#define FRONTIER_MON_DELIBIRD                   85
#define FRONTIER_MON_MANTINE                    86
#define FRONTIER_MON_HOUNDOOM                   87
#define FRONTIER_MON_KINGDRA                    88
#define FRONTIER_MON_SMEARGLE                   89
#define FRONTIER_MON_HITMONTOP                  90
#define FRONTIER_MON_MILTANK                    91
#define FRONTIER_MON_MIGHTYENA                  92
#define FRONTIER_MON_BEAUTIFLY                  93
#define FRONTIER_MON_DUSTOX                     94
#define FRONTIER_MON_LUDICOLO                   95
#define FRONTIER_MON_SHIFTRY                    96
#define FRONTIER_MON_SWELLOW                    97
#define FRONTIER_MON_GARDEVOIR                  98
#define FRONTIER_MON_MASQUERAIN                 99
#define FRONTIER_MON_SLAKING                    100
#define FRONTIER_MON_NINJASK                    101
#define FRONTIER_MON_SHEDINJA                   102
#define FRONTIER_MON_EXPLOUD                    103
#define FRONTIER_MON_HARIYAMA                   104
#define FRONTIER_MON_DELCATTY                   105
#define FRONTIER_MON_SABLEYE                    106
#define FRONTIER_MON_MAWILE                     107
#define FRONTIER_MON_AGGRON                     108
#define FRONTIER_MON_MEDICHAM                   109
#define FRONTIER_MON_MANECTRIC                  110
#define FRONTIER_MON_PLUSLE                     111
#define FRONTIER_MON_MINUN                      112
#define FRONTIER_MON_VOLBEAT                    113
#define FRONTIER_MON_ILLUMISE                   114
#define FRONTIER_MON_SWALOT                     115
#define FRONTIER_MON_SHARPEDO                   116
#define FRONTIER_MON_WAILORD                    117
#define FRONTIER_MON_CAMERUPT                   118
#define FRONTIER_MON_GRUMPIG                    119
#define FRONTIER_MON_SPINDA                     120
#define FRONTIER_MON_CACTURNE                   121
#define FRONTIER_MON_ALTARIA                    122
#define FRONTIER_MON_ZANGOOSE                   123
#define FRONTIER_MON_SEVIPER                    124
#define FRONTIER_MON_LUNATONE                   125
#define FRONTIER_MON_SOLROCK                    126
#define FRONTIER_MON_WHISCASH                   127
#define FRONTIER_MON_CLAYDOL                    128
#define FRONTIER_MON_CRADILY                    129
#define FRONTIER_MON_ARMALDO                    130
#define FRONTIER_MON_CASTFORM                   131
#define FRONTIER_MON_KECLEON                    132
#define FRONTIER_MON_BANETTE                    133
#define FRONTIER_MON_TROPIUS                    134
#define FRONTIER_MON_CHIMECHO                   135
#define FRONTIER_MON_ABSOL                      136
#define FRONTIER_MON_GLALIE                     137
#define FRONTIER_MON_WALREIN                    138
#define FRONTIER_MON_HUNTAIL                    139
#define FRONTIER_MON_GOREBYSS                   140
#define FRONTIER_MON_RELICANTH                  141
#define FRONTIER_MON_LUVDISC                    142
#define FRONTIER_MON_KRICKETUNE                 143
#define FRONTIER_MON_LUXRAY                     144
#define FRONTIER_MON_RAMPARDOS                  145
#define FRONTIER_MON_BASTIODON                  146
#define FRONTIER_MON_WORMADAM                   147
#define FRONTIER_MON_MOTHIM                     148
#define FRONTIER_MON_VESPIQUEN                  149
#define FRONTIER_MON_PACHIRISU                  150
#define FRONTIER_MON_FLOATZEL                   151
#define FRONTIER_MON_CHERRIM                    152
#define FRONTIER_MON_AMBIPOM                    153
#define FRONTIER_MON_DRIFBLIM                   154
#define FRONTIER_MON_LOPUNNY                    155
#define FRONTIER_MON_MISMAGIUS                  156
#define FRONTIER_MON_HONCHKROW                  157
#define FRONTIER_MON_PURUGLY                    158
#define FRONTIER_MON_SKUNTANK                   159
#define FRONTIER_MON_BRONZONG                   160
#define FRONTIER_MON_CHATOT                     161
#define FRONTIER_MON_SPIRITOMB                  162
#define FRONTIER_MON_DRAPION                    163
#define FRONTIER_MON_TOXICROAK                  164
#define FRONTIER_MON_CARNIVINE                  165
#define FRONTIER_MON_LUMINEON                   166
#define FRONTIER_MON_LICKILICKY                 167
#define FRONTIER_MON_ELECTIVIRE                 168
#define FRONTIER_MON_MAGMORTAR                  169
#define FRONTIER_MON_YANMEGA                    170
#define FRONTIER_MON_LEAFEON                    171
#define FRONTIER_MON_GLACEON                    172
#define FRONTIER_MON_PORYGON_Z                  173
#define FRONTIER_MON_PROBOPASS                  174
#define FRONTIER_MON_DUSKNOIR                   175
#define FRONTIER_MON_ROTOM                      176
#define FRONTIER_MON_PHIONE                     177
#define FRONTIER_MON_WATCHOG                    178
#define FRONTIER_MON_STOUTLAND                  179
#define FRONTIER_MON_LIEPARD                    180
#define FRONTIER_MON_SIMISAGE                   181
#define FRONTIER_MON_SIMISEAR                   182
#define FRONTIER_MON_SIMIPOUR                   183
#define FRONTIER_MON_MUSHARNA                   184
#define FRONTIER_MON_UNFEZANT                   185
#define FRONTIER_MON_ZEBSTRIKA                  186
#define FRONTIER_MON_GIGALITH                   187
#define FRONTIER_MON_GIGALITH_FRIBIAN           188
#define FRONTIER_MON_SWOOBAT                    189
#define FRONTIER_MON_AUDINO                     190
#define FRONTIER_MON_THROH                      191
#define FRONTIER_MON_SAWK                       192
#define FRONTIER_MON_LEAVANNY                   193
#define FRONTIER_MON_MARACTUS                   194
#define FRONTIER_MON_CRUSTLE                    195
#define FRONTIER_MON_SCRAFTY                    196
#define FRONTIER_MON_SIGILYPH                   197
#define FRONTIER_MON_COFAGRIGUS                 198
#define FRONTIER_MON_CARRACOSTA                 199
#define FRONTIER_MON_ARCHEOPS                   200
#define FRONTIER_MON_GARBODOR                   201
#define FRONTIER_MON_ZOROARK                    202
#define FRONTIER_MON_CINCCINO                   203
#define FRONTIER_MON_SWANNA                     204
#define FRONTIER_MON_SAWSBUCK                   205
#define FRONTIER_MON_EMOLGA                     206
#define FRONTIER_MON_ESCAVALIER                 207
#define FRONTIER_MON_KLINKLANG                  208
#define FRONTIER_MON_EELEKTROSS                 209
#define FRONTIER_MON_BEHEEYEM                   210
#define FRONTIER_MON_BEARTIC                    211
#define FRONTIER_MON_CRYOGONAL                  212
#define FRONTIER_MON_ACCELGOR                   213
#define FRONTIER_MON_STUNFISK                   214
#define FRONTIER_MON_STUNFISK_GALARIAN          215
#define FRONTIER_MON_DRUDDIGON                  216
#define FRONTIER_MON_GOLURK                     217
#define FRONTIER_MON_BOUFFALANT                 218
#define FRONTIER_MON_BRAVIARY                   219
#define FRONTIER_MON_HEATMOR                    220
#define FRONTIER_MON_VIVILLON                   221
#define FRONTIER_MON_PYROAR                     222
#define FRONTIER_MON_GOGOAT                     223
#define FRONTIER_MON_PANGORO                    224
#define FRONTIER_MON_FURFROU                    225
#define FRONTIER_MON_MEOWSTIC                   226
#define FRONTIER_MON_MEOWSTIC_FEMALE            227
#define FRONTIER_MON_AROMATISSE                 228
#define FRONTIER_MON_SLURPUFF                   229
#define FRONTIER_MON_MALAMAR                    230
#define FRONTIER_MON_CLAWITZER                  231
#define FRONTIER_MON_TYRANTRUM                  232
#define FRONTIER_MON_AURORUS                    233
#define FRONTIER_MON_DEDENNE                    234
#define FRONTIER_MON_CARBINK                    235
#define FRONTIER_MON_GOODRA                     236
#define FRONTIER_MON_TREVENANT                  237
#define FRONTIER_MON_GOURGEIST                  238
#define FRONTIER_MON_AVALUGG                    239
#define FRONTIER_MON_AVALUGG_HISUIAN            240
#define FRONTIER_MON_TOUCANNON                  241
#define FRONTIER_MON_GUMSHOOS                   242
#define FRONTIER_MON_VIKAVOLT                   243
#define FRONTIER_MON_CRABOMINABLE               244
#define FRONTIER_MON_ORICORIO                   245
#define FRONTIER_MON_LYCANROC                   246
#define FRONTIER_MON_LYCANROC_MIDNIGHT          247
#define FRONTIER_MON_LYCANROC_DUSK              248
#define FRONTIER_MON_WISHIWASHI                 249
#define FRONTIER_MON_MUDSDALE                   250
#define FRONTIER_MON_ARAQUANID                  251
#define FRONTIER_MON_LURANTIS                   252
#define FRONTIER_MON_SHIINOTIC                  253
#define FRONTIER_MON_BEWEAR                     254
#define FRONTIER_MON_COMFEY                     255
#define FRONTIER_MON_ORANGURU                   256
#define FRONTIER_MON_PASSIMIAN                  257
#define FRONTIER_MON_PALOSSAND                  258
#define FRONTIER_MON_PYUKUMUKU                  259
#define FRONTIER_MON_SILVALLY                   260
#define FRONTIER_MON_MINIOR                     261
#define FRONTIER_MON_KOMALA                     262
#define FRONTIER_MON_TURTONATOR                 263
#define FRONTIER_MON_TOGEDEMARU                 264
#define FRONTIER_MON_BRUXISH                    265
#define FRONTIER_MON_DRAMPA                     266
#define FRONTIER_MON_GUZZLORD                   267
#define FRONTIER_MON_STAKATAKA                  268
#define FRONTIER_MON_GREEDENT                   269
#define FRONTIER_MON_ORBEETLE                   270
#define FRONTIER_MON_THIEVUL                    271
#define FRONTIER_MON_ELDEGOSS                   272
#define FRONTIER_MON_DUBWOOL                    273
#define FRONTIER_MON_DUBWOOL_FRIBIAN            274
#define FRONTIER_MON_DREDNAW                    275
#define FRONTIER_MON_BOLTUND                    276
#define FRONTIER_MON_COALOSSAL                  277
#define FRONTIER_MON_FLAPPLE                    278
#define FRONTIER_MON_APPLETUN                   279
#define FRONTIER_MON_SANDACONDA                 280
#define FRONTIER_MON_CRAMORANT                  281
#define FRONTIER_MON_CENTISKORCH                282
#define FRONTIER_MON_GRAPPLOCT                  283
#define FRONTIER_MON_PERRSERKER                 284
#define FRONTIER_MON_CURSOLA                    285
#define FRONTIER_MON_SIRFETCHD                  286
#define FRONTIER_MON_MR_RIME                    287
#define FRONTIER_MON_RUNERIGUS                  288
#define FRONTIER_MON_ALCREMIE                   289
#define FRONTIER_MON_FALINKS                    290
#define FRONTIER_MON_PINCURCHIN                 291
#define FRONTIER_MON_FROSMOTH                   292
#define FRONTIER_MON_STONJOURNER                293
#define FRONTIER_MON_EISCUE                     294
#define FRONTIER_MON_MORPEKO                    295
#define FRONTIER_MON_COPPERAJAH                 296
#define FRONTIER_MON_ARCTOVISH                  297
#define FRONTIER_MON_DURALUDON                  298
#define FRONTIER_MON_WYRDEER                    299
#define FRONTIER_MON_OINKOLOGNE                 300
#define FRONTIER_MON_SPIDOPS                    301
#define FRONTIER_MON_DACHSBUN                   302
#define FRONTIER_MON_ARBOLIVA                   303
#define FRONTIER_MON_SQUAWKABILLY               304
#define FRONTIER_MON_BELLIBOLT                  305
#define FRONTIER_MON_MABOSSTIFF                 306
#define FRONTIER_MON_GRAFAIAI                   307
#define FRONTIER_MON_BRAMBLEGHAST               308
#define FRONTIER_MON_KLAWF                      309
#define FRONTIER_MON_SCOVILLAIN                 310
#define FRONTIER_MON_RABSCA                     311
#define FRONTIER_MON_WUGTRIO                    312
#define FRONTIER_MON_BOMBIRDIER                 313
#define FRONTIER_MON_REVAVROOM                  314
#define FRONTIER_MON_ORTHWORM                   315
#define FRONTIER_MON_HOUNDSTONE                 316
#define FRONTIER_MON_FLAMIGO                    317
#define FRONTIER_MON_CETITAN                    318
#define FRONTIER_MON_VELUZA                     319
#define FRONTIER_MON_TATSUGIRI                  320
#define FRONTIER_MON_FARIGIRAF                  321
#define FRONTIER_MON_DUDUNSPARCE                322
#define FRONTIER_MON_EVALEON                    323
#define FRONTIER_MON_AEREON                     324
#define FRONTIER_MON_CONTAGEON                  325
#define FRONTIER_MON_LANEON                     326

#define FRONTIER_MON_VENUSAUR                   327
#define FRONTIER_MON_CHARIZARD                  328
#define FRONTIER_MON_BLASTOISE                  329
#define FRONTIER_MON_CLEFABLE                   330
#define FRONTIER_MON_NINETALES_ALOLAN           331
#define FRONTIER_MON_ARCANINE_HISUIAN           332
#define FRONTIER_MON_ALAKAZAM                   333
#define FRONTIER_MON_TENTACRUEL                 334
#define FRONTIER_MON_SLOWBRO                    335
#define FRONTIER_MON_CLOYSTER                   336
#define FRONTIER_MON_CLOYSTER_FRIBIAN           337
#define FRONTIER_MON_GENGAR                     338
#define FRONTIER_MON_ELECTRODE_HISUIAN          339
#define FRONTIER_MON_WEEZING_GALARIAN           340
#define FRONTIER_MON_STARMIE                    341
#define FRONTIER_MON_TAUROS_PALDEAN_AQUA_BREED  342
#define FRONTIER_MON_TAUROS_PALDEAN_BLAZE_BREED 343
#define FRONTIER_MON_GYARADOS                   344
#define FRONTIER_MON_SNORLAX                    345
#define FRONTIER_MON_ARTICUNO                   346
#define FRONTIER_MON_ARTICUNO_GALARIAN          347
#define FRONTIER_MON_ZAPDOS                     348
#define FRONTIER_MON_ZAPDOS_GALARIAN            349
#define FRONTIER_MON_MOLTRES                    350
#define FRONTIER_MON_MOLTRES_GALARIAN           351
#define FRONTIER_MON_DRAGONITE                  352
#define FRONTIER_MON_MEGANIUM                   353
#define FRONTIER_MON_TYPHLOSION                 354
#define FRONTIER_MON_TYPHLOSION_HISUIAN         355
#define FRONTIER_MON_FERALIGATR                 356
#define FRONTIER_MON_ARIADOS                    357
#define FRONTIER_MON_AZUMARILL                  358
#define FRONTIER_MON_POLITOED                   359
#define FRONTIER_MON_QUAGSIRE                   360
#define FRONTIER_MON_UMBREON                    361
#define FRONTIER_MON_SLOWKING                   362
#define FRONTIER_MON_SLOWKING_GALARIAN          363
#define FRONTIER_MON_SCIZOR                     364
#define FRONTIER_MON_SHUCKLE                    365
#define FRONTIER_MON_SHUCKLE_FRIBIAN            366
#define FRONTIER_MON_SKARMORY                   367
#define FRONTIER_MON_SKARMORY_FRIBIAN           368
#define FRONTIER_MON_DONPHAN                    369
#define FRONTIER_MON_BLISSEY                    370
#define FRONTIER_MON_RAIKOU                     371
#define FRONTIER_MON_ENTEI                      372
#define FRONTIER_MON_SUICUNE                    373
#define FRONTIER_MON_TYRANITAR                  374
#define FRONTIER_MON_SCEPTILE                   375
#define FRONTIER_MON_BLAZIKEN                   376
#define FRONTIER_MON_SWAMPERT                   377
#define FRONTIER_MON_LINOONE                    378
#define FRONTIER_MON_PELIPPER                   379
#define FRONTIER_MON_BRELOOM                    380
#define FRONTIER_MON_BRELOOM_FRIBIAN            381
#define FRONTIER_MON_TORKOAL                    382
#define FRONTIER_MON_FLYGON                     383
#define FRONTIER_MON_CRAWDAUNT                  384
#define FRONTIER_MON_MILOTIC                    385
#define FRONTIER_MON_SALAMENCE                  386
#define FRONTIER_MON_METAGROSS                  387
#define FRONTIER_MON_REGIROCK                   388
#define FRONTIER_MON_REGICE                     389
#define FRONTIER_MON_REGISTEEL                  390
#define FRONTIER_MON_LATIAS                     391
#define FRONTIER_MON_LATIOS                     392
#define FRONTIER_MON_TORTERRA                   393
#define FRONTIER_MON_INFERNAPE                  394
#define FRONTIER_MON_EMPOLEON                   395
#define FRONTIER_MON_STARAPTOR                  396
#define FRONTIER_MON_BIBAREL                    397
#define FRONTIER_MON_ROSERADE                   398
#define FRONTIER_MON_GASTRODON                  399
#define FRONTIER_MON_GARCHOMP                   400
#define FRONTIER_MON_LUCARIO                    401
#define FRONTIER_MON_HIPPOWDON                  402
#define FRONTIER_MON_ABOMASNOW                  403
#define FRONTIER_MON_WEAVILE                    404
#define FRONTIER_MON_MAGNEZONE                  405
#define FRONTIER_MON_RHYPERIOR                  406
#define FRONTIER_MON_TANGROWTH                  407
#define FRONTIER_MON_TOGEKISS                   408
#define FRONTIER_MON_GLISCOR                    409
#define FRONTIER_MON_MAMOSWINE                  410
#define FRONTIER_MON_GALLADE                    411
#define FRONTIER_MON_FROSLASS                   412
#define FRONTIER_MON_UXIE                       413
#define FRONTIER_MON_MESPRIT                    414
#define FRONTIER_MON_AZELF                      415
#define FRONTIER_MON_HEATRAN                    416
#define FRONTIER_MON_CRESSELIA                  417
#define FRONTIER_MON_SERPERIOR                  418
#define FRONTIER_MON_EMBOAR                     419
#define FRONTIER_MON_SAMUROTT                   420
#define FRONTIER_MON_SAMUROTT_HISUIAN           421
#define FRONTIER_MON_EXCADRILL                  422
#define FRONTIER_MON_CONKELDURR                 423
#define FRONTIER_MON_SEISMITOAD                 424
#define FRONTIER_MON_SCOLIPEDE                  425
#define FRONTIER_MON_WHIMSICOTT                 426
#define FRONTIER_MON_LILLIGANT                  427
#define FRONTIER_MON_LILLIGANT_HISUIAN          428
#define FRONTIER_MON_KROOKODILE                 429
#define FRONTIER_MON_DARMANITAN                 430
#define FRONTIER_MON_DARMANITAN_GALARIAN        431
#define FRONTIER_MON_ZOROARK_HISUIAN            432
#define FRONTIER_MON_GOTHITELLE                 433
#define FRONTIER_MON_REUNICLUS                  434
#define FRONTIER_MON_VANILLUXE                  435
#define FRONTIER_MON_AMOONGUSS                  436
#define FRONTIER_MON_JELLICENT                  437
#define FRONTIER_MON_ALOMOMOLA                  438
#define FRONTIER_MON_GALVANTULA                 439
#define FRONTIER_MON_FERROTHORN                 440
#define FRONTIER_MON_CHANDELURE                 441
#define FRONTIER_MON_HAXORUS                    442
#define FRONTIER_MON_MIENSHAO                   443
#define FRONTIER_MON_BRAVIARY_HISUIAN           444
#define FRONTIER_MON_MANDIBUZZ                  445
#define FRONTIER_MON_DURANT                     446
#define FRONTIER_MON_HYDREIGON                  447
#define FRONTIER_MON_VOLCARONA                  448
#define FRONTIER_MON_COBALION                   449
#define FRONTIER_MON_TERRAKION                  450
#define FRONTIER_MON_VIRIZION                   451
#define FRONTIER_MON_TORNADUS                   452
#define FRONTIER_MON_TORNADUS_THERIAN           453
#define FRONTIER_MON_THUNDURUS                  454
#define FRONTIER_MON_THUNDURUS_THERIAN          455
#define FRONTIER_MON_KELDEO                     456
#define FRONTIER_MON_CHESNAUGHT                 457
#define FRONTIER_MON_DELPHOX                    458
#define FRONTIER_MON_GRENINJA                   459
#define FRONTIER_MON_GRENINJA_2                 460
#define FRONTIER_MON_DIGGERSBY                  461
#define FRONTIER_MON_TALONFLAME                 462
#define FRONTIER_MON_FLORGES                    463
#define FRONTIER_MON_AEGISLASH                  464
#define FRONTIER_MON_BARBARACLE                 465
#define FRONTIER_MON_DRAGALGE                   466
#define FRONTIER_MON_HELIOLISK                  467
#define FRONTIER_MON_SYLVEON                    468
#define FRONTIER_MON_HAWLUCHA                   469
#define FRONTIER_MON_GOODRA_HISUIAN             470
#define FRONTIER_MON_KLEFKI                     471
#define FRONTIER_MON_NOIVERN                    472
#define FRONTIER_MON_DECIDUEYE                  473
#define FRONTIER_MON_DECIDUEYE_HISUIAN          474
#define FRONTIER_MON_INCINEROAR                 475
#define FRONTIER_MON_PRIMARINA                  476
#define FRONTIER_MON_RIBOMBEE                   477
#define FRONTIER_MON_TOXAPEX                    478
#define FRONTIER_MON_SALAZZLE                   479
#define FRONTIER_MON_TSAREENA                   480
#define FRONTIER_MON_GOLISOPOD                  481
#define FRONTIER_MON_MIMIKYU                    482
#define FRONTIER_MON_DHELMISE                   483
#define FRONTIER_MON_KOMMO_O                    484
#define FRONTIER_MON_TAPU_KOKO                  485
#define FRONTIER_MON_TAPU_LELE                  486
#define FRONTIER_MON_TAPU_BULU                  487
#define FRONTIER_MON_TAPU_FINI                  488
#define FRONTIER_MON_NIHILEGO                   489
#define FRONTIER_MON_BUZZWOLE                   490
#define FRONTIER_MON_PHEROMOSA                  491
#define FRONTIER_MON_XURKITREE                  492
#define FRONTIER_MON_CELESTEELA                 493
#define FRONTIER_MON_KARTANA                    494
#define FRONTIER_MON_NAGANADEL                  495
#define FRONTIER_MON_BLACEPHALON                496
#define FRONTIER_MON_RILLABOOM                  497
#define FRONTIER_MON_CINDERACE                  498
#define FRONTIER_MON_INTELEON                   499
#define FRONTIER_MON_CORVIKNIGHT                500
#define FRONTIER_MON_BARRASKEWDA                501
#define FRONTIER_MON_TOXTRICITY                 502
#define FRONTIER_MON_POLTEAGEIST                503
#define FRONTIER_MON_HATTERENE                  504
#define FRONTIER_MON_GRIMMSNARL                 505
#define FRONTIER_MON_OBSTAGOON                  506
#define FRONTIER_MON_INDEEDEE                   507
#define FRONTIER_MON_DRACOZOLT                  508
#define FRONTIER_MON_ARCTOZOLT                  509
#define FRONTIER_MON_DRACOVISH                  510
#define FRONTIER_MON_DRAGAPULT                  511
#define FRONTIER_MON_URSHIFU_RAPID_STRIKE_STYLE 512
#define FRONTIER_MON_URSHIFU                    513
#define FRONTIER_MON_REGIELEKI                  514
#define FRONTIER_MON_REGIDRAGO                  515
#define FRONTIER_MON_GLASTRIER                  516
#define FRONTIER_MON_SPECTRIER                  517
#define FRONTIER_MON_CALYREX                    518
#define FRONTIER_MON_KLEAVOR                    519
#define FRONTIER_MON_URSALUNA                   520
#define FRONTIER_MON_URSALUNA_BLOODMOON         521
#define FRONTIER_MON_BASCULEGION                522
#define FRONTIER_MON_SNEASLER                   523
#define FRONTIER_MON_OVERQWIL                   524
#define FRONTIER_MON_ENAMORUS                   525
#define FRONTIER_MON_ENAMORUS_THERIAN           526
#define FRONTIER_MON_MEOWSCARADA                527
#define FRONTIER_MON_SKELEDIRGE                 528
#define FRONTIER_MON_QUAQUAVAL                  529
#define FRONTIER_MON_LOKIX                      530
#define FRONTIER_MON_PAWMOT                     531
#define FRONTIER_MON_MAUSHOLD                   532
#define FRONTIER_MON_GARGANACL                  533
#define FRONTIER_MON_ARMAROUGE                  534
#define FRONTIER_MON_CERULEDGE                  535
#define FRONTIER_MON_KILOWATTREL                536
#define FRONTIER_MON_TOEDSCRUEL                 537
#define FRONTIER_MON_ESPATHRA                   538
#define FRONTIER_MON_TINKATON                   539
#define FRONTIER_MON_PALAFIN                    540
#define FRONTIER_MON_CYCLIZAR                   541
#define FRONTIER_MON_GLIMMORA                   542
#define FRONTIER_MON_DONDOZO                    543
#define FRONTIER_MON_ANNIHILAPE                 544
#define FRONTIER_MON_CLODSIRE                   545
#define FRONTIER_MON_KINGAMBIT                  546
#define FRONTIER_MON_GREAT_TUSK                 547
#define FRONTIER_MON_SCREAM_TAIL                548
#define FRONTIER_MON_BRUTE_BONNET               549
#define FRONTIER_MON_FLUTTER_MANE               550
#define FRONTIER_MON_SLITHER_WING               551
#define FRONTIER_MON_SANDY_SHOCKS               552
#define FRONTIER_MON_IRON_TREADS                553
#define FRONTIER_MON_IRON_BUNDLE                554
#define FRONTIER_MON_IRON_HANDS                 555
#define FRONTIER_MON_IRON_JUGULIS               556
#define FRONTIER_MON_IRON_MOTH                  557
#define FRONTIER_MON_IRON_THORNS                558
#define FRONTIER_MON_BAXCALIBUR                 559
#define FRONTIER_MON_GHOLDENGO                  560
#define FRONTIER_MON_WO_CHIEN                   561
#define FRONTIER_MON_CHIEN_PAO                  562
#define FRONTIER_MON_TING_LU                    563
#define FRONTIER_MON_CHI_YU                     564
#define FRONTIER_MON_ROARING_MOON               565
#define FRONTIER_MON_IRON_VALIANT               566
#define FRONTIER_MON_WALKING_WAKE               567
#define FRONTIER_MON_IRON_LEAVES                568
#define FRONTIER_MON_DIPPLIN                    569
#define FRONTIER_MON_SINISTCHA                  570
#define FRONTIER_MON_OKIDOGI                    571
#define FRONTIER_MON_MUNKIDORI                  572
#define FRONTIER_MON_FEZANDIPITI                573
#define FRONTIER_MON_SCALEON                    574

#define FRONTIER_MONS_HIGH_TIER     327 // Mons above this point can only appear > level 50

#define NUM_FRONTIER_MONS           575

#endif //GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
