#ifndef GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
#define GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H

#define FRONTIER_MON_BUTTERFREE                 0
#define FRONTIER_MON_BEEDRILL                   1
#define FRONTIER_MON_PIDGEOT                    2
#define FRONTIER_MON_RATICATE                   3
#define FRONTIER_MON_RATICATE_ALOLAN            4
#define FRONTIER_MON_FEAROW                     5
#define FRONTIER_MON_ARBOK                      6
#define FRONTIER_MON_RAICHU                     7
#define FRONTIER_MON_RAICHU_ALOLAN              8
#define FRONTIER_MON_SANDSLASH                  9
#define FRONTIER_MON_SANDSLASH_ALOLAN           10
#define FRONTIER_MON_NIDOQUEEN                  11
#define FRONTIER_MON_NIDOKING                   12
#define FRONTIER_MON_NINETALES                  13
#define FRONTIER_MON_NINETALES_EMERIBIAN        14
#define FRONTIER_MON_WIGGLYTUFF                 15
#define FRONTIER_MON_VILEPLUME                  16
#define FRONTIER_MON_VILEPLUME_EMERIBIAN        17
#define FRONTIER_MON_PARASECT                   18
#define FRONTIER_MON_VENOMOTH                   19
#define FRONTIER_MON_DUGTRIO                    20
#define FRONTIER_MON_DUGTRIO_ALOLAN             21
#define FRONTIER_MON_PERSIAN                    22
#define FRONTIER_MON_PERSIAN_ALOLAN             23
#define FRONTIER_MON_GOLDUCK                    24
#define FRONTIER_MON_ARCANINE                   25
#define FRONTIER_MON_POLIWRATH                  26
#define FRONTIER_MON_MACHAMP                    27
#define FRONTIER_MON_VICTREEBEL                 28
#define FRONTIER_MON_GOLEM                      29
#define FRONTIER_MON_GOLEM_ALOLAN               30
#define FRONTIER_MON_GOLEM_FRIBIAN              31
#define FRONTIER_MON_RAPIDASH                   32
#define FRONTIER_MON_RAPIDASH_GALARIAN          33
#define FRONTIER_MON_SLOWBRO_GALARIAN           34
#define FRONTIER_MON_FARFETCHD                  35
#define FRONTIER_MON_DODRIO                     36
#define FRONTIER_MON_DODRIO_EMERIBIAN           37
#define FRONTIER_MON_DEWGONG                    38
#define FRONTIER_MON_MUK                        39
#define FRONTIER_MON_MUK_ALOLAN                 40
#define FRONTIER_MON_HYPNO                      41
#define FRONTIER_MON_KINGLER                    42
#define FRONTIER_MON_ELECTRODE                  43
#define FRONTIER_MON_EXEGGUTOR                  44
#define FRONTIER_MON_EXEGGUTOR_ALOLAN           45
#define FRONTIER_MON_MAROWAK                    46
#define FRONTIER_MON_MAROWAK_ALOLAN             47
#define FRONTIER_MON_HITMONLEE                  48
#define FRONTIER_MON_HITMONCHAN                 49
#define FRONTIER_MON_WEEZING                    50
#define FRONTIER_MON_KANGASKHAN                 51
#define FRONTIER_MON_SEAKING                    52
#define FRONTIER_MON_MR_MIME                    53
#define FRONTIER_MON_JYNX                       54
#define FRONTIER_MON_PINSIR                     55
#define FRONTIER_MON_TAUROS                     56
#define FRONTIER_MON_TAUROS_PALDEAN             57
#define FRONTIER_MON_LAPRAS                     58
#define FRONTIER_MON_DITTO                      59
#define FRONTIER_MON_VAPOREON                   60
#define FRONTIER_MON_JOLTEON                    61
#define FRONTIER_MON_FLAREON                    62
#define FRONTIER_MON_OMASTAR                    63
#define FRONTIER_MON_KABUTOPS                   64
#define FRONTIER_MON_AERODACTYL                 65
#define FRONTIER_MON_FURRET                     66
#define FRONTIER_MON_NOCTOWL                    67
#define FRONTIER_MON_NOCTOWL_EMERIBIAN          68
#define FRONTIER_MON_LEDIAN                     69
#define FRONTIER_MON_ARIADOS_EMERIBIAN          70
#define FRONTIER_MON_CROBAT                     71
#define FRONTIER_MON_LANTURN                    72
#define FRONTIER_MON_XATU                       73
#define FRONTIER_MON_AMPHAROS                   74
#define FRONTIER_MON_BELLOSSOM                  75
#define FRONTIER_MON_BELLOSSOM_EMERIBIAN        76
#define FRONTIER_MON_SUDOWOODO                  77
#define FRONTIER_MON_JUMPLUFF                   78
#define FRONTIER_MON_JUMPLUFF_EMERIBIAN         79
#define FRONTIER_MON_ESPEON                     80
#define FRONTIER_MON_WOBBUFFET                  81
#define FRONTIER_MON_FORRETRESS                 82
#define FRONTIER_MON_STEELIX                    83
#define FRONTIER_MON_GRANBULL                   84
#define FRONTIER_MON_HERACROSS                  85
#define FRONTIER_MON_MAGCARGO                   86
#define FRONTIER_MON_MAGCARGO_EMERIBIAN         87
#define FRONTIER_MON_CORSOLA                    88
#define FRONTIER_MON_OCTILLERY                  89
#define FRONTIER_MON_OCTILLERY_FRIBIAN          90
#define FRONTIER_MON_MANTINE                    91
#define FRONTIER_MON_HOUNDOOM                   92
#define FRONTIER_MON_KINGDRA                    93
#define FRONTIER_MON_SMEARGLE                   94
#define FRONTIER_MON_HITMONTOP                  95
#define FRONTIER_MON_MILTANK                    96
#define FRONTIER_MON_MIGHTYENA                  97
#define FRONTIER_MON_MIGHTYENA_EMERIBIAN        98
#define FRONTIER_MON_BEAUTIFLY                  99
#define FRONTIER_MON_DUSTOX                     100
#define FRONTIER_MON_LUDICOLO                   101
#define FRONTIER_MON_SHIFTRY                    102
#define FRONTIER_MON_SWELLOW                    103
#define FRONTIER_MON_GARDEVOIR                  104
#define FRONTIER_MON_GARDEVOIR_EMERIBIAN        105
#define FRONTIER_MON_MASQUERAIN                 106
#define FRONTIER_MON_SLAKING                    107
#define FRONTIER_MON_NINJASK                    108
#define FRONTIER_MON_SHEDINJA                   109
#define FRONTIER_MON_EXPLOUD                    110
#define FRONTIER_MON_HARIYAMA                   111
#define FRONTIER_MON_DELCATTY                   112
#define FRONTIER_MON_SABLEYE                    113
#define FRONTIER_MON_MAWILE                     114
#define FRONTIER_MON_AGGRON                     115
#define FRONTIER_MON_MEDICHAM                   116
#define FRONTIER_MON_MANECTRIC                  117
#define FRONTIER_MON_PLUSLE                     118
#define FRONTIER_MON_MINUN                      119
#define FRONTIER_MON_VOLBEAT                    120
#define FRONTIER_MON_ILLUMISE                   121
#define FRONTIER_MON_SWALOT                     122
#define FRONTIER_MON_SHARPEDO                   123
#define FRONTIER_MON_WAILORD                    124
#define FRONTIER_MON_CAMERUPT                   125
#define FRONTIER_MON_GRUMPIG                    126
#define FRONTIER_MON_SPINDA                     127
#define FRONTIER_MON_CACTURNE                   128
#define FRONTIER_MON_ALTARIA                    129
#define FRONTIER_MON_ZANGOOSE                   130
#define FRONTIER_MON_SEVIPER                    131
#define FRONTIER_MON_LUNATONE                   132
#define FRONTIER_MON_SOLROCK                    133
#define FRONTIER_MON_WHISCASH                   134
#define FRONTIER_MON_CLAYDOL                    135
#define FRONTIER_MON_CRADILY                    136
#define FRONTIER_MON_ARMALDO                    137
#define FRONTIER_MON_CASTFORM                   138
#define FRONTIER_MON_KECLEON                    139
#define FRONTIER_MON_BANETTE                    140
#define FRONTIER_MON_TROPIUS                    141
#define FRONTIER_MON_CHIMECHO                   142
#define FRONTIER_MON_ABSOL                      143
#define FRONTIER_MON_GLALIE                     144
#define FRONTIER_MON_WALREIN                    145
#define FRONTIER_MON_HUNTAIL                    146
#define FRONTIER_MON_GOREBYSS                   147
#define FRONTIER_MON_RELICANTH                  148
#define FRONTIER_MON_LUVDISC                    149
#define FRONTIER_MON_KRICKETUNE                 150
#define FRONTIER_MON_LUXRAY                     151
#define FRONTIER_MON_LUXRAY_EMERIBIAN           152
#define FRONTIER_MON_RAMPARDOS                  153
#define FRONTIER_MON_BASTIODON                  154
#define FRONTIER_MON_WORMADAM                   155
#define FRONTIER_MON_MOTHIM                     156
#define FRONTIER_MON_VESPIQUEN                  157
#define FRONTIER_MON_PACHIRISU                  158
#define FRONTIER_MON_FLOATZEL                   159
#define FRONTIER_MON_CHERRIM                    160
#define FRONTIER_MON_AMBIPOM                    161
#define FRONTIER_MON_DRIFBLIM                   162
#define FRONTIER_MON_DRIFBLIM_EMERIBIAN         163
#define FRONTIER_MON_LOPUNNY                    164
#define FRONTIER_MON_MISMAGIUS                  165
#define FRONTIER_MON_HONCHKROW                  166
#define FRONTIER_MON_PURUGLY                    167
#define FRONTIER_MON_SKUNTANK                   168
#define FRONTIER_MON_BRONZONG                   169
#define FRONTIER_MON_CHATOT                     170
#define FRONTIER_MON_SPIRITOMB                  171
#define FRONTIER_MON_DRAPION                    172
#define FRONTIER_MON_TOXICROAK                  173
#define FRONTIER_MON_CARNIVINE                  174
#define FRONTIER_MON_LUMINEON                   175
#define FRONTIER_MON_LICKILICKY                 176
#define FRONTIER_MON_ELECTIVIRE                 177
#define FRONTIER_MON_MAGMORTAR                  178
#define FRONTIER_MON_YANMEGA                    179
#define FRONTIER_MON_LEAFEON                    180
#define FRONTIER_MON_GLACEON                    181
#define FRONTIER_MON_PORYGON_Z                  182
#define FRONTIER_MON_PROBOPASS                  183
#define FRONTIER_MON_DUSKNOIR                   184
#define FRONTIER_MON_ROTOM                      185
#define FRONTIER_MON_PHIONE                     186
#define FRONTIER_MON_WATCHOG                    187
#define FRONTIER_MON_STOUTLAND                  188
#define FRONTIER_MON_LIEPARD                    189
#define FRONTIER_MON_SIMISAGE                   190
#define FRONTIER_MON_SIMISEAR                   191
#define FRONTIER_MON_SIMIPOUR                   192
#define FRONTIER_MON_MUSHARNA                   193
#define FRONTIER_MON_UNFEZANT                   194
#define FRONTIER_MON_ZEBSTRIKA                  195
#define FRONTIER_MON_GIGALITH                   196
#define FRONTIER_MON_GIGALITH_FRIBIAN           197
#define FRONTIER_MON_SWOOBAT                    198
#define FRONTIER_MON_AUDINO                     199
#define FRONTIER_MON_THROH                      200
#define FRONTIER_MON_SAWK                       201
#define FRONTIER_MON_LEAVANNY                   202
#define FRONTIER_MON_MARACTUS                   203
#define FRONTIER_MON_CRUSTLE                    204
#define FRONTIER_MON_SCRAFTY                    205
#define FRONTIER_MON_SIGILYPH                   206
#define FRONTIER_MON_COFAGRIGUS                 207
#define FRONTIER_MON_CARRACOSTA                 208
#define FRONTIER_MON_ARCHEOPS                   209
#define FRONTIER_MON_GARBODOR                   210
#define FRONTIER_MON_ZOROARK                    211
#define FRONTIER_MON_CINCCINO                   212
#define FRONTIER_MON_SWANNA                     213
#define FRONTIER_MON_SAWSBUCK                   214
#define FRONTIER_MON_EMOLGA                     215
#define FRONTIER_MON_ESCAVALIER                 216
#define FRONTIER_MON_KLINKLANG                  217
#define FRONTIER_MON_EELEKTROSS                 218
#define FRONTIER_MON_BEHEEYEM                   219
#define FRONTIER_MON_BEARTIC                    220
#define FRONTIER_MON_CRYOGONAL                  221
#define FRONTIER_MON_ACCELGOR                   222
#define FRONTIER_MON_STUNFISK                   223
#define FRONTIER_MON_STUNFISK_GALARIAN          224
#define FRONTIER_MON_DRUDDIGON                  225
#define FRONTIER_MON_GOLURK                     226
#define FRONTIER_MON_BOUFFALANT                 227
#define FRONTIER_MON_BRAVIARY                   228
#define FRONTIER_MON_HEATMOR                    229
#define FRONTIER_MON_VIVILLON                   230
#define FRONTIER_MON_PYROAR                     231
#define FRONTIER_MON_GOGOAT                     232
#define FRONTIER_MON_GOGOAT_EMERIBIAN           233
#define FRONTIER_MON_PANGORO                    234
#define FRONTIER_MON_FURFROU                    235
#define FRONTIER_MON_MEOWSTIC                   236
#define FRONTIER_MON_MEOWSTIC_FEMALE            237
#define FRONTIER_MON_AROMATISSE                 238
#define FRONTIER_MON_SLURPUFF                   239
#define FRONTIER_MON_MALAMAR                    240
#define FRONTIER_MON_CLAWITZER                  241
#define FRONTIER_MON_TYRANTRUM                  242
#define FRONTIER_MON_AURORUS                    243
#define FRONTIER_MON_DEDENNE                    244
#define FRONTIER_MON_CARBINK                    245
#define FRONTIER_MON_GOODRA                     246
#define FRONTIER_MON_TREVENANT                  247
#define FRONTIER_MON_TREVENANT_EMERIBIAN        248
#define FRONTIER_MON_GOURGEIST                  249
#define FRONTIER_MON_AVALUGG                    250
#define FRONTIER_MON_AVALUGG_HISUIAN            251
#define FRONTIER_MON_TOUCANNON                  252
#define FRONTIER_MON_GUMSHOOS                   253
#define FRONTIER_MON_VIKAVOLT                   254
#define FRONTIER_MON_CRABOMINABLE               255
#define FRONTIER_MON_ORICORIO                   256
#define FRONTIER_MON_LYCANROC                   257
#define FRONTIER_MON_LYCANROC_MIDNIGHT          258
#define FRONTIER_MON_LYCANROC_DUSK              259
#define FRONTIER_MON_WISHIWASHI                 260
#define FRONTIER_MON_MUDSDALE                   261
#define FRONTIER_MON_ARAQUANID                  262
#define FRONTIER_MON_LURANTIS                   263
#define FRONTIER_MON_SHIINOTIC                  264
#define FRONTIER_MON_BEWEAR                     265
#define FRONTIER_MON_COMFEY                     266
#define FRONTIER_MON_ORANGURU                   267
#define FRONTIER_MON_PASSIMIAN                  268
#define FRONTIER_MON_PALOSSAND                  269
#define FRONTIER_MON_PYUKUMUKU                  270
#define FRONTIER_MON_SILVALLY                   271
#define FRONTIER_MON_MINIOR                     272
#define FRONTIER_MON_KOMALA                     273
#define FRONTIER_MON_TURTONATOR                 274
#define FRONTIER_MON_TOGEDEMARU                 275
#define FRONTIER_MON_MIMIKYU_EMERIBIAN          276
#define FRONTIER_MON_BRUXISH                    277
#define FRONTIER_MON_DRAMPA                     278
#define FRONTIER_MON_GUZZLORD                   279
#define FRONTIER_MON_STAKATAKA                  280
#define FRONTIER_MON_GREEDENT                   281
#define FRONTIER_MON_ORBEETLE                   282
#define FRONTIER_MON_THIEVUL                    283
#define FRONTIER_MON_ELDEGOSS                   284
#define FRONTIER_MON_DUBWOOL                    285
#define FRONTIER_MON_DUBWOOL_FRIBIAN            286
#define FRONTIER_MON_DREDNAW                    287
#define FRONTIER_MON_BOLTUND                    288
#define FRONTIER_MON_COALOSSAL                  289
#define FRONTIER_MON_FLAPPLE                    290
#define FRONTIER_MON_APPLETUN                   291
#define FRONTIER_MON_SANDACONDA                 292
#define FRONTIER_MON_CRAMORANT                  293
#define FRONTIER_MON_CENTISKORCH                294
#define FRONTIER_MON_GRAPPLOCT                  295
#define FRONTIER_MON_PERRSERKER                 296
#define FRONTIER_MON_CURSOLA                    297
#define FRONTIER_MON_SIRFETCHD                  298
#define FRONTIER_MON_MR_RIME                    299
#define FRONTIER_MON_RUNERIGUS                  300
#define FRONTIER_MON_ALCREMIE                   301
#define FRONTIER_MON_FALINKS                    302
#define FRONTIER_MON_FALINKS_EMERIBIAN          303
#define FRONTIER_MON_PINCURCHIN                 304
#define FRONTIER_MON_FROSMOTH                   305
#define FRONTIER_MON_STONJOURNER                306
#define FRONTIER_MON_EISCUE                     307
#define FRONTIER_MON_MORPEKO                    308
#define FRONTIER_MON_COPPERAJAH                 309
#define FRONTIER_MON_ARCTOVISH                  310
#define FRONTIER_MON_WYRDEER                    311
#define FRONTIER_MON_OINKOLOGNE                 312
#define FRONTIER_MON_SPIDOPS                    313
#define FRONTIER_MON_DACHSBUN                   314
#define FRONTIER_MON_ARBOLIVA                   315
#define FRONTIER_MON_SQUAWKABILLY               316
#define FRONTIER_MON_BELLIBOLT                  317
#define FRONTIER_MON_MABOSSTIFF                 318
#define FRONTIER_MON_GRAFAIAI                   319
#define FRONTIER_MON_BRAMBLEGHAST               320
#define FRONTIER_MON_KLAWF                      321
#define FRONTIER_MON_SCOVILLAIN                 322
#define FRONTIER_MON_RABSCA                     323
#define FRONTIER_MON_WUGTRIO                    324
#define FRONTIER_MON_BOMBIRDIER                 325
#define FRONTIER_MON_REVAVROOM                  326
#define FRONTIER_MON_ORTHWORM                   327
#define FRONTIER_MON_HOUNDSTONE                 328
#define FRONTIER_MON_FLAMIGO                    329
#define FRONTIER_MON_CETITAN                    330
#define FRONTIER_MON_VELUZA                     331
#define FRONTIER_MON_TATSUGIRI                  332
#define FRONTIER_MON_FARIGIRAF                  333
#define FRONTIER_MON_DUDUNSPARCE                334
#define FRONTIER_MON_EVALEON                    335
#define FRONTIER_MON_AEREON                     336
#define FRONTIER_MON_CONTAGEON                  337
#define FRONTIER_MON_LANEON                     338
#define FRONTIER_MON_TITANEON                   339
#define FRONTIER_MON_MUDCARGO                   340
#define FRONTIER_MON_APIMARILL                  341
#define FRONTIER_MON_SOLFLORA                   342
#define FRONTIER_MON_SHIBIREFUGU                343
#define FRONTIER_MON_COGMENT                    344

#define FRONTIER_MON_VENUSAUR                   345
#define FRONTIER_MON_CHARIZARD                  346
#define FRONTIER_MON_CHARIZARD_EMERIBIAN        347
#define FRONTIER_MON_BLASTOISE                  348
#define FRONTIER_MON_CLEFABLE                   349
#define FRONTIER_MON_NINETALES_ALOLAN           350
#define FRONTIER_MON_ARCANINE_HISUIAN           351
#define FRONTIER_MON_ALAKAZAM                   352
#define FRONTIER_MON_TENTACRUEL                 353
#define FRONTIER_MON_SLOWBRO                    354
#define FRONTIER_MON_CLOYSTER                   355
#define FRONTIER_MON_CLOYSTER_FRIBIAN           356
#define FRONTIER_MON_GENGAR                     357
#define FRONTIER_MON_ELECTRODE_HISUIAN          358
#define FRONTIER_MON_WEEZING_GALARIAN           359
#define FRONTIER_MON_STARMIE                    360
#define FRONTIER_MON_TAUROS_PALDEAN_AQUA_BREED  361
#define FRONTIER_MON_TAUROS_PALDEAN_BLAZE_BREED 362
#define FRONTIER_MON_GYARADOS                   363
#define FRONTIER_MON_SNORLAX                    364
#define FRONTIER_MON_ARTICUNO                   365
#define FRONTIER_MON_ARTICUNO_GALARIAN          366
#define FRONTIER_MON_ZAPDOS                     367
#define FRONTIER_MON_ZAPDOS_GALARIAN            368
#define FRONTIER_MON_MOLTRES                    369
#define FRONTIER_MON_MOLTRES_GALARIAN           370
#define FRONTIER_MON_DRAGONITE                  371
#define FRONTIER_MON_MEGANIUM                   372
#define FRONTIER_MON_MEGANIUM_EMERIBIAN         373
#define FRONTIER_MON_TYPHLOSION                 374
#define FRONTIER_MON_TYPHLOSION_HISUIAN         375
#define FRONTIER_MON_TYPHLOSION_EMERIBIAN       376
#define FRONTIER_MON_FERALIGATR                 377
#define FRONTIER_MON_FERALIGATR_EMERIBIAN       378
#define FRONTIER_MON_ARIADOS                    379
#define FRONTIER_MON_AZUMARILL                  380
#define FRONTIER_MON_POLITOED                   381
#define FRONTIER_MON_QUAGSIRE                   382
#define FRONTIER_MON_UMBREON                    383
#define FRONTIER_MON_SLOWKING                   384
#define FRONTIER_MON_SLOWKING_GALARIAN          385
#define FRONTIER_MON_SCIZOR                     386
#define FRONTIER_MON_SHUCKLE                    387
#define FRONTIER_MON_SHUCKLE_FRIBIAN            388
#define FRONTIER_MON_SKARMORY                   389
#define FRONTIER_MON_SKARMORY_FRIBIAN           390
#define FRONTIER_MON_DONPHAN                    391
#define FRONTIER_MON_BLISSEY                    392
#define FRONTIER_MON_RAIKOU                     393
#define FRONTIER_MON_ENTEI                      394
#define FRONTIER_MON_SUICUNE                    395
#define FRONTIER_MON_TYRANITAR                  396
#define FRONTIER_MON_SCEPTILE                   397
#define FRONTIER_MON_BLAZIKEN                   398
#define FRONTIER_MON_SWAMPERT                   399
#define FRONTIER_MON_LINOONE                    400
#define FRONTIER_MON_PELIPPER                   401
#define FRONTIER_MON_BRELOOM                    402
#define FRONTIER_MON_BRELOOM_FRIBIAN            403
#define FRONTIER_MON_TORKOAL                    404
#define FRONTIER_MON_FLYGON                     405
#define FRONTIER_MON_CRAWDAUNT                  406
#define FRONTIER_MON_MILOTIC                    407
#define FRONTIER_MON_SALAMENCE                  408
#define FRONTIER_MON_METAGROSS                  409
#define FRONTIER_MON_REGIROCK                   410
#define FRONTIER_MON_REGICE                     411
#define FRONTIER_MON_REGISTEEL                  412
#define FRONTIER_MON_LATIAS                     413
#define FRONTIER_MON_LATIOS                     414
#define FRONTIER_MON_TORTERRA                   415
#define FRONTIER_MON_INFERNAPE                  416
#define FRONTIER_MON_EMPOLEON                   417
#define FRONTIER_MON_STARAPTOR                  418
#define FRONTIER_MON_BIBAREL                    419
#define FRONTIER_MON_ROSERADE                   420
#define FRONTIER_MON_GASTRODON                  421
#define FRONTIER_MON_LOPUNNY_EMERIBIAN          422
#define FRONTIER_MON_GARCHOMP                   423
#define FRONTIER_MON_LUCARIO                    424
#define FRONTIER_MON_HIPPOWDON                  425
#define FRONTIER_MON_ABOMASNOW                  426
#define FRONTIER_MON_WEAVILE                    427
#define FRONTIER_MON_MAGNEZONE                  428
#define FRONTIER_MON_RHYPERIOR                  429
#define FRONTIER_MON_TANGROWTH                  430
#define FRONTIER_MON_TOGEKISS                   431
#define FRONTIER_MON_GLISCOR                    432
#define FRONTIER_MON_MAMOSWINE                  433
#define FRONTIER_MON_GALLADE                    434
#define FRONTIER_MON_FROSLASS                   435
#define FRONTIER_MON_UXIE                       436
#define FRONTIER_MON_MESPRIT                    437
#define FRONTIER_MON_AZELF                      438
#define FRONTIER_MON_HEATRAN                    439
#define FRONTIER_MON_CRESSELIA                  440
#define FRONTIER_MON_SERPERIOR                  441
#define FRONTIER_MON_EMBOAR                     442
#define FRONTIER_MON_SAMUROTT                   443
#define FRONTIER_MON_SAMUROTT_HISUIAN           444
#define FRONTIER_MON_EXCADRILL                  445
#define FRONTIER_MON_CONKELDURR                 446
#define FRONTIER_MON_SEISMITOAD                 447
#define FRONTIER_MON_SCOLIPEDE                  448
#define FRONTIER_MON_WHIMSICOTT                 449
#define FRONTIER_MON_LILLIGANT                  450
#define FRONTIER_MON_LILLIGANT_HISUIAN          451
#define FRONTIER_MON_KROOKODILE                 452
#define FRONTIER_MON_DARMANITAN                 453
#define FRONTIER_MON_DARMANITAN_GALARIAN        454
#define FRONTIER_MON_ZOROARK_HISUIAN            455
#define FRONTIER_MON_GOTHITELLE                 456
#define FRONTIER_MON_REUNICLUS                  457
#define FRONTIER_MON_VANILLUXE                  458
#define FRONTIER_MON_AMOONGUSS                  459
#define FRONTIER_MON_JELLICENT                  460
#define FRONTIER_MON_ALOMOMOLA                  461
#define FRONTIER_MON_GALVANTULA                 462
#define FRONTIER_MON_FERROTHORN                 463
#define FRONTIER_MON_CHANDELURE                 464
#define FRONTIER_MON_HAXORUS                    465
#define FRONTIER_MON_MIENSHAO                   466
#define FRONTIER_MON_BRAVIARY_HISUIAN           467
#define FRONTIER_MON_MANDIBUZZ                  468
#define FRONTIER_MON_DURANT                     469
#define FRONTIER_MON_HYDREIGON                  470
#define FRONTIER_MON_VOLCARONA                  471
#define FRONTIER_MON_COBALION                   472
#define FRONTIER_MON_TERRAKION                  473
#define FRONTIER_MON_VIRIZION                   474
#define FRONTIER_MON_TORNADUS                   475
#define FRONTIER_MON_TORNADUS_THERIAN           476
#define FRONTIER_MON_THUNDURUS                  477
#define FRONTIER_MON_THUNDURUS_THERIAN          478
#define FRONTIER_MON_KELDEO                     479
#define FRONTIER_MON_CHESNAUGHT                 480
#define FRONTIER_MON_DELPHOX                    481
#define FRONTIER_MON_GRENINJA                   482
#define FRONTIER_MON_GRENINJA_2                 483
#define FRONTIER_MON_DIGGERSBY                  484
#define FRONTIER_MON_TALONFLAME                 485
#define FRONTIER_MON_FLORGES                    486
#define FRONTIER_MON_AEGISLASH                  487
#define FRONTIER_MON_AEGISLASH_EMERIBIAN        488
#define FRONTIER_MON_BARBARACLE                 489
#define FRONTIER_MON_DRAGALGE                   490
#define FRONTIER_MON_DRAGALGE_EMERIBIAN         491
#define FRONTIER_MON_HELIOLISK                  492
#define FRONTIER_MON_SYLVEON                    493
#define FRONTIER_MON_HAWLUCHA                   494
#define FRONTIER_MON_GOODRA_HISUIAN             495
#define FRONTIER_MON_KLEFKI                     496
#define FRONTIER_MON_NOIVERN                    497
#define FRONTIER_MON_DECIDUEYE                  498
#define FRONTIER_MON_DECIDUEYE_HISUIAN          499
#define FRONTIER_MON_INCINEROAR                 500
#define FRONTIER_MON_PRIMARINA                  501
#define FRONTIER_MON_RIBOMBEE                   502
#define FRONTIER_MON_TOXAPEX                    503
#define FRONTIER_MON_SALAZZLE                   504
#define FRONTIER_MON_TSAREENA                   505
#define FRONTIER_MON_GOLISOPOD                  506
#define FRONTIER_MON_MIMIKYU                    507
#define FRONTIER_MON_DHELMISE                   508
#define FRONTIER_MON_KOMMO_O                    509
#define FRONTIER_MON_TAPU_KOKO                  510
#define FRONTIER_MON_TAPU_LELE                  511
#define FRONTIER_MON_TAPU_BULU                  512
#define FRONTIER_MON_TAPU_FINI                  513
#define FRONTIER_MON_NIHILEGO                   514
#define FRONTIER_MON_BUZZWOLE                   515
#define FRONTIER_MON_PHEROMOSA                  516
#define FRONTIER_MON_XURKITREE                  517
#define FRONTIER_MON_CELESTEELA                 518
#define FRONTIER_MON_KARTANA                    519
#define FRONTIER_MON_NAGANADEL                  520
#define FRONTIER_MON_BLACEPHALON                521
#define FRONTIER_MON_RILLABOOM                  522
#define FRONTIER_MON_CINDERACE                  523
#define FRONTIER_MON_INTELEON                   524
#define FRONTIER_MON_CORVIKNIGHT                525
#define FRONTIER_MON_BARRASKEWDA                526
#define FRONTIER_MON_TOXTRICITY                 527
#define FRONTIER_MON_POLTEAGEIST                528
#define FRONTIER_MON_HATTERENE                  529
#define FRONTIER_MON_GRIMMSNARL                 530
#define FRONTIER_MON_OBSTAGOON                  531
#define FRONTIER_MON_INDEEDEE                   532
#define FRONTIER_MON_DRACOZOLT                  533
#define FRONTIER_MON_ARCTOZOLT                  534
#define FRONTIER_MON_DRACOVISH                  535
#define FRONTIER_MON_DRAGAPULT                  536
#define FRONTIER_MON_URSHIFU_RAPID_STRIKE_STYLE 537
#define FRONTIER_MON_URSHIFU                    538
#define FRONTIER_MON_REGIELEKI                  539
#define FRONTIER_MON_REGIDRAGO                  540
#define FRONTIER_MON_GLASTRIER                  541
#define FRONTIER_MON_SPECTRIER                  542
#define FRONTIER_MON_CALYREX                    543
#define FRONTIER_MON_KLEAVOR                    544
#define FRONTIER_MON_URSALUNA                   545
#define FRONTIER_MON_URSALUNA_BLOODMOON         546
#define FRONTIER_MON_BASCULEGION                547
#define FRONTIER_MON_SNEASLER                   548
#define FRONTIER_MON_OVERQWIL                   549
#define FRONTIER_MON_ENAMORUS                   550
#define FRONTIER_MON_ENAMORUS_THERIAN           551
#define FRONTIER_MON_MEOWSCARADA                552
#define FRONTIER_MON_SKELEDIRGE                 553
#define FRONTIER_MON_QUAQUAVAL                  554
#define FRONTIER_MON_LOKIX                      555
#define FRONTIER_MON_PAWMOT                     556
#define FRONTIER_MON_MAUSHOLD                   557
#define FRONTIER_MON_GARGANACL                  558
#define FRONTIER_MON_ARMAROUGE                  559
#define FRONTIER_MON_CERULEDGE                  560
#define FRONTIER_MON_KILOWATTREL                561
#define FRONTIER_MON_TOEDSCRUEL                 562
#define FRONTIER_MON_ESPATHRA                   563
#define FRONTIER_MON_TINKATON                   564
#define FRONTIER_MON_PALAFIN                    565
#define FRONTIER_MON_CYCLIZAR                   566
#define FRONTIER_MON_GLIMMORA                   567
#define FRONTIER_MON_DONDOZO                    568
#define FRONTIER_MON_ANNIHILAPE                 569
#define FRONTIER_MON_CLODSIRE                   570
#define FRONTIER_MON_KINGAMBIT                  571
#define FRONTIER_MON_GREAT_TUSK                 572
#define FRONTIER_MON_SCREAM_TAIL                573
#define FRONTIER_MON_BRUTE_BONNET               574
#define FRONTIER_MON_FLUTTER_MANE               575
#define FRONTIER_MON_SLITHER_WING               576
#define FRONTIER_MON_SANDY_SHOCKS               577
#define FRONTIER_MON_IRON_TREADS                578
#define FRONTIER_MON_IRON_BUNDLE                579
#define FRONTIER_MON_IRON_HANDS                 580
#define FRONTIER_MON_IRON_JUGULIS               581
#define FRONTIER_MON_IRON_MOTH                  582
#define FRONTIER_MON_IRON_THORNS                583
#define FRONTIER_MON_BAXCALIBUR                 584
#define FRONTIER_MON_GHOLDENGO                  585
#define FRONTIER_MON_WO_CHIEN                   586
#define FRONTIER_MON_CHIEN_PAO                  587
#define FRONTIER_MON_TING_LU                    588
#define FRONTIER_MON_CHI_YU                     589
#define FRONTIER_MON_ROARING_MOON               590
#define FRONTIER_MON_IRON_VALIANT               591
#define FRONTIER_MON_WALKING_WAKE               592
#define FRONTIER_MON_IRON_LEAVES                593
#define FRONTIER_MON_SINISTCHA                  594
#define FRONTIER_MON_OKIDOGI                    595
#define FRONTIER_MON_MUNKIDORI                  596
#define FRONTIER_MON_FEZANDIPITI                597
#define FRONTIER_MON_OGERPON                    598
#define FRONTIER_MON_ARCHALUDON                 599
#define FRONTIER_MON_HYDRAPPLE                  600
#define FRONTIER_MON_GOUGING_FIRE               601
#define FRONTIER_MON_RAGING_BOLT                602
#define FRONTIER_MON_IRON_BOULDER               603
#define FRONTIER_MON_IRON_CROWN                 604
#define FRONTIER_MON_SCALEON                    605
#define FRONTIER_MON_RAITORA                    606
#define FRONTIER_MON_MADAME                     607
#define FRONTIER_MON_DELIJOY                    608

#define FRONTIER_MONS_HIGH_TIER     344 // Mons above this point can only appear > level 50

#define NUM_FRONTIER_MONS           609

#endif //GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
