// Add new IDs here
enum {
    HELP_EXPANSION_1_BOAT_EXPLANATION,
    HELP_EXPANSION_1_NPC_FOLLOWERS,
    HELP_EXPANSION_1_NPC_FOLLOWERS_2,
    HELP_BATTLE_CONTROLS,
    HELP_POKEDEX,
    HELP_SHOP_INVENTORY,
    HELP_FLYING,
    HELP_TERASTALLIZATION,
    HELP_MEGA_EVOLUTION,
    HELP_COUNT
};
