MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"

MoveTutor_Text_WhichMoveToTeach:
	.string "Which move would you like me to teach?$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh! My Pokémon totally rules!\n"
	.string "It's cooler than any Pokémon!\p"
	.string "I was lipping off with a swagger in\n"
	.string "my step like that when the Chairman\l"
	.string "chewed me out.\p"
	.string "That took the swagger out of my step.\p"
	.string "If you'd like, I'll teach the move\n"
	.string "Swagger to a Pokémon of yours.$"

MoveTutor_Text_SwaggerDeclined:
	.string "What, no? Can't you get into\n"
	.string "the spirit of things?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "All right, which Pokémon wants to\n"
	.string "learn how to Swagger?$"

MoveTutor_Text_SwaggerTaught:
	.string "I'll just praise my Pokémon from now\n"
	.string "on without the swagger.$"

MoveTutor_Text_TricksTeach:
	.string "Wattson's gym is full of tricks and\n"
	.string "traps, but I've got a solution.\p"
	.string "You just need to be Tricky yourself!\p"
	.string "Would you like me to teach your\n"
	.string "Pokémon a Tricky move?$"

MoveTutor_Text_TricksDeclined:
	.string "You'll be back when you can't counter\n"
	.string "his tricks…$"

MoveTutor_Text_TricksWhichMon:
	.string "Ehehe, sure thing!\n"
	.string "Let's get Tricky!$"

MoveTutor_Text_TricksTaught:
	.string "Get in there and teach Wattson what\n"
	.string "for!$"

MoveTutor_Text_IcyWindTeach:
	.string "The air in this town is nice, but\n"
	.string "sometimes I still feel a cold chill.\p"
	.string "That's because my Pokémon use Icy Wind\n"
	.string "on me!\p"
	.string "Want me to teach it to a Pokémon?$"

MoveTutor_Text_IcyWindDeclined:
	.string "We're not on the same wavelength.$"

MoveTutor_Text_IcyWindWhichMon:
	.string "Yay!\n"
	.string "Show me which Pokémon I should teach.$"

MoveTutor_Text_IcyWindTaught:
	.string "I get a thrill when I feel that chill!$"

MoveTutor_SleepTalkTeach:
	.string "The old people in this town fall asleep\n"
	.string "in the sands all the time, and they\l"
	.string "always talk in their sleep like Pokémon!\p"
	.string "Want me to teach one of your Pokémon\n"
	.string "to Sleep Talk like they do?$"

MoveTutor_SleepTalkDeclined:
	.string "Well, if I wanted to hear Sleep Talk, I\n"
	.string "wouldn't need your Pokémon anyway!$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Let me see the Pokémon\l"
	.string "you want me to teach.$"

MoveTutor_Text_SleepTalkTaught:
	.string "Haha!\p"
	.string "Your Pokémon sounds just like the old\n"
	.string "people!$"

MoveTutor_Text_SignalBeamTeach:
	.string "I want all sorts of things!\n"
	.string "But I used up my allowance…\p"
	.string "Wouldn't it be nice if I could fire\n"
	.string "a ray out and confuse the shop keeper\l"
	.string "while I sneak off?\p"
	.string "If you want, I can teach your Pokémon\n"
	.string "the move Signal Beam.$"

MoveTutor_Text_SignalBeamDeclined:
	.string "Okay. I'll be here if you change\n"
	.string "your mind.$"

MoveTutor_Text_SignalBeamWhichMon:
	.string "Okay! I'll teach it!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_SignalBeamTaught:
	.string "When a Pokémon uses Signal Beam\n"
	.string "there's a good chance it can\l"
	.string "confuse its opponent\p"
	.string "Wouldn't it be nice if we could\n"
	.string "use it, too?$"

MoveTutor_Text_BodySlamTeach:
	.string "Humph! My wife relies on shopping\n"
	.string "catalogs to stay awake.\p"
	.string "I think she should just let me\n"
	.string "Body Slam her!\p"
	.string "I can teach your Pokémon how to\n"
	.string "Body Slam instead. Interested?$"

MoveTutor_Text_BodySlamDeclined:
	.string "Oh, fine, fine. You want to stay awake\n"
	.string "with her catalogs, too…$"

MoveTutor_Text_BodySlamWhichMon:
	.string "Ah, an appreciative child!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_BodySlamTaught:
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.\p"
	.string "I would be happy if I got it right,\n"
	.string "even if she won't let me Body Slam…$"

MoveTutor_Text_HyperVoiceTeach:
	.string "When I see the wide world from up\n"
	.string "here on the roof…\p"
	.string "It makes me want to shout as loud as\n"
	.string "possible, so I can hear the echo!\p"
	.string "Giggle…\p"
	.string "I know! Would you be interested in\n"
	.string "having a Pokémon learn Hyper Voice?$"

MoveTutor_Text_HyperVoiceDeclined:
	.string "Oh, no?\p"
	.string "I can really teach your Pokémon\n"
	.string "to scream, you know.$"

MoveTutor_Text_HyperVoiceWhichMon:
	.string "Which Pokémon do you want me to\n"
	.string "teach Hyper Voice?$"

MoveTutor_Text_HyperVoiceTaught:
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"

MoveTutor_Text_CombatMoveTeach:
	.string "I can't believe it!\p"
	.string "I fell in the water and washed up here!\p"
	.string "It just makes me want to hit something!\p"
	.string "Let me teach your Pokémon a move\n"
	.string "so they can hit things too!$"

MoveTutor_Text_CombatMoveDeclined:
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_CombatMoveWhichMon:
	.string "You're a good person!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_CombatMoveTaught:
	.string "I want you to win using the moves\n"
	.string "I've taught your Pokémon!$"

MoveTutor_Text_PledgeMoveTeach:
	.string "This is the city where I proposed to\n"
	.string "my wife long ago.\p"
	.string "Every year I return to honor that\n"
	.string "pledge.\p"
	.string "Would you like me to teach your Pokémon\n"
	.string "a Pledge move to use in combination\l"
	.string "with their battle partner?$"

MoveTutor_Text_PledgeMoveDeclined:
	.string "Ah, well return if you feel so.\n"
	.string "I will remain here for a while.$"

MoveTutor_Text_PledgeMoveWhichMon:
	.string "In her memory, which Pokémon\n"
	.string "will I be teaching?$"

MoveTutor_Text_PledgeMoveTaught:
	.string "I hope that with this move, you'll\n"
	.string "always remember your partners.$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Sigh…\p"
	.string "Sootopolis's Gym Leader is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "The only way I could compete is to\n"
	.string "strike them with a Dynamic Punch!\p"
	.string "Please, let me teach your Pokémon\n"
	.string "the move Dynamic Punch!$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Oh…\n"
	.string "Even you rejected me…$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Okay, which Pokémon should I teach\n"
	.string "Dynamic Punch?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"

MoveTutor_Text_ExplosionTeach:
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge Explosion of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach Explosion to your Pokémon!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! You're turning me down because\n"
	.string "I live in the country?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fine! An Explosion it is!\n"
	.string "Which Pokémon wants to blow up?$"

MoveTutor_Text_ExplosionTaught:
	.string "For a long time, I've taught Pokémon\n"
	.string "how to use Explosion, but I've yet\l"
	.string "to ignite my own Explosion…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"
