Call1_JaksonText::
# 2 "data/expansion_1/rival_text.pory"
	.string "Jakson: Yo, {PLAYER}!\n"
	.string "I'm glad I caught you!\p"
	.string "If I didn't see you online, I was\n"
	.string "going to message you on ENCORE.\p"
	.string "I can't believe you're all still\n"
	.string "playing enough to contact you\l"
	.string "in-game…\p"
	.string "A- Anyway, to the point.\p"
	.string "It was… a bit of a rush job… but…\n"
	.string "I was able to put together a nice\l"
	.string "surprise for the whole group.\p"
	.string "Drop by Slateport City when you're\n"
	.string "next free. Specifically the Harbor.\p"
	.string "I'll assemble the others, too.\n"
	.string "See you soon!$"

Exp1_Town01_SakuraText::
# 21 "data/expansion_1/rival_text.pory"
	.string "PLACEHOLDER$"

Exp1_Town01_HarperText::
# 25 "data/expansion_1/rival_text.pory"
	.string "PLACEHOLDER$"

Exp1_Town01_ReddText::
# 29 "data/expansion_1/rival_text.pory"
	.string "PLACEHOLDER$"

Exp1_Town01_BaronText::
# 33 "data/expansion_1/rival_text.pory"
	.string "PLACEHOLDER$"

Exp1_Town01_JaksonText::
# 37 "data/expansion_1/rival_text.pory"
	.string "PLACEHOLDER$"

Exp1_Town01_JaksonTextAccept::
# 41 "data/expansion_1/rival_text.pory"
	.string "PLACEHOLDER$"

Exp1_Town01_JaksonTextDecline::
# 45 "data/expansion_1/rival_text.pory"
	.string "PLACEHOLDER$"
