WoodlandCradleGrass_MapScripts::
	.byte 0


TrainerTipsMoveInfo::
# 4 "data/maps/WoodlandCradleGrass/scripts.pory"
	lock
# 5 "data/maps/WoodlandCradleGrass/scripts.pory"
	msgbox TrainerTipsMoveInfo_Text_0
# 6 "data/maps/WoodlandCradleGrass/scripts.pory"
	release
	end


TrainerTipsBallCycle::
# 11 "data/maps/WoodlandCradleGrass/scripts.pory"
	lock
# 12 "data/maps/WoodlandCradleGrass/scripts.pory"
	msgbox TrainerTipsBallCycle_Text_0
# 13 "data/maps/WoodlandCradleGrass/scripts.pory"
	release
	end


TrainerTipsStatusIVsEVs::
# 18 "data/maps/WoodlandCradleGrass/scripts.pory"
	lock
# 19 "data/maps/WoodlandCradleGrass/scripts.pory"
	msgbox TrainerTipsStatusIVsEVs_Text_0
# 20 "data/maps/WoodlandCradleGrass/scripts.pory"
	release
	end


TrainerTipsIVsNoEffect::
# 25 "data/maps/WoodlandCradleGrass/scripts.pory"
	lock
# 26 "data/maps/WoodlandCradleGrass/scripts.pory"
	msgbox TrainerTipsIVsNoEffect_Text_0
# 27 "data/maps/WoodlandCradleGrass/scripts.pory"
	release
	end


TrainerTipsNatureColors::
# 32 "data/maps/WoodlandCradleGrass/scripts.pory"
	lock
# 33 "data/maps/WoodlandCradleGrass/scripts.pory"
	msgbox TrainerTipsNatureColors_Text_0
# 34 "data/maps/WoodlandCradleGrass/scripts.pory"
	release
	end


Cheater::
# 39 "data/maps/WoodlandCradleGrass/scripts.pory"
	lock
# 40 "data/maps/WoodlandCradleGrass/scripts.pory"
	msgbox Cheater_Text_0
# 41 "data/maps/WoodlandCradleGrass/scripts.pory"
	release
	end


TrainerTipsMoveInfo_Text_0:
# 5 "data/maps/WoodlandCradleGrass/scripts.pory"
	.string "Trainer Tips\p"
	.string "When choosing a move to use in battle,\n"
	.string "press the L button to view move\l"
	.string "information.$"

TrainerTipsBallCycle_Text_0:
# 12 "data/maps/WoodlandCradleGrass/scripts.pory"
	.string "Trainer Tips\p"
	.string "In wild battles, hold the R button and\n"
	.string "press the Left or Right buttons to\l"
	.string "cycle between available Pokéballs.$"

TrainerTipsStatusIVsEVs_Text_0:
# 19 "data/maps/WoodlandCradleGrass/scripts.pory"
	.string "Trainer Tips\p"
	.string "When viewing stats in the Pokémon\n"
	.string "status screen, press the A button to\l"
	.string "cycle between stats, IVs, and EVs.$"

TrainerTipsIVsNoEffect_Text_0:
# 26 "data/maps/WoodlandCradleGrass/scripts.pory"
	.string "Trainer Tips\p"
	.string "Individual Values, or IVs, will not\n"
	.string "influence a Pokémon's stats. They will\l"
	.string "still change the type of Hidden Power.$"

TrainerTipsNatureColors_Text_0:
# 33 "data/maps/WoodlandCradleGrass/scripts.pory"
	.string "Trainer Tips\p"
	.string "A Pokémon's nature increases one stat\n"
	.string "and decreases another.\p"
	.string "The red stat on the Pokémon status\n"
	.string "screen is increased and the blue stat\l"
	.string "is decreased.$"

Cheater_Text_0:
# 40 "data/maps/WoodlandCradleGrass/scripts.pory"
	.string "How did you get up here?\n"
	.string "Are you cheating?$"
