WeatherScript_SetAndDo_None::
# 2 "data/scripts/weather.pory"
	setweather WEATHER_NONE
# 3 "data/scripts/weather.pory"
	doweather
	return


WeatherScript_SetAndDo_Sunny::
# 7 "data/scripts/weather.pory"
	setweather WEATHER_SUNNY
# 8 "data/scripts/weather.pory"
	doweather
	return


WeatherScript_SetAndDo_SunnyClouds::
# 12 "data/scripts/weather.pory"
	setweather WEATHER_SUNNY_CLOUDS
# 13 "data/scripts/weather.pory"
	doweather
	return


WeatherScript_SetAndDo_Drought::
# 17 "data/scripts/weather.pory"
	setweather WEATHER_DROUGHT
# 18 "data/scripts/weather.pory"
	doweather
	return


WeatherScript_SetAndDo_FogHorizontal::
# 22 "data/scripts/weather.pory"
	setweather WEATHER_FOG_HORIZONTAL
# 23 "data/scripts/weather.pory"
	doweather
	return


WeatherScript_SetAndDo_VolcanicAsh::
# 27 "data/scripts/weather.pory"
	setweather WEATHER_VOLCANIC_ASH
# 28 "data/scripts/weather.pory"
	doweather
	return


WeatherScript_SetAndDo_Sandstorm::
# 32 "data/scripts/weather.pory"
	setweather WEATHER_SANDSTORM
# 33 "data/scripts/weather.pory"
	doweather
	return


WeatherScript_SetAndDo_Rain::
# 37 "data/scripts/weather.pory"
	setweather WEATHER_RAIN
# 38 "data/scripts/weather.pory"
	doweather
	return


WeatherScript_SetAndDo_Snow::
# 42 "data/scripts/weather.pory"
	setweather WEATHER_SNOW
# 43 "data/scripts/weather.pory"
	doweather
	return


WeatherScript_SetAndDo_Abnormal::
# 47 "data/scripts/weather.pory"
	setweather WEATHER_ABNORMAL
# 48 "data/scripts/weather.pory"
	doweather
	return

