# 1 "data/maps/SootopolisCity/scripts.pory"

# 2 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_EXPERT, 1
# 3 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_WOMAN_2, 2
# 4 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_KIRI, 3
# 5 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_NINJA_BOY, 4
# 6 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_BOY_1, 5
# 7 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_STEVEN, 7
# 8 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_WOMAN_1, 8
# 9 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_GROUDON, 9
# 10 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_KYOGRE, 10
# 11 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_RAYQUAZA, 11
# 12 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_MANIAC, 12
# 13 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_GIRL, 13
# 14 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_BLACK_BELT, 14
# 15 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_BOY_2, 15
# 16 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_MAXIE, 16
# 17 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_ARCHIE, 17
# 18 "data/maps/SootopolisCity/scripts.pory"
.set LOCALID_WALLACE, 18
# 19 "data/maps/SootopolisCity/scripts.pory"

# 20 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_PanToActionFromPokeCenter:
# 21 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_southwest
# 22 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_southwest
# 23 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_southwest
# 24 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_southwest
# 25 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_southwest
# 26 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_southwest
# 27 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_southwest
# 28 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_southwest
# 29 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_southwest
# 30 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_southwest
# 31 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_southwest
# 32 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_southwest
# 33 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 34 "data/maps/SootopolisCity/scripts.pory"

# 35 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_PanBackToPokeCenter:
# 36 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_northeast
# 37 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_northeast
# 38 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_northeast
# 39 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_northeast
# 40 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_northeast
# 41 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_northeast
# 42 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_northeast
# 43 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_northeast
# 44 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_northeast
# 45 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_northeast
# 46 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_northeast
# 47 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_northeast
# 48 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 49 "data/maps/SootopolisCity/scripts.pory"

# 50 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_PanToActionFromDive:
# 51 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_northeast
# 52 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_northeast
# 53 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 54 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 55 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 56 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 57 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 58 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 59 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 60 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 61 "data/maps/SootopolisCity/scripts.pory"

# 62 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_PanBackToDive:
# 63 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 64 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 65 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 66 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 67 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 68 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 69 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 70 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_southwest
# 71 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_diag_southwest
# 72 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 73 "data/maps/SootopolisCity/scripts.pory"

# 74 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_KyogreAttack:
# 75 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_left
# 76 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_left
# 77 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_left
# 78 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 79 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 80 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 81 "data/maps/SootopolisCity/scripts.pory"
	init_affine_anim
# 82 "data/maps/SootopolisCity/scripts.pory"
	walk_left_affine
# 83 "data/maps/SootopolisCity/scripts.pory"
	clear_affine_anim
# 84 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 85 "data/maps/SootopolisCity/scripts.pory"

# 86 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_KyogreDefend:
# 87 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 88 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 89 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 90 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 91 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 92 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 93 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 94 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 95 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 96 "data/maps/SootopolisCity/scripts.pory"
	init_affine_anim
# 97 "data/maps/SootopolisCity/scripts.pory"
	walk_left_affine
# 98 "data/maps/SootopolisCity/scripts.pory"
	clear_affine_anim
# 99 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 100 "data/maps/SootopolisCity/scripts.pory"

# 101 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_KyogreMoveBack:
# 102 "data/maps/SootopolisCity/scripts.pory"
	lock_facing_direction
# 103 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 104 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 105 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 106 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 107 "data/maps/SootopolisCity/scripts.pory"
	unlock_facing_direction
# 108 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 109 "data/maps/SootopolisCity/scripts.pory"

# 110 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_KyogreIdle:
# 111 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_left
# 112 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_left
# 113 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_left
# 114 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_left
# 115 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_left
# 116 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_left
# 117 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 118 "data/maps/SootopolisCity/scripts.pory"

# 119 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_GroudonAttack:
# 120 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_right
# 121 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_right
# 122 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_right
# 123 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 124 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 125 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 126 "data/maps/SootopolisCity/scripts.pory"
	walk_fast_right
# 127 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 128 "data/maps/SootopolisCity/scripts.pory"

# 129 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_GroudonDefend:
# 130 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 131 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 132 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 133 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 134 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 135 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 136 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 137 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 138 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 139 "data/maps/SootopolisCity/scripts.pory"
	walk_fast_right
# 140 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 141 "data/maps/SootopolisCity/scripts.pory"

# 142 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_GroudonMoveBack:
# 143 "data/maps/SootopolisCity/scripts.pory"
	lock_facing_direction
# 144 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 145 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 146 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 147 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 148 "data/maps/SootopolisCity/scripts.pory"
	unlock_facing_direction
# 149 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 150 "data/maps/SootopolisCity/scripts.pory"

# 151 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_GroudonIdle:
# 152 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_right
# 153 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_right
# 154 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_right
# 155 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_right
# 156 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_right
# 157 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_slow_right
# 158 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 159 "data/maps/SootopolisCity/scripts.pory"

# 160 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_RayquazaFlyOff:
# 161 "data/maps/SootopolisCity/scripts.pory"
	walk_fast_up
# 162 "data/maps/SootopolisCity/scripts.pory"
	walk_faster_up
# 163 "data/maps/SootopolisCity/scripts.pory"
	walk_faster_up
# 164 "data/maps/SootopolisCity/scripts.pory"
	walk_faster_up
# 165 "data/maps/SootopolisCity/scripts.pory"
	walk_faster_up
# 166 "data/maps/SootopolisCity/scripts.pory"
	walk_faster_up
# 167 "data/maps/SootopolisCity/scripts.pory"
	walk_faster_up
# 168 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 169 "data/maps/SootopolisCity/scripts.pory"

# 170 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_CaveOfOriginExpert::
# 171 "data/maps/SootopolisCity/scripts.pory"
	lock
# 172 "data/maps/SootopolisCity/scripts.pory"
	faceplayer
# 173 "data/maps/SootopolisCity/scripts.pory"
	goto_if_ge VAR_SOOTOPOLIS_CITY_STATE, 6, SootopolisCity_EventScript_ExpertPostLegendaries
# 174 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 5, SootopolisCity_EventScript_ExpertLegendaries
# 175 "data/maps/SootopolisCity/scripts.pory"
	goto_if_ge VAR_SOOTOPOLIS_CITY_STATE, 2, SootopolisCity_EventScript_ExpertLeadToCave
# 176 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_CaveOfOriginPleaseLeave, MSGBOX_DEFAULT
# 177 "data/maps/SootopolisCity/scripts.pory"
	release
# 178 "data/maps/SootopolisCity/scripts.pory"
	end
# 179 "data/maps/SootopolisCity/scripts.pory"

# 180 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_ExpertLeadToCave::
# 181 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_LeadSuperiorTrainerToCave, MSGBOX_DEFAULT
# 182 "data/maps/SootopolisCity/scripts.pory"
	release
# 183 "data/maps/SootopolisCity/scripts.pory"
	end
# 184 "data/maps/SootopolisCity/scripts.pory"

# 185 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_ExpertPostLegendaries::
# 186 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_CaveOfOriginSleepsToo, MSGBOX_DEFAULT
# 187 "data/maps/SootopolisCity/scripts.pory"
	release
# 188 "data/maps/SootopolisCity/scripts.pory"
	end
# 189 "data/maps/SootopolisCity/scripts.pory"

# 190 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_ExpertLegendaries::
# 191 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_AwakenedPokemonClash, MSGBOX_DEFAULT
# 192 "data/maps/SootopolisCity/scripts.pory"
	release
# 193 "data/maps/SootopolisCity/scripts.pory"
	end
# 194 "data/maps/SootopolisCity/scripts.pory"

# 195 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Kiri::
# 196 "data/maps/SootopolisCity/scripts.pory"
	lock
# 197 "data/maps/SootopolisCity/scripts.pory"
	faceplayer
# 198 "data/maps/SootopolisCity/scripts.pory"
	goto_if_le VAR_SOOTOPOLIS_CITY_STATE, 1, SootopolisCity_EventScript_KiriGiveBerry
# 199 "data/maps/SootopolisCity/scripts.pory"
	goto_if_ge VAR_SOOTOPOLIS_CITY_STATE, 6, SootopolisCity_EventScript_KiriGiveBerry
# 200 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 5, SootopolisCity_EventScript_KiriRayquaza
# 201 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_BigPokemonFighting, MSGBOX_DEFAULT
# 202 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 203 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_KIRI, Common_Movement_FaceOriginalDirection
# 204 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 205 "data/maps/SootopolisCity/scripts.pory"
	release
# 206 "data/maps/SootopolisCity/scripts.pory"
	end
# 207 "data/maps/SootopolisCity/scripts.pory"

# 208 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_KiriRayquaza::
# 209 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_PrettyMonCameFromSky, MSGBOX_DEFAULT
# 210 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 211 "data/maps/SootopolisCity/scripts.pory"
	release
# 212 "data/maps/SootopolisCity/scripts.pory"
	end
# 213 "data/maps/SootopolisCity/scripts.pory"

# 214 "data/maps/SootopolisCity/scripts.pory"
@ Gives 2 berries daily. First ranges from FIRST_KIRI_BERRY to LAST_KIRI_BERRY, second is always Figy or Iapapa
# 215 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_KiriGiveBerry::
# 216 "data/maps/SootopolisCity/scripts.pory"
	dotimebasedevents
# 217 "data/maps/SootopolisCity/scripts.pory"
	special GetPlayerBigGuyGirlString
# 218 "data/maps/SootopolisCity/scripts.pory"
	goto_if_set FLAG_DAILY_SOOTOPOLIS_RECEIVED_BERRY, SootopolisCity_EventScript_KiriReceivedBerry
# 219 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_NameIsKiriHaveOneOfThese, MSGBOX_DEFAULT
# 220 "data/maps/SootopolisCity/scripts.pory"
	random NUM_KIRI_BERRIES
# 221 "data/maps/SootopolisCity/scripts.pory"
	addvar VAR_RESULT, NUM_KIRI_BERRIES_SKIPPED
# 222 "data/maps/SootopolisCity/scripts.pory"
	addvar VAR_RESULT, FIRST_BERRY_INDEX
# 223 "data/maps/SootopolisCity/scripts.pory"
	giveitem VAR_RESULT
# 224 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
# 225 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_DAILY_SOOTOPOLIS_RECEIVED_BERRY
# 226 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_GiveYouThisBerryToo, MSGBOX_DEFAULT
# 227 "data/maps/SootopolisCity/scripts.pory"
	random 2
# 228 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_RESULT, 0, SootopolisCity_EventScript_GiveFigyBerry
# 229 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_RESULT, 1, SootopolisCity_EventScript_GiveIapapaBerry
# 230 "data/maps/SootopolisCity/scripts.pory"
	end
# 231 "data/maps/SootopolisCity/scripts.pory"

# 232 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_GiveFigyBerry::
# 233 "data/maps/SootopolisCity/scripts.pory"
	giveitem ITEM_FIGY_BERRY
# 234 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
# 235 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_WhatKindOfWishInYourName, MSGBOX_DEFAULT
# 236 "data/maps/SootopolisCity/scripts.pory"
	release
# 237 "data/maps/SootopolisCity/scripts.pory"
	end
# 238 "data/maps/SootopolisCity/scripts.pory"

# 239 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_GiveIapapaBerry::
# 240 "data/maps/SootopolisCity/scripts.pory"
	giveitem ITEM_IAPAPA_BERRY
# 241 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
# 242 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_WhatKindOfWishInYourName, MSGBOX_DEFAULT
# 243 "data/maps/SootopolisCity/scripts.pory"
	release
# 244 "data/maps/SootopolisCity/scripts.pory"
	end
# 245 "data/maps/SootopolisCity/scripts.pory"

# 246 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_KiriReceivedBerry::
# 247 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_LikeSeasonBornIn, MSGBOX_YESNO
# 248 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_RESULT, YES, SootopolisCity_EventScript_KiriLikeSeasonBornIn
# 249 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_OhDoesntMatter, MSGBOX_DEFAULT
# 250 "data/maps/SootopolisCity/scripts.pory"
	release
# 251 "data/maps/SootopolisCity/scripts.pory"
	end
# 252 "data/maps/SootopolisCity/scripts.pory"

# 253 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_KiriLikeSeasonBornIn::
# 254 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_ThenILoveAutumn, MSGBOX_DEFAULT
# 255 "data/maps/SootopolisCity/scripts.pory"
	release
# 256 "data/maps/SootopolisCity/scripts.pory"
	end
# 257 "data/maps/SootopolisCity/scripts.pory"

# 258 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Woman2::
# 259 "data/maps/SootopolisCity/scripts.pory"
	lockall
# 260 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_WOMAN_2, Common_Movement_FacePlayer
# 261 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 262 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 5, SootopolisCity_EventScript_Woman2Rayquaza
# 263 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_WeatherWentWild, MSGBOX_DEFAULT
# 264 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 265 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_WOMAN_2, Common_Movement_FaceOriginalDirection
# 266 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 267 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 268 "data/maps/SootopolisCity/scripts.pory"
	end
# 269 "data/maps/SootopolisCity/scripts.pory"

# 270 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Woman2Rayquaza::
# 271 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_YouBroughtFlyingMon, MSGBOX_DEFAULT
# 272 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 273 "data/maps/SootopolisCity/scripts.pory"
	end
# 274 "data/maps/SootopolisCity/scripts.pory"

# 275 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Man::
# 276 "data/maps/SootopolisCity/scripts.pory"
	lock
# 277 "data/maps/SootopolisCity/scripts.pory"
	faceplayer
# 278 "data/maps/SootopolisCity/scripts.pory"
	goto_if_ge VAR_SOOTOPOLIS_CITY_STATE, 6, SootopolisCity_EventScript_ManPostLegendaries
# 279 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_NoOrdinaryTourist, MSGBOX_DEFAULT
# 280 "data/maps/SootopolisCity/scripts.pory"
	release
# 281 "data/maps/SootopolisCity/scripts.pory"
	end
# 282 "data/maps/SootopolisCity/scripts.pory"

# 283 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_ManPostLegendaries::
# 284 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_CityRegainedCalm, MSGBOX_DEFAULT
# 285 "data/maps/SootopolisCity/scripts.pory"
	release
# 286 "data/maps/SootopolisCity/scripts.pory"
	end
# 287 "data/maps/SootopolisCity/scripts.pory"

# 288 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Woman1::
# 289 "data/maps/SootopolisCity/scripts.pory"
	lock
# 290 "data/maps/SootopolisCity/scripts.pory"
	faceplayer
# 291 "data/maps/SootopolisCity/scripts.pory"
	goto_if_ge VAR_SOOTOPOLIS_CITY_STATE, 6, SootopolisCity_EventScript_Woman1PostLegendaries
# 292 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 5, SootopolisCity_EventScript_Woman1Rayquaza
# 293 "data/maps/SootopolisCity/scripts.pory"
	goto_if_ge VAR_SOOTOPOLIS_CITY_STATE, 2, SootopolisCity_EventScript_Woman1Legendaries
# 294 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_SootopolisSkyBeautiful, MSGBOX_DEFAULT
# 295 "data/maps/SootopolisCity/scripts.pory"
	release
# 296 "data/maps/SootopolisCity/scripts.pory"
	end
# 297 "data/maps/SootopolisCity/scripts.pory"

# 298 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Woman1Legendaries::
# 299 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_GiganticPokemonFight, MSGBOX_DEFAULT
# 300 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 301 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_WOMAN_1, Common_Movement_FaceOriginalDirection
# 302 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 303 "data/maps/SootopolisCity/scripts.pory"
	release
# 304 "data/maps/SootopolisCity/scripts.pory"
	end
# 305 "data/maps/SootopolisCity/scripts.pory"

# 306 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Woman1PostLegendaries::
# 307 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_NightSkyFavoriteScenery, MSGBOX_DEFAULT
# 308 "data/maps/SootopolisCity/scripts.pory"
	release
# 309 "data/maps/SootopolisCity/scripts.pory"
	end
# 310 "data/maps/SootopolisCity/scripts.pory"

# 311 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Woman1Rayquaza::
# 312 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_FearedWorstWhenPokemonFlewDown, MSGBOX_DEFAULT
# 313 "data/maps/SootopolisCity/scripts.pory"
	release
# 314 "data/maps/SootopolisCity/scripts.pory"
	end
# 315 "data/maps/SootopolisCity/scripts.pory"

# 316 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_NinjaBoy::
# 317 "data/maps/SootopolisCity/scripts.pory"
	lockall
# 318 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_NINJA_BOY, Common_Movement_FacePlayer
# 319 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 320 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 5, SootopolisCity_EventScript_NinjaBoyRayquaza
# 321 "data/maps/SootopolisCity/scripts.pory"
	goto_if_ge VAR_SOOTOPOLIS_CITY_STATE, 6, SootopolisCity_EventScript_NinjaBoyNormal
# 322 "data/maps/SootopolisCity/scripts.pory"
	goto_if_le VAR_SOOTOPOLIS_CITY_STATE, 1, SootopolisCity_EventScript_NinjaBoyNormal
# 323 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_ThisIsWicked, MSGBOX_DEFAULT
# 324 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 325 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_NINJA_BOY, Common_Movement_FaceOriginalDirection
# 326 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 327 "data/maps/SootopolisCity/scripts.pory"
	release
# 328 "data/maps/SootopolisCity/scripts.pory"
	end
# 329 "data/maps/SootopolisCity/scripts.pory"

# 330 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_NinjaBoyNormal::
# 331 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_WonderWhatWorldIsLike, MSGBOX_DEFAULT
# 332 "data/maps/SootopolisCity/scripts.pory"
	release
# 333 "data/maps/SootopolisCity/scripts.pory"
	end
# 334 "data/maps/SootopolisCity/scripts.pory"

# 335 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_NinjaBoyRayquaza::
# 336 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_ThatWasWicked, MSGBOX_DEFAULT
# 337 "data/maps/SootopolisCity/scripts.pory"
	release
# 338 "data/maps/SootopolisCity/scripts.pory"
	end
# 339 "data/maps/SootopolisCity/scripts.pory"

# 340 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Boy1::
# 341 "data/maps/SootopolisCity/scripts.pory"
	lockall
# 342 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_BOY_1, Common_Movement_FacePlayer
# 343 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 344 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 5, SootopolisCity_EventScript_Boy1Rayquaza
# 345 "data/maps/SootopolisCity/scripts.pory"
	goto_if_set FLAG_SYS_GAME_CLEAR, SootopolisCity_EventScript_Boy1GameClear
# 346 "data/maps/SootopolisCity/scripts.pory"
	goto_if_ge VAR_SOOTOPOLIS_CITY_STATE, 6, SootopolisCity_EventScript_Boy1Normal
# 347 "data/maps/SootopolisCity/scripts.pory"
	goto_if_le VAR_SOOTOPOLIS_CITY_STATE, 1, SootopolisCity_EventScript_Boy1Normal
# 348 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_GiantPokemonSuddenlyAppeared, MSGBOX_DEFAULT
# 349 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 350 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_BOY_1, Common_Movement_FaceOriginalDirection
# 351 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 352 "data/maps/SootopolisCity/scripts.pory"
	release
# 353 "data/maps/SootopolisCity/scripts.pory"
	end
# 354 "data/maps/SootopolisCity/scripts.pory"

# 355 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Boy1Rayquaza::
# 356 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_WhatIsThatGreenPokemon, MSGBOX_DEFAULT
# 357 "data/maps/SootopolisCity/scripts.pory"
	release
# 358 "data/maps/SootopolisCity/scripts.pory"
	end
# 359 "data/maps/SootopolisCity/scripts.pory"

# 360 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Boy1GameClear::
# 361 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_WhereDidLegendariesGo, MSGBOX_DEFAULT
# 362 "data/maps/SootopolisCity/scripts.pory"
	release
# 363 "data/maps/SootopolisCity/scripts.pory"
	end
# 364 "data/maps/SootopolisCity/scripts.pory"

# 365 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Boy1Normal::
# 366 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_PhysicallyFitLivingHere, MSGBOX_DEFAULT
# 367 "data/maps/SootopolisCity/scripts.pory"
	release
# 368 "data/maps/SootopolisCity/scripts.pory"
	end
# 369 "data/maps/SootopolisCity/scripts.pory"

# 370 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_GymSign::
# 371 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_GymSign, MSGBOX_SIGN
# 372 "data/maps/SootopolisCity/scripts.pory"
	end
# 373 "data/maps/SootopolisCity/scripts.pory"

# 374 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_CitySign::
# 375 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_CitySign, MSGBOX_SIGN
# 376 "data/maps/SootopolisCity/scripts.pory"
	end
# 377 "data/maps/SootopolisCity/scripts.pory"

# 378 "data/maps/SootopolisCity/scripts.pory"
EventScript_ClosedSootopolisDoor::
# 379 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_DoorIsClosed, MSGBOX_SIGN
# 380 "data/maps/SootopolisCity/scripts.pory"
	end
# 381 "data/maps/SootopolisCity/scripts.pory"

# 382 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Steven::
# 383 "data/maps/SootopolisCity/scripts.pory"
	lockall
# 384 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_STEVEN, Common_Movement_FacePlayer
# 385 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 386 "data/maps/SootopolisCity/scripts.pory"
	call_if_unset FLAG_STEVEN_GUIDES_TO_CAVE_OF_ORIGIN, SootopolisCity_EventScript_StevenLeadPlayerCaveOfOrigin
# 387 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 2, SootopolisCity_EventScript_StevenHelpWallace
# 388 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 3, SootopolisCity_EventScript_StevenHelpedWallace
# 389 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 4, SootopolisCity_EventScript_StevenHelpedWallace
# 390 "data/maps/SootopolisCity/scripts.pory"
	goto_if_set FLAG_SOOTOPOLIS_ARCHIE_MAXIE_LEAVE, SootopolisCity_EventScript_StevenMaxieArchieLeft
# 391 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_SoThatsRayquaza, MSGBOX_DEFAULT
# 392 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 393 "data/maps/SootopolisCity/scripts.pory"
	end
# 394 "data/maps/SootopolisCity/scripts.pory"

# 395 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_StevenHelpWallace::
# 396 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_KnowWhatsNeededToHelpHim, MSGBOX_DEFAULT
# 397 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 398 "data/maps/SootopolisCity/scripts.pory"
	end
# 399 "data/maps/SootopolisCity/scripts.pory"

# 400 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_StevenMaxieArchieLeft::
# 401 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_MaxieArchieLeft, MSGBOX_DEFAULT
# 402 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 403 "data/maps/SootopolisCity/scripts.pory"
	end
# 404 "data/maps/SootopolisCity/scripts.pory"

# 405 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_StevenHelpedWallace::
# 406 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_NeverBeenToSkyPillar, MSGBOX_DEFAULT
# 407 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 408 "data/maps/SootopolisCity/scripts.pory"
	end
# 409 "data/maps/SootopolisCity/scripts.pory"

# 410 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_StevenLeadPlayerCaveOfOrigin::
# 411 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_InvolvedWithCrisisComeWithMe, MSGBOX_DEFAULT
# 412 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 413 "data/maps/SootopolisCity/scripts.pory"
	call_if_eq VAR_FACING, DIR_WEST, SootopolisCity_EventScript_StartWalkToCaveOfOriginWest
# 414 "data/maps/SootopolisCity/scripts.pory"
	call_if_eq VAR_FACING, DIR_NORTH, SootopolisCity_EventScript_StartWalkToCaveOfOriginNorth
# 415 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_DoesThisMakeYourFearPokemon, MSGBOX_DEFAULT
# 416 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 417 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_STEVEN, SootopolisCity_Movement_StevenWalkToCaveOfOrigin
# 418 "data/maps/SootopolisCity/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, SootopolisCity_Movement_PlayerWalkToCaveOfOrigin
# 419 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 420 "data/maps/SootopolisCity/scripts.pory"
	delay 120
# 421 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_EXPERT, SootopolisCity_Movement_ExpertMoveAside
# 422 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 423 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_STEVEN, SootopolisCity_Movement_StevenArriveCaveEntrance
# 424 "data/maps/SootopolisCity/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, SootopolisCity_Movement_PlayerArriveCaveEntrance
# 425 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 426 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_HereWereAreHelpWallace, MSGBOX_DEFAULT
# 427 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 428 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_STEVEN_GUIDES_TO_CAVE_OF_ORIGIN
# 429 "data/maps/SootopolisCity/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkUp2
# 430 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 431 "data/maps/SootopolisCity/scripts.pory"
	warp MAP_CAVE_OF_ORIGIN_ENTRANCE, 9, 20
# 432 "data/maps/SootopolisCity/scripts.pory"
	waitstate
# 433 "data/maps/SootopolisCity/scripts.pory"
	end
# 434 "data/maps/SootopolisCity/scripts.pory"

# 435 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_StartWalkToCaveOfOriginWest::
# 436 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_STEVEN, SootopolisCity_Movement_StevenStartWalkToCaveOfOrigin
# 437 "data/maps/SootopolisCity/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, SootopolisCity_Movement_PlayerStartWalkToCaveOfOriginWest
# 438 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 439 "data/maps/SootopolisCity/scripts.pory"
	return
# 440 "data/maps/SootopolisCity/scripts.pory"

# 441 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_StartWalkToCaveOfOriginNorth::
# 442 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_STEVEN, SootopolisCity_Movement_StevenStartWalkToCaveOfOrigin
# 443 "data/maps/SootopolisCity/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, SootopolisCity_Movement_PlayerStartWalkToCaveOfOriginNorth
# 444 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 445 "data/maps/SootopolisCity/scripts.pory"
	return
# 446 "data/maps/SootopolisCity/scripts.pory"

# 447 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_StevenStartWalkToCaveOfOrigin:
# 448 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 449 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 450 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 451 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 452 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 453 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 454 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 455 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 456 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 457 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 458 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 459 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 460 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 461 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 462 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 463 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 464 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 465 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 466 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 467 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 468 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 469 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 470 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 471 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 472 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 473 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 474 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 475 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 476 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 477 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 478 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 479 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 480 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 481 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 482 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 483 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_faster_down
# 484 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 485 "data/maps/SootopolisCity/scripts.pory"

# 486 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_PlayerStartWalkToCaveOfOriginWest:
# 487 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 488 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 489 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 490 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 491 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 492 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 493 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 494 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 495 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 496 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 497 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 498 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 499 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 500 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 501 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 502 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 503 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 504 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 505 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 506 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 507 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 508 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 509 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 510 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 511 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 512 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 513 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 514 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 515 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 516 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 517 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 518 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 519 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 520 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 521 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 522 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 523 "data/maps/SootopolisCity/scripts.pory"

# 524 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_PlayerStartWalkToCaveOfOriginNorth:
# 525 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 526 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 527 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 528 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 529 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 530 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 531 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 532 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 533 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 534 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 535 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 536 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 537 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 538 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 539 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 540 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 541 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 542 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 543 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 544 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 545 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 546 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 547 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 548 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 549 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 550 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 551 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 552 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 553 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 554 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 555 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 556 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 557 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 558 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 559 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 560 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 561 "data/maps/SootopolisCity/scripts.pory"

# 562 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_StevenWalkToCaveOfOrigin:
# 563 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 564 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 565 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 566 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 567 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 568 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 569 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 570 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 571 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 572 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 573 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 574 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 575 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 576 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 577 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 578 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 579 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 580 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 581 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 582 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 583 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 584 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 585 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 586 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 587 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 588 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 589 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 590 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 591 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 592 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 593 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 594 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 595 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 596 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 597 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 598 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 599 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 600 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 601 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 602 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 603 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 604 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 605 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 606 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 607 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 608 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 609 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 610 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 611 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 612 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 613 "data/maps/SootopolisCity/scripts.pory"
	delay_4
# 614 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_faster_left
# 615 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 616 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 617 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 618 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 619 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 620 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 621 "data/maps/SootopolisCity/scripts.pory"

# 622 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_PlayerWalkToCaveOfOrigin:
# 623 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 624 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 625 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 626 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 627 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 628 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 629 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 630 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 631 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 632 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 633 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 634 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 635 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 636 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 637 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 638 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 639 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 640 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 641 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 642 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 643 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 644 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 645 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 646 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 647 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 648 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 649 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 650 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 651 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 652 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 653 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 654 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 655 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 656 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 657 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 658 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 659 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 660 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 661 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 662 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 663 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 664 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 665 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 666 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 667 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 668 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 669 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 670 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 671 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 672 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 673 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 674 "data/maps/SootopolisCity/scripts.pory"

# 675 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_ExpertMoveAside:
# 676 "data/maps/SootopolisCity/scripts.pory"
	walk_slow_left
# 677 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_faster_right
# 678 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 679 "data/maps/SootopolisCity/scripts.pory"

# 680 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_StevenArriveCaveEntrance:
# 681 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 682 "data/maps/SootopolisCity/scripts.pory"
	walk_down
# 683 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 684 "data/maps/SootopolisCity/scripts.pory"
	delay_8
# 685 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 686 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 687 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 688 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 689 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 690 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_faster_left
# 691 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 692 "data/maps/SootopolisCity/scripts.pory"

# 693 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_PlayerArriveCaveEntrance:
# 694 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 695 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 696 "data/maps/SootopolisCity/scripts.pory"
	delay_16
# 697 "data/maps/SootopolisCity/scripts.pory"
	delay_8
# 698 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 699 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 700 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 701 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 702 "data/maps/SootopolisCity/scripts.pory"
	walk_up
# 703 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_faster_right
# 704 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 705 "data/maps/SootopolisCity/scripts.pory"

# 706 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Boy2::
# 707 "data/maps/SootopolisCity/scripts.pory"
	lockall
# 708 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_BOY_2, Common_Movement_FacePlayer
# 709 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 710 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 5, SootopolisCity_EventScript_Boy2Rayquaza
# 711 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_TwoPokemonArentAngry, MSGBOX_DEFAULT
# 712 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 713 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_BOY_2, Common_Movement_FaceOriginalDirection
# 714 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 715 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 716 "data/maps/SootopolisCity/scripts.pory"
	end
# 717 "data/maps/SootopolisCity/scripts.pory"

# 718 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Boy2Rayquaza::
# 719 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_FlyingMonStoppedRampage, MSGBOX_DEFAULT
# 720 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 721 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 722 "data/maps/SootopolisCity/scripts.pory"
	end
# 723 "data/maps/SootopolisCity/scripts.pory"

# 724 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_BlackBelt::
# 725 "data/maps/SootopolisCity/scripts.pory"
	lockall
# 726 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 5, SootopolisCity_EventScript_BlackBeltRayquaza
# 727 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_GoRedAndBlueMon, MSGBOX_DEFAULT
# 728 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 729 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_BLACK_BELT, Common_Movement_FacePlayer
# 730 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 731 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_DoYouKnowMonNames, MSGBOX_DEFAULT
# 732 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 733 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_BLACK_BELT, Common_Movement_FaceOriginalDirection
# 734 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 735 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 736 "data/maps/SootopolisCity/scripts.pory"
	end
# 737 "data/maps/SootopolisCity/scripts.pory"

# 738 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_BlackBeltRayquaza::
# 739 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_BLACK_BELT, Common_Movement_FacePlayer
# 740 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 741 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_GreenOneSettlesThings, MSGBOX_DEFAULT
# 742 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 743 "data/maps/SootopolisCity/scripts.pory"
	end
# 744 "data/maps/SootopolisCity/scripts.pory"

# 745 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Girl::
# 746 "data/maps/SootopolisCity/scripts.pory"
	lockall
# 747 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_GIRL, Common_Movement_FacePlayer
# 748 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 749 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 5, SootopolisCity_EventScript_GirlRayquaza
# 750 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_SootopolisWillBeWrecked, MSGBOX_DEFAULT
# 751 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 752 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_GIRL, Common_Movement_FaceOriginalDirection
# 753 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 754 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 755 "data/maps/SootopolisCity/scripts.pory"
	end
# 756 "data/maps/SootopolisCity/scripts.pory"

# 757 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_GirlRayquaza::
# 758 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_SootopolisDidntGetWrecked, MSGBOX_DEFAULT
# 759 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 760 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 761 "data/maps/SootopolisCity/scripts.pory"
	end
# 762 "data/maps/SootopolisCity/scripts.pory"

# 763 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Maniac::
# 764 "data/maps/SootopolisCity/scripts.pory"
	lockall
# 765 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_MANIAC, Common_Movement_FacePlayer
# 766 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 767 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 5, SootopolisCity_EventScript_ManiacRayquaza
# 768 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_SeeingLegendWithOwnEyes, MSGBOX_DEFAULT
# 769 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 770 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_MANIAC, Common_Movement_FaceOriginalDirection
# 771 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 772 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 773 "data/maps/SootopolisCity/scripts.pory"
	end
# 774 "data/maps/SootopolisCity/scripts.pory"

# 775 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_ManiacRayquaza::
# 776 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_SawLegendWithOwnEyes, MSGBOX_DEFAULT
# 777 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 778 "data/maps/SootopolisCity/scripts.pory"
	end
# 779 "data/maps/SootopolisCity/scripts.pory"

# 780 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Wallace::
# 781 "data/maps/SootopolisCity/scripts.pory"
	lock
# 782 "data/maps/SootopolisCity/scripts.pory"
	faceplayer
# 783 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 4, SootopolisCity_EventScript_GoToSkyPillar
# 784 "data/maps/SootopolisCity/scripts.pory"
	goto_if_set FLAG_RECEIVED_HM_WATERFALL, SootopolisCity_EventScript_GoToGym
# 785 "data/maps/SootopolisCity/scripts.pory"
	goto_if_set FLAG_SOOTOPOLIS_ARCHIE_MAXIE_LEAVE, SootopolisCity_EventScript_GiveWaterfall
# 786 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_AquaMagmaDidntMeanHarm, MSGBOX_DEFAULT
# 787 "data/maps/SootopolisCity/scripts.pory"
	release
# 788 "data/maps/SootopolisCity/scripts.pory"
	end
# 789 "data/maps/SootopolisCity/scripts.pory"

# 790 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_GiveWaterfall::
# 791 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_ThankYouForHelpAcceptThis, MSGBOX_DEFAULT
# 792 "data/maps/SootopolisCity/scripts.pory"
	giveitem ITEM_HM_WATERFALL
# 793 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_RECEIVED_HM_WATERFALL
# 794 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_ExplainWaterfallGoToGym, MSGBOX_DEFAULT
# 795 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 796 "data/maps/SootopolisCity/scripts.pory"
	call_if_eq VAR_FACING, DIR_NORTH, SootopolisCity_EventScript_WallaceMoveFromGym
# 797 "data/maps/SootopolisCity/scripts.pory"
	call_if_eq VAR_FACING, DIR_EAST, SootopolisCity_EventScript_WallaceMoveFromGym
# 798 "data/maps/SootopolisCity/scripts.pory"
	call_if_eq VAR_FACING, DIR_WEST, SootopolisCity_EventScript_WallaceMoveFromGymWest
# 799 "data/maps/SootopolisCity/scripts.pory"
	release
# 800 "data/maps/SootopolisCity/scripts.pory"
	end
# 801 "data/maps/SootopolisCity/scripts.pory"

# 802 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_WallaceMoveFromGym::
# 803 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_WALLACE, SootopolisCity_Movement_WallaceMoveFromGym
# 804 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 805 "data/maps/SootopolisCity/scripts.pory"
	copyobjectxytoperm LOCALID_WALLACE
# 806 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_SOOTOPOLIS_WALLACE_STATE, 1
# 807 "data/maps/SootopolisCity/scripts.pory"
	return
# 808 "data/maps/SootopolisCity/scripts.pory"

# 809 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_WallaceMoveFromGymWest::
# 810 "data/maps/SootopolisCity/scripts.pory"
	applymovement LOCALID_WALLACE, SootopolisCity_Movement_WallaceMoveFromGymWest
# 811 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 812 "data/maps/SootopolisCity/scripts.pory"
	copyobjectxytoperm LOCALID_WALLACE
# 813 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_SOOTOPOLIS_WALLACE_STATE, 2
# 814 "data/maps/SootopolisCity/scripts.pory"
	return
# 815 "data/maps/SootopolisCity/scripts.pory"

# 816 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_GoToSkyPillar::
# 817 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_HaventYouScaledSkyPillar, MSGBOX_DEFAULT
# 818 "data/maps/SootopolisCity/scripts.pory"
	release
# 819 "data/maps/SootopolisCity/scripts.pory"
	end
# 820 "data/maps/SootopolisCity/scripts.pory"

# 821 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_GoToGym::
# 822 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_DazzledByMentor, MSGBOX_DEFAULT
# 823 "data/maps/SootopolisCity/scripts.pory"
	release
# 824 "data/maps/SootopolisCity/scripts.pory"
	end
# 825 "data/maps/SootopolisCity/scripts.pory"

# 826 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_WallaceMoveFromGym:
# 827 "data/maps/SootopolisCity/scripts.pory"
	walk_right
# 828 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_faster_down
# 829 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 830 "data/maps/SootopolisCity/scripts.pory"

# 831 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Movement_WallaceMoveFromGymWest:
# 832 "data/maps/SootopolisCity/scripts.pory"
	walk_left
# 833 "data/maps/SootopolisCity/scripts.pory"
	walk_in_place_faster_down
# 834 "data/maps/SootopolisCity/scripts.pory"
	step_end
# 835 "data/maps/SootopolisCity/scripts.pory"

# 836 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Maxie::
# 837 "data/maps/SootopolisCity/scripts.pory"
	lockall
# 838 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 5, SootopolisCity_EventScript_MaxieRayquaza
# 839 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_GroudonPleaseStop, MSGBOX_DEFAULT
# 840 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 841 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 842 "data/maps/SootopolisCity/scripts.pory"
	end
# 843 "data/maps/SootopolisCity/scripts.pory"

# 844 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_MaxieRayquaza::
# 845 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_AfterAllOurScheming, MSGBOX_DEFAULT
# 846 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_MET_MAXIE_SOOTOPOLIS
# 847 "data/maps/SootopolisCity/scripts.pory"
	goto_if_set FLAG_MET_ARCHIE_SOOTOPOLIS, SootopolisCity_EventScript_MaxieArchieLeave
# 848 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 849 "data/maps/SootopolisCity/scripts.pory"
	end
# 850 "data/maps/SootopolisCity/scripts.pory"

# 851 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_Archie::
# 852 "data/maps/SootopolisCity/scripts.pory"
	lockall
# 853 "data/maps/SootopolisCity/scripts.pory"
	goto_if_eq VAR_SOOTOPOLIS_CITY_STATE, 5, SootopolisCity_EventScript_ArchieRayquaza
# 854 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_KyogreCalmDown, MSGBOX_DEFAULT
# 855 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 856 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 857 "data/maps/SootopolisCity/scripts.pory"
	end
# 858 "data/maps/SootopolisCity/scripts.pory"

# 859 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_ArchieRayquaza::
# 860 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_TryingMeaninglessToPokemon, MSGBOX_DEFAULT
# 861 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_MET_ARCHIE_SOOTOPOLIS
# 862 "data/maps/SootopolisCity/scripts.pory"
	goto_if_set FLAG_MET_MAXIE_SOOTOPOLIS, SootopolisCity_EventScript_MaxieArchieLeave
# 863 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 864 "data/maps/SootopolisCity/scripts.pory"
	end
# 865 "data/maps/SootopolisCity/scripts.pory"

# 866 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_EventScript_MaxieArchieLeave::
# 867 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_HIDE_SOOTOPOLIS_CITY_MAXIE
# 868 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_HIDE_SOOTOPOLIS_CITY_ARCHIE
# 869 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_SOOTOPOLIS_ARCHIE_MAXIE_LEAVE
# 870 "data/maps/SootopolisCity/scripts.pory"
	clearflag FLAG_HIDE_MT_PYRE_SUMMIT_MAXIE
# 871 "data/maps/SootopolisCity/scripts.pory"
	clearflag FLAG_HIDE_MT_PYRE_SUMMIT_ARCHIE
# 872 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_MT_PYRE_STATE, 2
# 873 "data/maps/SootopolisCity/scripts.pory"
	warpsilent MAP_SOOTOPOLIS_CITY, 31, 34
# 874 "data/maps/SootopolisCity/scripts.pory"
	waitstate
# 875 "data/maps/SootopolisCity/scripts.pory"
	releaseall
# 876 "data/maps/SootopolisCity/scripts.pory"
	end
# 877 "data/maps/SootopolisCity/scripts.pory"

# 878 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_GymSign:
# 879 "data/maps/SootopolisCity/scripts.pory"
	.string "Sootopolis City Pokémon Gym\n"
# 880 "data/maps/SootopolisCity/scripts.pory"
	.string "Leader: Juan\p"
# 881 "data/maps/SootopolisCity/scripts.pory"
	.string "“The Gym Leader with the beauty\n"
# 882 "data/maps/SootopolisCity/scripts.pory"
	.string "of pure water!”$"
# 883 "data/maps/SootopolisCity/scripts.pory"

# 884 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_CitySign:
# 885 "data/maps/SootopolisCity/scripts.pory"
	.string "Sootopolis City\p"
# 886 "data/maps/SootopolisCity/scripts.pory"
	.string "“The mystical city where history\n"
# 887 "data/maps/SootopolisCity/scripts.pory"
	.string "slumbers.”$"
# 888 "data/maps/SootopolisCity/scripts.pory"

# 889 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_DoorIsClosed:
# 890 "data/maps/SootopolisCity/scripts.pory"
	.string "The door is closed.$"
# 891 "data/maps/SootopolisCity/scripts.pory"

# 892 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_PhysicallyFitLivingHere:
# 893 "data/maps/SootopolisCity/scripts.pory"
	.string "Diving in the sea. Climbing up and\n"
# 894 "data/maps/SootopolisCity/scripts.pory"
	.string "down stairs all the time…\p"
# 895 "data/maps/SootopolisCity/scripts.pory"
	.string "If you live in this town, you end up\n"
# 896 "data/maps/SootopolisCity/scripts.pory"
	.string "getting physically fit.$"
# 897 "data/maps/SootopolisCity/scripts.pory"

# 898 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_GiantPokemonSuddenlyAppeared:
# 899 "data/maps/SootopolisCity/scripts.pory"
	.string "These giant Pokémon suddenly appeared\n"
# 900 "data/maps/SootopolisCity/scripts.pory"
	.string "in the middle of the city!\p"
# 901 "data/maps/SootopolisCity/scripts.pory"
	.string "And, I've never seen them before!\p"
# 902 "data/maps/SootopolisCity/scripts.pory"
	.string "Why are they smashing into each\n"
# 903 "data/maps/SootopolisCity/scripts.pory"
	.string "other like that?\p"
# 904 "data/maps/SootopolisCity/scripts.pory"
	.string "Why can't they be friends, those\n"
# 905 "data/maps/SootopolisCity/scripts.pory"
	.string "Pokémon?$"
# 906 "data/maps/SootopolisCity/scripts.pory"

# 907 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_WhatIsThatGreenPokemon:
# 908 "data/maps/SootopolisCity/scripts.pory"
	.string "What? What? What?\n"
# 909 "data/maps/SootopolisCity/scripts.pory"
	.string "What is that green Pokémon?!$"
# 910 "data/maps/SootopolisCity/scripts.pory"

# 911 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_WhereDidLegendariesGo:
# 912 "data/maps/SootopolisCity/scripts.pory"
	.string "Groudon and Kyogre…\n"
# 913 "data/maps/SootopolisCity/scripts.pory"
	.string "Where did they go?\p"
# 914 "data/maps/SootopolisCity/scripts.pory"
	.string "Will they cause droughts or downpours\n"
# 915 "data/maps/SootopolisCity/scripts.pory"
	.string "somewhere else?$"
# 916 "data/maps/SootopolisCity/scripts.pory"

# 917 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_TwoPokemonArentAngry:
# 918 "data/maps/SootopolisCity/scripts.pory"
	.string "I just get this sense somehow that\n"
# 919 "data/maps/SootopolisCity/scripts.pory"
	.string "the two Pokémon aren't angry.\p"
# 920 "data/maps/SootopolisCity/scripts.pory"
	.string "I think… They probably can't control\n"
# 921 "data/maps/SootopolisCity/scripts.pory"
	.string "their own power…$"
# 922 "data/maps/SootopolisCity/scripts.pory"

# 923 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_FlyingMonStoppedRampage:
# 924 "data/maps/SootopolisCity/scripts.pory"
	.string "That flying Pokémon came down from\n"
# 925 "data/maps/SootopolisCity/scripts.pory"
	.string "the sky and stopped the rampaging\l"
# 926 "data/maps/SootopolisCity/scripts.pory"
	.string "Pokémon…$"
# 927 "data/maps/SootopolisCity/scripts.pory"

# 928 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_WonderWhatWorldIsLike:
# 929 "data/maps/SootopolisCity/scripts.pory"
	.string "I… I've never been out of this city.\p"
# 930 "data/maps/SootopolisCity/scripts.pory"
	.string "I wonder what the world is like on\n"
# 931 "data/maps/SootopolisCity/scripts.pory"
	.string "the other side of this round sky?$"
# 932 "data/maps/SootopolisCity/scripts.pory"

# 933 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_ThisIsWicked:
# 934 "data/maps/SootopolisCity/scripts.pory"
	.string "Wow!\n"
# 935 "data/maps/SootopolisCity/scripts.pory"
	.string "This is wicked!$"
# 936 "data/maps/SootopolisCity/scripts.pory"

# 937 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_ThatWasWicked:
# 938 "data/maps/SootopolisCity/scripts.pory"
	.string "Wow!\n"
# 939 "data/maps/SootopolisCity/scripts.pory"
	.string "That was wicked!$"
# 940 "data/maps/SootopolisCity/scripts.pory"

# 941 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_GoRedAndBlueMon:
# 942 "data/maps/SootopolisCity/scripts.pory"
	.string "Go for it, red Pokémon!\n"
# 943 "data/maps/SootopolisCity/scripts.pory"
	.string "Don't back off, blue Pokémon!$"
# 944 "data/maps/SootopolisCity/scripts.pory"

# 945 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_DoYouKnowMonNames:
# 946 "data/maps/SootopolisCity/scripts.pory"
	.string "… … … … … …\p"
# 947 "data/maps/SootopolisCity/scripts.pory"
	.string "Hi, do you know the names of those\n"
# 948 "data/maps/SootopolisCity/scripts.pory"
	.string "Pokémon fighting over there?$"
# 949 "data/maps/SootopolisCity/scripts.pory"

# 950 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_GreenOneSettlesThings:
# 951 "data/maps/SootopolisCity/scripts.pory"
	.string "I was wondering which one would win,\n"
# 952 "data/maps/SootopolisCity/scripts.pory"
	.string "the red one or the blue one, but, oh no,\l"
# 953 "data/maps/SootopolisCity/scripts.pory"
	.string "it's the green one that settles things!\p"
# 954 "data/maps/SootopolisCity/scripts.pory"
	.string "Talk about a huge turn of events!$"
# 955 "data/maps/SootopolisCity/scripts.pory"

# 956 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_SeeingLegendWithOwnEyes:
# 957 "data/maps/SootopolisCity/scripts.pory"
	.string "There's an ancient legend that claims\n"
# 958 "data/maps/SootopolisCity/scripts.pory"
	.string "the land and sea were shaped by\l"
# 959 "data/maps/SootopolisCity/scripts.pory"
	.string "a colossal battle between Pokémon.\p"
# 960 "data/maps/SootopolisCity/scripts.pory"
	.string "Well, I'm seeing that happen with\n"
# 961 "data/maps/SootopolisCity/scripts.pory"
	.string "my very own eyes!\p"
# 962 "data/maps/SootopolisCity/scripts.pory"
	.string "Whoa! I never expected to be\n"
# 963 "data/maps/SootopolisCity/scripts.pory"
	.string "witness to something this huge!$"
# 964 "data/maps/SootopolisCity/scripts.pory"

# 965 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_SawLegendWithOwnEyes:
# 966 "data/maps/SootopolisCity/scripts.pory"
	.string "There's an ancient legend that claims\n"
# 967 "data/maps/SootopolisCity/scripts.pory"
	.string "the land and sea were shaped by\l"
# 968 "data/maps/SootopolisCity/scripts.pory"
	.string "a colossal battle between Pokémon.\p"
# 969 "data/maps/SootopolisCity/scripts.pory"
	.string "Well, I saw that happen with\n"
# 970 "data/maps/SootopolisCity/scripts.pory"
	.string "my very own eyes!\p"
# 971 "data/maps/SootopolisCity/scripts.pory"
	.string "Whoa! I never expected to be\n"
# 972 "data/maps/SootopolisCity/scripts.pory"
	.string "witness to something this huge!$"
# 973 "data/maps/SootopolisCity/scripts.pory"

# 974 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_BigPokemonFighting:
# 975 "data/maps/SootopolisCity/scripts.pory"
	.string "A big Pokémon is fighting with\n"
# 976 "data/maps/SootopolisCity/scripts.pory"
	.string "another big Pokémon!\p"
# 977 "data/maps/SootopolisCity/scripts.pory"
	.string "Please, someone make them stop!$"
# 978 "data/maps/SootopolisCity/scripts.pory"

# 979 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_PrettyMonCameFromSky:
# 980 "data/maps/SootopolisCity/scripts.pory"
	.string "A pretty Pokémon came down from\n"
# 981 "data/maps/SootopolisCity/scripts.pory"
	.string "the sky…$"
# 982 "data/maps/SootopolisCity/scripts.pory"

# 983 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_SootopolisWillBeWrecked:
# 984 "data/maps/SootopolisCity/scripts.pory"
	.string "Oh, no!\n"
# 985 "data/maps/SootopolisCity/scripts.pory"
	.string "Sootopolis City will get wrecked!$"
# 986 "data/maps/SootopolisCity/scripts.pory"

# 987 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_SootopolisDidntGetWrecked:
# 988 "data/maps/SootopolisCity/scripts.pory"
	.string "Sootopolis City didn't get wrecked!$"
# 989 "data/maps/SootopolisCity/scripts.pory"

# 990 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_NoOrdinaryTourist:
# 991 "data/maps/SootopolisCity/scripts.pory"
	.string "Hm!\n"
# 992 "data/maps/SootopolisCity/scripts.pory"
	.string "You've come all the way to Sootopolis?\l"
# 993 "data/maps/SootopolisCity/scripts.pory"
	.string "You're no ordinary tourist.\p"
# 994 "data/maps/SootopolisCity/scripts.pory"
	.string "But I suppose that doesn't make you\n"
# 995 "data/maps/SootopolisCity/scripts.pory"
	.string "an extraordinary tourist, either.$"
# 996 "data/maps/SootopolisCity/scripts.pory"

# 997 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_CityRegainedCalm:
# 998 "data/maps/SootopolisCity/scripts.pory"
	.string "The city has regained its calm…$"
# 999 "data/maps/SootopolisCity/scripts.pory"

# 1000 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_CaveOfOriginPleaseLeave:
# 1001 "data/maps/SootopolisCity/scripts.pory"
	.string "Who might you be?\p"
# 1002 "data/maps/SootopolisCity/scripts.pory"
	.string "This is the Cave of Origin.\p"
# 1003 "data/maps/SootopolisCity/scripts.pory"
	.string "The spirits of Pokémon, becalmed at\n"
# 1004 "data/maps/SootopolisCity/scripts.pory"
	.string "Mt. Pyre, are said to be revived here.\p"
# 1005 "data/maps/SootopolisCity/scripts.pory"
	.string "Please leave.$"
# 1006 "data/maps/SootopolisCity/scripts.pory"

# 1007 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_LeadSuperiorTrainerToCave:
# 1008 "data/maps/SootopolisCity/scripts.pory"
	.string "A person with a strong will and\n"
# 1009 "data/maps/SootopolisCity/scripts.pory"
	.string "superior talent…\p"
# 1010 "data/maps/SootopolisCity/scripts.pory"
	.string "A Trainer who has knowledge and\n"
# 1011 "data/maps/SootopolisCity/scripts.pory"
	.string "experience of many kinds of Pokémon…\p"
# 1012 "data/maps/SootopolisCity/scripts.pory"
	.string "If such a person were to appear, I was\n"
# 1013 "data/maps/SootopolisCity/scripts.pory"
	.string "instructed by Wallace to lead that\l"
# 1014 "data/maps/SootopolisCity/scripts.pory"
	.string "Trainer to this Cave.$"
# 1015 "data/maps/SootopolisCity/scripts.pory"

# 1016 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_AwakenedPokemonClash:
# 1017 "data/maps/SootopolisCity/scripts.pory"
	.string "Oh, my…\p"
# 1018 "data/maps/SootopolisCity/scripts.pory"
	.string "The clash between the two awakened\n"
# 1019 "data/maps/SootopolisCity/scripts.pory"
	.string "Pokémon was quelled by the awakening\l"
# 1020 "data/maps/SootopolisCity/scripts.pory"
	.string "of a third Pokémon…$"
# 1021 "data/maps/SootopolisCity/scripts.pory"

# 1022 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_CaveOfOriginSleepsToo:
# 1023 "data/maps/SootopolisCity/scripts.pory"
	.string "This is the Cave of Origin…\p"
# 1024 "data/maps/SootopolisCity/scripts.pory"
	.string "With the passing of the crisis,\n"
# 1025 "data/maps/SootopolisCity/scripts.pory"
	.string "the cave, too, shall sleep…$"
# 1026 "data/maps/SootopolisCity/scripts.pory"

# 1027 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_SootopolisSkyBeautiful:
# 1028 "data/maps/SootopolisCity/scripts.pory"
	.string "Sootopolis sprang up as a town in\n"
# 1029 "data/maps/SootopolisCity/scripts.pory"
	.string "the crater of a volcano.\p"
# 1030 "data/maps/SootopolisCity/scripts.pory"
	.string "If you look up at the sky, the lip of\n"
# 1031 "data/maps/SootopolisCity/scripts.pory"
	.string "the crater is also visible.\l"
# 1032 "data/maps/SootopolisCity/scripts.pory"
	.string "So, all you see is the sky in a circle.\p"
# 1033 "data/maps/SootopolisCity/scripts.pory"
	.string "But that's what makes the sky above\n"
# 1034 "data/maps/SootopolisCity/scripts.pory"
	.string "Sootopolis the most beautiful.$"
# 1035 "data/maps/SootopolisCity/scripts.pory"

# 1036 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_GiganticPokemonFight:
# 1037 "data/maps/SootopolisCity/scripts.pory"
	.string "When two Pokémon that gigantic\n"
# 1038 "data/maps/SootopolisCity/scripts.pory"
	.string "are fighting that savagely, there's\l"
# 1039 "data/maps/SootopolisCity/scripts.pory"
	.string "not much that we can do.$"
# 1040 "data/maps/SootopolisCity/scripts.pory"

# 1041 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_FearedWorstWhenPokemonFlewDown:
# 1042 "data/maps/SootopolisCity/scripts.pory"
	.string "When that third Pokémon flew down,\n"
# 1043 "data/maps/SootopolisCity/scripts.pory"
	.string "I feared the worst.$"
# 1044 "data/maps/SootopolisCity/scripts.pory"

# 1045 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_NightSkyFavoriteScenery:
# 1046 "data/maps/SootopolisCity/scripts.pory"
	.string "A circle of a night sky framed by\n"
# 1047 "data/maps/SootopolisCity/scripts.pory"
	.string "the crater of a volcano…\p"
# 1048 "data/maps/SootopolisCity/scripts.pory"
	.string "And in that ring, stars flicker and\n"
# 1049 "data/maps/SootopolisCity/scripts.pory"
	.string "blink as if they were alive…\l"
# 1050 "data/maps/SootopolisCity/scripts.pory"
	.string "It's my favorite scenery.$"
# 1051 "data/maps/SootopolisCity/scripts.pory"

# 1052 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_WeatherWentWild:
# 1053 "data/maps/SootopolisCity/scripts.pory"
	.string "The weather was clear this morning,\n"
# 1054 "data/maps/SootopolisCity/scripts.pory"
	.string "but…\p"
# 1055 "data/maps/SootopolisCity/scripts.pory"
	.string "All of a sudden, dark clouds brewed up,\n"
# 1056 "data/maps/SootopolisCity/scripts.pory"
	.string "rain started falling in sheets, and\l"
# 1057 "data/maps/SootopolisCity/scripts.pory"
	.string "there was thunder and lightning, too.\p"
# 1058 "data/maps/SootopolisCity/scripts.pory"
	.string "The weather just went completely\n"
# 1059 "data/maps/SootopolisCity/scripts.pory"
	.string "wild!\p"
# 1060 "data/maps/SootopolisCity/scripts.pory"
	.string "Is all of this because of those\n"
# 1061 "data/maps/SootopolisCity/scripts.pory"
	.string "Pokémon?$"
# 1062 "data/maps/SootopolisCity/scripts.pory"

# 1063 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_YouBroughtFlyingMon:
# 1064 "data/maps/SootopolisCity/scripts.pory"
	.string "Oh?\p"
# 1065 "data/maps/SootopolisCity/scripts.pory"
	.string "It was you who brought that flying\n"
# 1066 "data/maps/SootopolisCity/scripts.pory"
	.string "Pokémon here?\p"
# 1067 "data/maps/SootopolisCity/scripts.pory"
	.string "Well, aren't you amazing!$"
# 1068 "data/maps/SootopolisCity/scripts.pory"

# 1069 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_GroudonPleaseStop:
# 1070 "data/maps/SootopolisCity/scripts.pory"
	.string "Maxie: G… Groudon…\n"
# 1071 "data/maps/SootopolisCity/scripts.pory"
	.string "Please! Stop what you're doing!\p"
# 1072 "data/maps/SootopolisCity/scripts.pory"
	.string "I know the extent of your power now!\p"
# 1073 "data/maps/SootopolisCity/scripts.pory"
	.string "If you keep going, all Hoenn, not just\n"
# 1074 "data/maps/SootopolisCity/scripts.pory"
	.string "Sootopolis, will be utterly ruined!$"
# 1075 "data/maps/SootopolisCity/scripts.pory"

# 1076 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_AfterAllOurScheming:
# 1077 "data/maps/SootopolisCity/scripts.pory"
	.string "Maxie: So the super-ancient Pokémon\n"
# 1078 "data/maps/SootopolisCity/scripts.pory"
	.string "weren't only Groudon and Kyogre…\p"
# 1079 "data/maps/SootopolisCity/scripts.pory"
	.string "After all our fruitless scheming and\n"
# 1080 "data/maps/SootopolisCity/scripts.pory"
	.string "frantic efforts, that one Pokémon's\l"
# 1081 "data/maps/SootopolisCity/scripts.pory"
	.string "simple action puts everything right\l"
# 1082 "data/maps/SootopolisCity/scripts.pory"
	.string "again as if nothing had happened…\p"
# 1083 "data/maps/SootopolisCity/scripts.pory"
	.string "Fu…\n"
# 1084 "data/maps/SootopolisCity/scripts.pory"
	.string "Fuhahaha…$"
# 1085 "data/maps/SootopolisCity/scripts.pory"

# 1086 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_KyogreCalmDown:
# 1087 "data/maps/SootopolisCity/scripts.pory"
	.string "Archie: Kyogre! What's wrong?!\n"
# 1088 "data/maps/SootopolisCity/scripts.pory"
	.string "Look over here! It's the Red Orb!\l"
# 1089 "data/maps/SootopolisCity/scripts.pory"
	.string "Calm down! Kyogre!\p"
# 1090 "data/maps/SootopolisCity/scripts.pory"
	.string "… … … … … …\n"
# 1091 "data/maps/SootopolisCity/scripts.pory"
	.string "… … … … … …\p"
# 1092 "data/maps/SootopolisCity/scripts.pory"
	.string "It's no good!\n"
# 1093 "data/maps/SootopolisCity/scripts.pory"
	.string "It's not responding at all!$"
# 1094 "data/maps/SootopolisCity/scripts.pory"

# 1095 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_TryingMeaninglessToPokemon:
# 1096 "data/maps/SootopolisCity/scripts.pory"
	.string "Archie: Kyogre and Groudon both\n"
# 1097 "data/maps/SootopolisCity/scripts.pory"
	.string "flew off to who knows where.\p"
# 1098 "data/maps/SootopolisCity/scripts.pory"
	.string "The weather in Hoenn has returned\n"
# 1099 "data/maps/SootopolisCity/scripts.pory"
	.string "to its normal state…\p"
# 1100 "data/maps/SootopolisCity/scripts.pory"
	.string "Haha…\n"
# 1101 "data/maps/SootopolisCity/scripts.pory"
	.string "Hahaha…\p"
# 1102 "data/maps/SootopolisCity/scripts.pory"
	.string "Maybe what we were trying to do was\n"
# 1103 "data/maps/SootopolisCity/scripts.pory"
	.string "something small, even meaningless,\l"
# 1104 "data/maps/SootopolisCity/scripts.pory"
	.string "to Pokémon…$"
# 1105 "data/maps/SootopolisCity/scripts.pory"

# 1106 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_InvolvedWithCrisisComeWithMe:
# 1107 "data/maps/SootopolisCity/scripts.pory"
	.string "Steven: Those Pokémon fighting…\n"
# 1108 "data/maps/SootopolisCity/scripts.pory"
	.string "Groudon… And Kyogre…\p"
# 1109 "data/maps/SootopolisCity/scripts.pory"
	.string "The two super-ancient Pokémon\n"
# 1110 "data/maps/SootopolisCity/scripts.pory"
	.string "were awakened from a long sleep…\p"
# 1111 "data/maps/SootopolisCity/scripts.pory"
	.string "And now they are smashing each other\n"
# 1112 "data/maps/SootopolisCity/scripts.pory"
	.string "with their uncontrollable energy…\p"
# 1113 "data/maps/SootopolisCity/scripts.pory"
	.string "…{PLAYER}{KUN}.\p"
# 1114 "data/maps/SootopolisCity/scripts.pory"
	.string "You being here now I'll take to mean\n"
# 1115 "data/maps/SootopolisCity/scripts.pory"
	.string "that you're prepared to become\l"
# 1116 "data/maps/SootopolisCity/scripts.pory"
	.string "involved in this crisis.\p"
# 1117 "data/maps/SootopolisCity/scripts.pory"
	.string "Well, then, there's someone that\n"
# 1118 "data/maps/SootopolisCity/scripts.pory"
	.string "I'd like you to meet.\p"
# 1119 "data/maps/SootopolisCity/scripts.pory"
	.string "Come with me, please.$"
# 1120 "data/maps/SootopolisCity/scripts.pory"

# 1121 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_DoesThisMakeYourFearPokemon:
# 1122 "data/maps/SootopolisCity/scripts.pory"
	.string "Steven: Listen, {PLAYER}{KUN}.\p"
# 1123 "data/maps/SootopolisCity/scripts.pory"
	.string "Does seeing Groudon and Kyogre make\n"
# 1124 "data/maps/SootopolisCity/scripts.pory"
	.string "you think Pokémon are to be feared?\p"
# 1125 "data/maps/SootopolisCity/scripts.pory"
	.string "But that's not true.\n"
# 1126 "data/maps/SootopolisCity/scripts.pory"
	.string "Pokémon are really more…\p"
# 1127 "data/maps/SootopolisCity/scripts.pory"
	.string "…Why am I asking you this?\n"
# 1128 "data/maps/SootopolisCity/scripts.pory"
	.string "You already know.$"
# 1129 "data/maps/SootopolisCity/scripts.pory"

# 1130 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_HereWereAreHelpWallace:
# 1131 "data/maps/SootopolisCity/scripts.pory"
	.string "Steven: Okay, here we are!\p"
# 1132 "data/maps/SootopolisCity/scripts.pory"
	.string "Inside here you'll find someone named\n"
# 1133 "data/maps/SootopolisCity/scripts.pory"
	.string "Wallace.\p"
# 1134 "data/maps/SootopolisCity/scripts.pory"
	.string "I think you have what's needed to\n"
# 1135 "data/maps/SootopolisCity/scripts.pory"
	.string "help him…$"
# 1136 "data/maps/SootopolisCity/scripts.pory"

# 1137 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_KnowWhatsNeededToHelpHim:
# 1138 "data/maps/SootopolisCity/scripts.pory"
	.string "Steven: I think you have what's\n"
# 1139 "data/maps/SootopolisCity/scripts.pory"
	.string "needed to help him…$"
# 1140 "data/maps/SootopolisCity/scripts.pory"

# 1141 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_NeverBeenToSkyPillar:
# 1142 "data/maps/SootopolisCity/scripts.pory"
	.string "Steven: The Sky Pillar…\p"
# 1143 "data/maps/SootopolisCity/scripts.pory"
	.string "I've never been there.\n"
# 1144 "data/maps/SootopolisCity/scripts.pory"
	.string "I wonder where it could be?$"
# 1145 "data/maps/SootopolisCity/scripts.pory"

# 1146 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_SoThatsRayquaza:
# 1147 "data/maps/SootopolisCity/scripts.pory"
	.string "Steven: So that's Rayquaza…\p"
# 1148 "data/maps/SootopolisCity/scripts.pory"
	.string "It's incredible how the two rampaging\n"
# 1149 "data/maps/SootopolisCity/scripts.pory"
	.string "Pokémon would flee from it in fear…$"
# 1150 "data/maps/SootopolisCity/scripts.pory"

# 1151 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_MaxieArchieLeft:
# 1152 "data/maps/SootopolisCity/scripts.pory"
	.string "Steven: It looks like both Maxie and\n"
# 1153 "data/maps/SootopolisCity/scripts.pory"
	.string "Archie have gone away somewhere.\p"
# 1154 "data/maps/SootopolisCity/scripts.pory"
	.string "Perhaps they've gone to Mt. Pyre to\n"
# 1155 "data/maps/SootopolisCity/scripts.pory"
	.string "return those Orbs…$"
# 1156 "data/maps/SootopolisCity/scripts.pory"

# 1157 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_HaventYouScaledSkyPillar:
# 1158 "data/maps/SootopolisCity/scripts.pory"
	.string "Wallace: Oh?\n"
# 1159 "data/maps/SootopolisCity/scripts.pory"
	.string "{PLAYER}{KUN}?\p"
# 1160 "data/maps/SootopolisCity/scripts.pory"
	.string "Haven't you scaled the Sky Pillar\n"
# 1161 "data/maps/SootopolisCity/scripts.pory"
	.string "yet?\p"
# 1162 "data/maps/SootopolisCity/scripts.pory"
	.string "I'm sure that you can make it to\n"
# 1163 "data/maps/SootopolisCity/scripts.pory"
	.string "the top of the Sky Pillar…$"
# 1164 "data/maps/SootopolisCity/scripts.pory"

# 1165 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_AquaMagmaDidntMeanHarm:
# 1166 "data/maps/SootopolisCity/scripts.pory"
	.string "Wallace: {PLAYER}{KUN}…\p"
# 1167 "data/maps/SootopolisCity/scripts.pory"
	.string "The leaders of Team Magma and Aqua,\n"
# 1168 "data/maps/SootopolisCity/scripts.pory"
	.string "I don't think they meant harm.\p"
# 1169 "data/maps/SootopolisCity/scripts.pory"
	.string "It wouldn't hurt to hear what they\n"
# 1170 "data/maps/SootopolisCity/scripts.pory"
	.string "have to say for themselves.$"
# 1171 "data/maps/SootopolisCity/scripts.pory"

# 1172 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_ThankYouForHelpAcceptThis:
# 1173 "data/maps/SootopolisCity/scripts.pory"
	.string "Wallace: {PLAYER}{KUN}…\n"
# 1174 "data/maps/SootopolisCity/scripts.pory"
	.string "My eyes didn't deceive me.\p"
# 1175 "data/maps/SootopolisCity/scripts.pory"
	.string "Thanks to your help, Sootopolis…\n"
# 1176 "data/maps/SootopolisCity/scripts.pory"
	.string "No, all of Hoenn was saved.\p"
# 1177 "data/maps/SootopolisCity/scripts.pory"
	.string "On behalf of the people, I thank you.\p"
# 1178 "data/maps/SootopolisCity/scripts.pory"
	.string "This is a gift from me.\n"
# 1179 "data/maps/SootopolisCity/scripts.pory"
	.string "Please accept it.$"
# 1180 "data/maps/SootopolisCity/scripts.pory"

# 1181 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_ExplainWaterfallGoToGym:
# 1182 "data/maps/SootopolisCity/scripts.pory"
	.string "That Hidden Machine contains\n"
# 1183 "data/maps/SootopolisCity/scripts.pory"
	.string "Waterfall.\p"
# 1184 "data/maps/SootopolisCity/scripts.pory"
	.string "If you have the Rain Badge, a Pokémon\n"
# 1185 "data/maps/SootopolisCity/scripts.pory"
	.string "that has learned that HM move can\l"
# 1186 "data/maps/SootopolisCity/scripts.pory"
	.string "force its way up waterfalls.\p"
# 1187 "data/maps/SootopolisCity/scripts.pory"
	.string "And where does one get the Rain Badge?\n"
# 1188 "data/maps/SootopolisCity/scripts.pory"
	.string "You know, don't you?\p"
# 1189 "data/maps/SootopolisCity/scripts.pory"
	.string "That's right! You have to beat\n"
# 1190 "data/maps/SootopolisCity/scripts.pory"
	.string "the Sootopolis Gym Leader.\p"
# 1191 "data/maps/SootopolisCity/scripts.pory"
	.string "When you're all set to go, step through\n"
# 1192 "data/maps/SootopolisCity/scripts.pory"
	.string "that door.$"
# 1193 "data/maps/SootopolisCity/scripts.pory"

# 1194 "data/maps/SootopolisCity/scripts.pory"
SootopolisCity_Text_DazzledByMentor:
# 1195 "data/maps/SootopolisCity/scripts.pory"
	.string "Wallace: I'm sure that you will be\n"
# 1196 "data/maps/SootopolisCity/scripts.pory"
	.string "dazzled by my mentor's breathtakingly\l"
# 1197 "data/maps/SootopolisCity/scripts.pory"
	.string "elegant battle style.$"

SootopolisCity_MapScripts::
# 1218 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SootopolisCity_MapScripts_MAP_SCRIPT_ON_LOAD
# 1235 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION
# 1294 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, SootopolisCity_MapScripts_MAP_SCRIPT_ON_RESUME
# 1300 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SootopolisCity_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE
# 1304 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, SootopolisCity_MapScripts_MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE
	.byte 0

SootopolisCity_MapScripts_MAP_SCRIPT_ON_LOAD:
# 1219 "data/maps/SootopolisCity/scripts.pory"
	goto_if_unset FLAG_SOOTOPOLIS_ARCHIE_MAXIE_LEAVE, SootopolisCity_MapScripts_MAP_SCRIPT_ON_LOAD_2
SootopolisCity_MapScripts_MAP_SCRIPT_ON_LOAD_1:
# 1222 "data/maps/SootopolisCity/scripts.pory"
	goto_if_unset FLAG_KYOGRE_ESCAPED_SEAFLOOR_CAVERN, SootopolisCity_MapScripts_MAP_SCRIPT_ON_LOAD_4
# 1223 "data/maps/SootopolisCity/scripts.pory"
	goto_if_unset FLAG_SOOTOPOLIS_ARCHIE_MAXIE_LEAVE, SootopolisCity_MapScripts_MAP_SCRIPT_ON_LOAD_5
	return

SootopolisCity_MapScripts_MAP_SCRIPT_ON_LOAD_2:
# 1220 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 31, 32, METATILE_Sootopolis_GymDoor_Closed, TRUE
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_LOAD_1

SootopolisCity_MapScripts_MAP_SCRIPT_ON_LOAD_4:
	return

SootopolisCity_MapScripts_MAP_SCRIPT_ON_LOAD_5:
# 1224 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 9, 6, METATILE_Sootopolis_Door_Closed, TRUE
# 1225 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 9, 17, METATILE_Sootopolis_Door_Closed, TRUE
# 1226 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 9, 26, METATILE_Sootopolis_Door_Closed, TRUE
# 1227 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 44, 17, METATILE_Sootopolis_Door_Closed, TRUE
# 1228 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 8, 35, METATILE_Sootopolis_Door_Closed, TRUE
# 1229 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 53, 28, METATILE_Sootopolis_Door_Closed, TRUE
# 1230 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 45, 6, METATILE_Sootopolis_Door_Closed, TRUE
# 1231 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 48, 25, METATILE_Sootopolis_Door_Closed, TRUE
# 1232 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 51, 36, METATILE_Sootopolis_Door_Closed, TRUE
	return

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION:
# 1236 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_VISITED_SOOTOPOLIS_CITY
# 1237 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 1
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_2
# 1237 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SKY_PILLAR_STATE, 1
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_2
SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_1:
# 1240 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 0
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_7
# 1240 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 6
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_7
# 1241 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 1
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_8
# 1241 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SKY_PILLAR_STATE, 1
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_8
# 1244 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SKY_PILLAR_STATE, 1
	goto_if_le SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_9
SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_6:
# 1247 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 0
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_18
# 1247 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 6
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_18
# 1248 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 1
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_19
# 1248 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 2
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_19
# 1248 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 3
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_19
# 1248 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 4
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_19
# 1248 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SKY_PILLAR_STATE, 1
	goto_if_le SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_19
SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_17:
# 1251 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 1
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_33
# 1251 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 2
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_33
# 1251 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 3
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_33
# 1251 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 4
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_33
# 1251 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 5
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_33
SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_32:
# 1261 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 2
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_44
# 1261 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 3
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_44
SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_43:
# 1267 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 4
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_49
SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_48:
# 1272 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 5
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_54
SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_53:
# 1290 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 6
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_56
	return

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_2:
# 1238 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_HIDE_MAP_NAME_POPUP
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_1

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_7:
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_6

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_8:
# 1242 "data/maps/SootopolisCity/scripts.pory"
	setweather WEATHER_DOWNPOUR
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_6

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_9:
# 1245 "data/maps/SootopolisCity/scripts.pory"
	call Common_EventScript_SetAbnormalWeather
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_6

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_18:
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_17

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_19:
# 1249 "data/maps/SootopolisCity/scripts.pory"
	setmaplayoutindex LAYOUT_SOOTOPOLIS_CITY_LEGENDS_BATTLE
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_17

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_33:
# 1252 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 3, 13, 48
# 1253 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 5, 46, 32
# 1254 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 4, 48, 41
# 1255 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 8, 45, 43
# 1256 "data/maps/SootopolisCity/scripts.pory"
	setobjectmovementtype 3, MOVEMENT_TYPE_FACE_UP
# 1257 "data/maps/SootopolisCity/scripts.pory"
	setobjectmovementtype 5, MOVEMENT_TYPE_FACE_LEFT
# 1258 "data/maps/SootopolisCity/scripts.pory"
	setobjectmovementtype 4, MOVEMENT_TYPE_FACE_LEFT
# 1259 "data/maps/SootopolisCity/scripts.pory"
	setobjectmovementtype 8, MOVEMENT_TYPE_FACE_LEFT
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_32

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_44:
# 1262 "data/maps/SootopolisCity/scripts.pory"
	goto_if_set FLAG_STEVEN_GUIDES_TO_CAVE_OF_ORIGIN, SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_51
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_43

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_49:
# 1268 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 1, 30, 18
# 1269 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 18, 31, 18
# 1270 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 7, 32, 18
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_48

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_51:
# 1263 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 1, 30, 18
# 1264 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 7, 32, 18
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_43

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_54:
# 1273 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 1, 31, 18
# 1274 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 7, 29, 33
# 1275 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 16, 33, 35
# 1276 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 17, 34, 35
# 1277 "data/maps/SootopolisCity/scripts.pory"
	switch VAR_SOOTOPOLIS_WALLACE_STATE
# 1278 "data/maps/SootopolisCity/scripts.pory"
	case 0, SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_59
# 1281 "data/maps/SootopolisCity/scripts.pory"
	case 1, SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_60
# 1284 "data/maps/SootopolisCity/scripts.pory"
	case 2, SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_61
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_53

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_56:
# 1291 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 1, 31, 18
	return

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_59:
# 1279 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 18, 31, 33
# 1280 "data/maps/SootopolisCity/scripts.pory"
	setobjectmovementtype 18, MOVEMENT_TYPE_FACE_DOWN
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_53

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_60:
# 1282 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 18, 32, 33
# 1283 "data/maps/SootopolisCity/scripts.pory"
	setobjectmovementtype 18, MOVEMENT_TYPE_FACE_DOWN
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_53

SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_61:
# 1285 "data/maps/SootopolisCity/scripts.pory"
	setobjectxyperm 18, 30, 33
# 1286 "data/maps/SootopolisCity/scripts.pory"
	setobjectmovementtype 18, MOVEMENT_TYPE_FACE_DOWN
	goto SootopolisCity_MapScripts_MAP_SCRIPT_ON_TRANSITION_53

SootopolisCity_MapScripts_MAP_SCRIPT_ON_RESUME:
# 1295 "data/maps/SootopolisCity/scripts.pory"
	setdivewarp MAP_UNDERWATER_SOOTOPOLIS_CITY, 9, 6
# 1296 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SOOTOPOLIS_CITY_STATE, 5
	goto_if_eq SootopolisCity_MapScripts_MAP_SCRIPT_ON_RESUME_1
# 1296 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SKY_PILLAR_STATE, 1
	goto_if_le SootopolisCity_MapScripts_MAP_SCRIPT_ON_RESUME_1
	return

SootopolisCity_MapScripts_MAP_SCRIPT_ON_RESUME_1:
# 1297 "data/maps/SootopolisCity/scripts.pory"
	setmaplayoutindex LAYOUT_SOOTOPOLIS_CITY_LEGENDS_BATTLE
	return

SootopolisCity_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE:
# 1301 "data/maps/SootopolisCity/scripts.pory"
	map_script_2 VAR_SOOTOPOLIS_CITY_STATE, 1, SootopolisCity_EventScript_StartLegendariesScene
# 1302 "data/maps/SootopolisCity/scripts.pory"
	map_script_2 VAR_SKY_PILLAR_STATE, 1, SootopolisCity_EventScript_StartRayquazaScene
	.2byte 0

SootopolisCity_MapScripts_MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE:
# 1305 "data/maps/SootopolisCity/scripts.pory"
	map_script_2 VAR_SOOTOPOLIS_CITY_STATE, 5, SootopolisCity_EventScript_PlayerFaceLegendaries
	.2byte 0


SootopolisCity_EventScript_StartLegendariesScene::
# 1311 "data/maps/SootopolisCity/scripts.pory"
	lockall
# 1312 "data/maps/SootopolisCity/scripts.pory"
	special StorePlayerCoordsInVars
# 1313 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_0x8004, 43
	goto_if_ne SootopolisCity_EventScript_StartLegendariesScene_2
# 1313 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_0x8005, 32
	goto_if_ne SootopolisCity_EventScript_StartLegendariesScene_2
SootopolisCity_EventScript_StartLegendariesScene_1:
# 1316 "data/maps/SootopolisCity/scripts.pory"
	delay 60
# 1317 "data/maps/SootopolisCity/scripts.pory"
	special SpawnCameraObject
# 1318 "data/maps/SootopolisCity/scripts.pory"
	goto_if_set FLAG_TEMP_1, SootopolisCity_EventScript_StartLegendariesScene_7
# 1322 "data/maps/SootopolisCity/scripts.pory"
	applymovement OBJ_EVENT_ID_CAMERA, SootopolisCity_Movement_PanToActionFromPokeCenter
SootopolisCity_EventScript_StartLegendariesScene_6:
# 1324 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 1325 "data/maps/SootopolisCity/scripts.pory"
	special RemoveCameraObject
# 1326 "data/maps/SootopolisCity/scripts.pory"
	delay 60
# 1327 "data/maps/SootopolisCity/scripts.pory"
	fadescreenspeed FADE_TO_BLACK, 8
# 1328 "data/maps/SootopolisCity/scripts.pory"
	setweather WEATHER_ABNORMAL
# 1329 "data/maps/SootopolisCity/scripts.pory"
	doweather
# 1330 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8004, FALSE
# 1331 "data/maps/SootopolisCity/scripts.pory"
	special Script_DoRayquazaScene
# 1332 "data/maps/SootopolisCity/scripts.pory"
	waitstate
# 1333 "data/maps/SootopolisCity/scripts.pory"
	applymovement 10, Common_Movement_WalkInPlaceFasterLeft
# 1334 "data/maps/SootopolisCity/scripts.pory"
	applymovement 9, Common_Movement_WalkInPlaceFasterRight
# 1335 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 1336 "data/maps/SootopolisCity/scripts.pory"
	delay 60
# 1337 "data/maps/SootopolisCity/scripts.pory"
	waitse
# 1338 "data/maps/SootopolisCity/scripts.pory"
	playmoncry SPECIES_KYOGRE, CRY_MODE_ENCOUNTER
# 1339 "data/maps/SootopolisCity/scripts.pory"
	applymovement 10, SootopolisCity_Movement_KyogreAttack
# 1340 "data/maps/SootopolisCity/scripts.pory"
	applymovement 9, SootopolisCity_Movement_GroudonDefend
# 1341 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 1342 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8004, 1
# 1343 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8005, 1
# 1344 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8006, 8
# 1345 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8007, 5
# 1346 "data/maps/SootopolisCity/scripts.pory"
	special ShakeCamera
# 1347 "data/maps/SootopolisCity/scripts.pory"
	waitstate
# 1348 "data/maps/SootopolisCity/scripts.pory"
	applymovement 10, SootopolisCity_Movement_KyogreMoveBack
# 1349 "data/maps/SootopolisCity/scripts.pory"
	applymovement 9, SootopolisCity_Movement_GroudonMoveBack
# 1350 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 1351 "data/maps/SootopolisCity/scripts.pory"
	waitse
# 1352 "data/maps/SootopolisCity/scripts.pory"
	playmoncry SPECIES_GROUDON, CRY_MODE_ENCOUNTER
# 1353 "data/maps/SootopolisCity/scripts.pory"
	applymovement 10, SootopolisCity_Movement_KyogreDefend
# 1354 "data/maps/SootopolisCity/scripts.pory"
	applymovement 9, SootopolisCity_Movement_GroudonAttack
# 1355 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 1356 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8004, 1
# 1357 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8005, 1
# 1358 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8006, 8
# 1359 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8007, 5
# 1360 "data/maps/SootopolisCity/scripts.pory"
	special ShakeCamera
# 1361 "data/maps/SootopolisCity/scripts.pory"
	waitstate
# 1362 "data/maps/SootopolisCity/scripts.pory"
	applymovement 10, SootopolisCity_Movement_KyogreMoveBack
# 1363 "data/maps/SootopolisCity/scripts.pory"
	applymovement 9, SootopolisCity_Movement_GroudonMoveBack
# 1364 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 1365 "data/maps/SootopolisCity/scripts.pory"
	waitse
# 1366 "data/maps/SootopolisCity/scripts.pory"
	playmoncry SPECIES_KYOGRE, CRY_MODE_ENCOUNTER
# 1367 "data/maps/SootopolisCity/scripts.pory"
	applymovement 10, SootopolisCity_Movement_KyogreAttack
# 1368 "data/maps/SootopolisCity/scripts.pory"
	applymovement 9, SootopolisCity_Movement_GroudonDefend
# 1369 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 1370 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8004, 1
# 1371 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8005, 1
# 1372 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8006, 8
# 1373 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8007, 5
# 1374 "data/maps/SootopolisCity/scripts.pory"
	special ShakeCamera
# 1375 "data/maps/SootopolisCity/scripts.pory"
	waitstate
# 1376 "data/maps/SootopolisCity/scripts.pory"
	applymovement 10, SootopolisCity_Movement_KyogreMoveBack
# 1377 "data/maps/SootopolisCity/scripts.pory"
	applymovement 9, SootopolisCity_Movement_GroudonMoveBack
# 1378 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 1379 "data/maps/SootopolisCity/scripts.pory"
	special SpawnCameraObject
# 1380 "data/maps/SootopolisCity/scripts.pory"
	applymovement 10, SootopolisCity_Movement_KyogreIdle
# 1381 "data/maps/SootopolisCity/scripts.pory"
	applymovement 9, SootopolisCity_Movement_GroudonIdle
# 1382 "data/maps/SootopolisCity/scripts.pory"
	goto_if_set FLAG_TEMP_1, SootopolisCity_EventScript_StartLegendariesScene_11
# 1386 "data/maps/SootopolisCity/scripts.pory"
	applymovement OBJ_EVENT_ID_CAMERA, SootopolisCity_Movement_PanBackToPokeCenter
SootopolisCity_EventScript_StartLegendariesScene_10:
# 1388 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 1389 "data/maps/SootopolisCity/scripts.pory"
	special RemoveCameraObject
# 1390 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_SOOTOPOLIS_CITY_STATE, 2
# 1391 "data/maps/SootopolisCity/scripts.pory"
	clearflag FLAG_HIDE_MAP_NAME_POPUP
# 1392 "data/maps/SootopolisCity/scripts.pory"
	releaseall
	return

SootopolisCity_EventScript_StartLegendariesScene_2:
# 1314 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_TEMP_1
	goto SootopolisCity_EventScript_StartLegendariesScene_1

SootopolisCity_EventScript_StartLegendariesScene_7:
# 1319 "data/maps/SootopolisCity/scripts.pory"
	applymovement OBJ_EVENT_ID_CAMERA, SootopolisCity_Movement_PanToActionFromDive
	goto SootopolisCity_EventScript_StartLegendariesScene_6

SootopolisCity_EventScript_StartLegendariesScene_11:
# 1383 "data/maps/SootopolisCity/scripts.pory"
	applymovement OBJ_EVENT_ID_CAMERA, SootopolisCity_Movement_PanBackToDive
	goto SootopolisCity_EventScript_StartLegendariesScene_10


SootopolisCity_EventScript_StartRayquazaScene::
# 1396 "data/maps/SootopolisCity/scripts.pory"
	lockall
# 1397 "data/maps/SootopolisCity/scripts.pory"
	special StorePlayerCoordsInVars
# 1398 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_0x8004, 43
	goto_if_ne SootopolisCity_EventScript_StartRayquazaScene_2
# 1398 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_0x8005, 32
	goto_if_ne SootopolisCity_EventScript_StartRayquazaScene_2
SootopolisCity_EventScript_StartRayquazaScene_1:
# 1401 "data/maps/SootopolisCity/scripts.pory"
	delay 60
# 1402 "data/maps/SootopolisCity/scripts.pory"
	special SpawnCameraObject
# 1403 "data/maps/SootopolisCity/scripts.pory"
	goto_if_set FLAG_TEMP_1, SootopolisCity_EventScript_StartRayquazaScene_7
# 1407 "data/maps/SootopolisCity/scripts.pory"
	applymovement OBJ_EVENT_ID_CAMERA, SootopolisCity_Movement_PanToActionFromPokeCenter
SootopolisCity_EventScript_StartRayquazaScene_6:
# 1409 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 1410 "data/maps/SootopolisCity/scripts.pory"
	delay 20
# 1411 "data/maps/SootopolisCity/scripts.pory"
	fadescreenspeed FADE_TO_BLACK, 8
# 1412 "data/maps/SootopolisCity/scripts.pory"
	applymovement OBJ_EVENT_ID_CAMERA, Common_Movement_WalkUp2
# 1413 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 1414 "data/maps/SootopolisCity/scripts.pory"
	special RemoveCameraObject
# 1415 "data/maps/SootopolisCity/scripts.pory"
	addobject 11
# 1416 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8004, TRUE
# 1417 "data/maps/SootopolisCity/scripts.pory"
	special Script_DoRayquazaScene
# 1418 "data/maps/SootopolisCity/scripts.pory"
	waitstate
# 1419 "data/maps/SootopolisCity/scripts.pory"
	delay 80
# 1420 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_EventScript_StartRayquazaScene_Text_0
# 1421 "data/maps/SootopolisCity/scripts.pory"
	closemessage
# 1422 "data/maps/SootopolisCity/scripts.pory"
	special SavePlayerParty
# 1423 "data/maps/SootopolisCity/scripts.pory"
	fadescreen FADE_TO_BLACK
# 1424 "data/maps/SootopolisCity/scripts.pory"
	special ChooseHalfPartyForBattle
# 1425 "data/maps/SootopolisCity/scripts.pory"
	waitstate
# 1426 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_WILD_PARTNER
# 1427 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_NO_CATCHING
# 1428 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_NO_RUNNING
# 1429 "data/maps/SootopolisCity/scripts.pory"
	setwildbattle SPECIES_GROUDON, 55, ITEM_RED_ORB, 0, SPECIES_KYOGRE, 55, ITEM_BLUE_ORB, 0, MOVE_BULK_UP, MOVE_HAMMER_ARM, MOVE_LAVA_PLUME, MOVE_PRECIPICE_BLADES, MOVE_CALM_MIND, MOVE_BODY_SLAM, MOVE_ICE_BEAM, MOVE_ORIGIN_PULSE
# 1430 "data/maps/SootopolisCity/scripts.pory"
	multi_wild PARTNER_RAYQUAZA
# 1431 "data/maps/SootopolisCity/scripts.pory"
	clearflag FLAG_WILD_PARTNER
# 1432 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_RESULT, 1
	goto_if_ne SootopolisCity_EventScript_StartRayquazaScene_10
# 1438 "data/maps/SootopolisCity/scripts.pory"
	fadescreenspeed FADE_TO_BLACK, 2
# 1439 "data/maps/SootopolisCity/scripts.pory"
	clearflag FLAG_NO_CATCHING
# 1440 "data/maps/SootopolisCity/scripts.pory"
	clearflag FLAG_NO_RUNNING
# 1441 "data/maps/SootopolisCity/scripts.pory"
	removeobject 9
# 1442 "data/maps/SootopolisCity/scripts.pory"
	removeobject 10
# 1443 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 27, 43, METATILE_Sootopolis_RoughWater, FALSE
# 1444 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 28, 43, METATILE_Sootopolis_RoughWater, FALSE
# 1445 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 29, 43, METATILE_Sootopolis_RoughWater, FALSE
# 1446 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 30, 43, METATILE_Sootopolis_RoughWater, FALSE
# 1447 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 27, 44, METATILE_Sootopolis_RoughWater, FALSE
# 1448 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 28, 44, METATILE_Sootopolis_RoughWater, FALSE
# 1449 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 29, 44, METATILE_Sootopolis_RoughWater, FALSE
# 1450 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 30, 44, METATILE_Sootopolis_RoughWater, FALSE
# 1451 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 27, 45, METATILE_Sootopolis_RoughWater, FALSE
# 1452 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 28, 45, METATILE_Sootopolis_RoughWater, FALSE
# 1453 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 29, 45, METATILE_Sootopolis_RoughWater, FALSE
# 1454 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 30, 45, METATILE_Sootopolis_RoughWater, FALSE
# 1455 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 32, 43, METATILE_Sootopolis_RoughWater, FALSE
# 1456 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 33, 43, METATILE_Sootopolis_RoughWater, FALSE
# 1457 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 34, 43, METATILE_Sootopolis_RoughWater, FALSE
# 1458 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 35, 43, METATILE_Sootopolis_RoughWater, FALSE
# 1459 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 32, 44, METATILE_Sootopolis_RoughWater, FALSE
# 1460 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 33, 44, METATILE_Sootopolis_RoughWater, FALSE
# 1461 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 34, 44, METATILE_Sootopolis_RoughWater, FALSE
# 1462 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 35, 44, METATILE_Sootopolis_RoughWater, FALSE
# 1463 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 32, 45, METATILE_Sootopolis_RoughWater, FALSE
# 1464 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 33, 45, METATILE_Sootopolis_RoughWater, FALSE
# 1465 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 34, 45, METATILE_Sootopolis_RoughWater, FALSE
# 1466 "data/maps/SootopolisCity/scripts.pory"
	setmetatile 35, 45, METATILE_Sootopolis_RoughWater, FALSE
# 1467 "data/maps/SootopolisCity/scripts.pory"
	special DrawWholeMapView
# 1468 "data/maps/SootopolisCity/scripts.pory"
	fadescreenspeed FADE_FROM_BLACK, 2
# 1469 "data/maps/SootopolisCity/scripts.pory"
	playse SE_THUNDER
# 1470 "data/maps/SootopolisCity/scripts.pory"
	special SpawnCameraObject
# 1471 "data/maps/SootopolisCity/scripts.pory"
	applymovement OBJ_EVENT_ID_CAMERA, Common_Movement_WalkUp2
# 1472 "data/maps/SootopolisCity/scripts.pory"
	goto_if_set FLAG_TEMP_1, SootopolisCity_EventScript_StartRayquazaScene_14
SootopolisCity_EventScript_StartRayquazaScene_13:
# 1475 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 1476 "data/maps/SootopolisCity/scripts.pory"
	waitse
# 1477 "data/maps/SootopolisCity/scripts.pory"
	playmoncry SPECIES_RAYQUAZA, CRY_MODE_ENCOUNTER
# 1478 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8004, 1
# 1479 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8005, 1
# 1480 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8006, 8
# 1481 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8007, 3
# 1482 "data/maps/SootopolisCity/scripts.pory"
	special ShakeCamera
# 1483 "data/maps/SootopolisCity/scripts.pory"
	waitstate
# 1484 "data/maps/SootopolisCity/scripts.pory"
	waitse
# 1485 "data/maps/SootopolisCity/scripts.pory"
	playmoncry SPECIES_RAYQUAZA, CRY_MODE_ENCOUNTER
# 1486 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8004, 1
# 1487 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8005, 2
# 1488 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8006, 8
# 1489 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_0x8007, 5
# 1490 "data/maps/SootopolisCity/scripts.pory"
	special ShakeCamera
# 1491 "data/maps/SootopolisCity/scripts.pory"
	waitstate
# 1492 "data/maps/SootopolisCity/scripts.pory"
	waitmoncry
# 1493 "data/maps/SootopolisCity/scripts.pory"
	setweather WEATHER_NONE
# 1494 "data/maps/SootopolisCity/scripts.pory"
	doweather
# 1495 "data/maps/SootopolisCity/scripts.pory"
	applymovement 11, SootopolisCity_Movement_RayquazaFlyOff
# 1496 "data/maps/SootopolisCity/scripts.pory"
	waitmovement 0
# 1497 "data/maps/SootopolisCity/scripts.pory"
	removeobject 11
# 1498 "data/maps/SootopolisCity/scripts.pory"
	special WaitWeather
# 1499 "data/maps/SootopolisCity/scripts.pory"
	waitstate
# 1500 "data/maps/SootopolisCity/scripts.pory"
	clearflag FLAG_SYS_WEATHER_CTRL
# 1501 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_SKY_PILLAR_STATE, 2
# 1502 "data/maps/SootopolisCity/scripts.pory"
	clearflag FLAG_LEGENDARIES_IN_SOOTOPOLIS
# 1503 "data/maps/SootopolisCity/scripts.pory"
	goto_if_set FLAG_TEMP_1, SootopolisCity_EventScript_StartRayquazaScene_17
# 1507 "data/maps/SootopolisCity/scripts.pory"
	fadenewbgm MUS_SOOTOPOLIS
SootopolisCity_EventScript_StartRayquazaScene_16:
# 1509 "data/maps/SootopolisCity/scripts.pory"
	delay 120
# 1510 "data/maps/SootopolisCity/scripts.pory"
	clearflag FLAG_HIDE_MAP_NAME_POPUP
# 1511 "data/maps/SootopolisCity/scripts.pory"
	goto_if_set FLAG_TEMP_1, SootopolisCity_EventScript_StartRayquazaScene_21
# 1515 "data/maps/SootopolisCity/scripts.pory"
	warpwhitefade MAP_SOOTOPOLIS_CITY, 43, 32
SootopolisCity_EventScript_StartRayquazaScene_20:
# 1517 "data/maps/SootopolisCity/scripts.pory"
	waitstate
	return

SootopolisCity_EventScript_StartRayquazaScene_2:
# 1399 "data/maps/SootopolisCity/scripts.pory"
	setflag FLAG_TEMP_1
	goto SootopolisCity_EventScript_StartRayquazaScene_1

SootopolisCity_EventScript_StartRayquazaScene_7:
# 1404 "data/maps/SootopolisCity/scripts.pory"
	applymovement OBJ_EVENT_ID_CAMERA, SootopolisCity_Movement_PanToActionFromDive
	goto SootopolisCity_EventScript_StartRayquazaScene_6

SootopolisCity_EventScript_StartRayquazaScene_10:
# 1433 "data/maps/SootopolisCity/scripts.pory"
	fadescreen FADE_TO_BLACK
# 1434 "data/maps/SootopolisCity/scripts.pory"
	special SetCB2WhiteOut
# 1435 "data/maps/SootopolisCity/scripts.pory"
	waitstate
	return

SootopolisCity_EventScript_StartRayquazaScene_14:
# 1473 "data/maps/SootopolisCity/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkUp4
	goto SootopolisCity_EventScript_StartRayquazaScene_13

SootopolisCity_EventScript_StartRayquazaScene_17:
# 1504 "data/maps/SootopolisCity/scripts.pory"
	fadenewbgm MUS_SURF
	goto SootopolisCity_EventScript_StartRayquazaScene_16

SootopolisCity_EventScript_StartRayquazaScene_21:
# 1512 "data/maps/SootopolisCity/scripts.pory"
	warpwhitefade MAP_SOOTOPOLIS_CITY, 29, 53
	goto SootopolisCity_EventScript_StartRayquazaScene_20


SootopolisCity_EventScript_PlayerFaceLegendaries::
# 1522 "data/maps/SootopolisCity/scripts.pory"
	special StorePlayerCoordsInVars
# 1523 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_0x8004, 43
	goto_if_ne SootopolisCity_EventScript_PlayerFaceLegendaries_1
# 1523 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_0x8005, 32
	goto_if_ne SootopolisCity_EventScript_PlayerFaceLegendaries_1
	return

SootopolisCity_EventScript_PlayerFaceLegendaries_1:
# 1524 "data/maps/SootopolisCity/scripts.pory"
	turnobject OBJ_EVENT_ID_PLAYER, DIR_NORTH
# 1525 "data/maps/SootopolisCity/scripts.pory"
	compare VAR_SKY_PILLAR_STATE, 2
	goto_if_eq SootopolisCity_EventScript_PlayerFaceLegendaries_5
	return

SootopolisCity_EventScript_PlayerFaceLegendaries_5:
# 1526 "data/maps/SootopolisCity/scripts.pory"
	setvar VAR_SKY_PILLAR_STATE, 3
	return


SootopolisCity_EventScript_StartRayquazaScene_Text_0:
# 1420 "data/maps/SootopolisCity/scripts.pory"
	.string "But Rayquaza alone cannot quell them!$"
