Text_RegisteredInPokenav_OneInput::
# 1 "data/register_pokenav.pory"
	.string "Registered {STR_VAR_2}\n"
	.string "in the Pokénav.$"

Text_RegisteredInPokenav_TwoInputs::
# 6 "data/register_pokenav.pory"
	.string "Registered {STR_VAR_1} {STR_VAR_2}\n"
	.string "in the Pokénav.$"

Text_GymLeader::
# 11 "data/register_pokenav.pory"
	.string "Gym Leader$"

Text_GymLeaders::
# 15 "data/register_pokenav.pory"
	.string "Gym Leaders$"

Text_ThisScottPerson::
# 19 "data/register_pokenav.pory"
	.string "this Scott person$"
