Sakura_Town01::
# 5 "data/rival_scripts.pory"
	speakername CommonText_Sakura
# 6 "data/rival_scripts.pory"
	msgbox Town01_SakuraText, MSGBOX_NPC
	return


Jakson_Town01::
# 10 "data/rival_scripts.pory"
	speakername CommonText_Jakson
# 11 "data/rival_scripts.pory"
	msgbox Town01_JaksonText, MSGBOX_NPC
	return


Redd_Town01::
# 15 "data/rival_scripts.pory"
	lock
# 16 "data/rival_scripts.pory"
	speakername CommonText_Redd
# 17 "data/rival_scripts.pory"
	msgbox Town01_ReddText
# 18 "data/rival_scripts.pory"
	release
	return


Harper_Town01::
# 22 "data/rival_scripts.pory"
	speakername CommonText_Harper
# 23 "data/rival_scripts.pory"
	msgbox Town01_HarperText, MSGBOX_NPC
	return


Sakura_Town02::
# 28 "data/rival_scripts.pory"
	speakername CommonText_Sakura
# 29 "data/rival_scripts.pory"
	msgbox Town02_SakuraText, MSGBOX_NPC
	return


Harper_Town02::
# 33 "data/rival_scripts.pory"
	speakername CommonText_Harper
# 34 "data/rival_scripts.pory"
	msgbox Town02_HarperText, MSGBOX_NPC
	return


Redd_Town02::
# 38 "data/rival_scripts.pory"
	speakername CommonText_Redd
# 39 "data/rival_scripts.pory"
	msgbox Town02_ReddText, MSGBOX_NPC
	return


Baron_Town02::
# 43 "data/rival_scripts.pory"
	speakername CommonText_Baron
# 44 "data/rival_scripts.pory"
	msgbox Town02_BaronText, MSGBOX_NPC
	return


Jakson_Town02::
# 48 "data/rival_scripts.pory"
	speakername CommonText_Jakson
# 49 "data/rival_scripts.pory"
	msgbox Town02_JaksonText, MSGBOX_NPC
	return


Sakura_Town03::
# 54 "data/rival_scripts.pory"
	speakername CommonText_Sakura
# 55 "data/rival_scripts.pory"
	msgbox Town03_SakuraText, MSGBOX_NPC
	return


Harper_Town03::
# 59 "data/rival_scripts.pory"
	speakername CommonText_Harper
# 60 "data/rival_scripts.pory"
	msgbox Town03_HarperText, MSGBOX_NPC
	return


Redd_Town03::
# 64 "data/rival_scripts.pory"
	speakername CommonText_Redd
# 65 "data/rival_scripts.pory"
	msgbox Town03_ReddText, MSGBOX_NPC
	return


Jakson_Town03::
# 69 "data/rival_scripts.pory"
	speakername CommonText_Jakson
# 70 "data/rival_scripts.pory"
	msgbox Town03_JaksonText, MSGBOX_NPC
	return


Baron_Town03::
# 74 "data/rival_scripts.pory"
	lock
# 75 "data/rival_scripts.pory"
	speakername CommonText_Baron
# 76 "data/rival_scripts.pory"
	msgbox Town03_BaronText1
# 77 "data/rival_scripts.pory"
	faceplayer
# 78 "data/rival_scripts.pory"
	msgbox Town03_BaronText2
# 79 "data/rival_scripts.pory"
	release
	return

