#include "battle_transition_tasks/double_clock_wipe_pokeball.h"
#include "battle_transition_tasks/frontier_circles.h"
#include "battle_transition_tasks/tpp_host.h"
#include "battle_transition_tasks/speed_lines.h"
#include "battle_transition_tasks/triangle_tessellation.h"
#include "battle_transition_tasks/airbrush_tile.h"
