# 1 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"

# 2 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
RustboroCity_DevonCorp_1F_EventScript_RocksMetalDisplay::
# 3 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox RustboroCity_DevonCorp_1F_Text_RocksMetalDisplay, MSGBOX_SIGN
# 4 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	end
# 5 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"

# 6 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
RustboroCity_DevonCorp_1F_EventScript_ProductsDisplay::
# 7 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox RustboroCity_DevonCorp_1F_Text_ProductDisplay, MSGBOX_SIGN
# 8 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	end
# 9 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"

# 10 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
RustboroCity_DevonCorp_1F_Text_WelcomeToDevonCorp:
# 11 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "Hello and welcome to the Devon\n"
# 12 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "Corporation.\p"
# 13 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "We're proud producers of items and\n"
# 14 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "medicine that enhance your life.$"
# 15 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"

# 16 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
RustboroCity_DevonCorp_1F_Text_StaffGotRobbed:
# 17 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "One of our research staff stupidly\n"
# 18 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "got robbed of an important parcel.$"
# 19 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"

# 20 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
RustboroCity_DevonCorp_1F_Text_ThoseShoesAreOurProduct:
# 21 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "Hey, those Running Shoes!\n"
# 22 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "They're one of our products!\p"
# 23 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "It makes me happy when I see someone\n"
# 24 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "using something we made.$"
# 25 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"

# 26 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
RustboroCity_DevonCorp_1F_Text_RobberWasntVeryBright:
# 27 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "That stolen parcel…\p"
# 28 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "Well, sure it's important, but it's not\n"
# 29 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "anything that anyone can use.\p"
# 30 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "In my estimation, that robber must not\n"
# 31 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "have been very bright.$"
# 32 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"

# 33 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
RustboroCity_DevonCorp_1F_Text_SoundsLikeStolenGoodsRecovered:
# 34 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "It sounds like they've recovered\n"
# 35 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "the ripped-off Devon Goods.$"
# 36 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"

# 37 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
RustboroCity_DevonCorp_1F_Text_OnlyAuthorizedPeopleEnter:
# 38 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "I'm sorry, only authorized people\n"
# 39 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "are allowed to enter here.$"
# 40 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"

# 41 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
RustboroCity_DevonCorp_1F_Text_HowCouldWeGetRobbed:
# 42 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "It's beyond stupid.\n"
# 43 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "How could we get robbed?$"
# 44 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"

# 45 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
RustboroCity_DevonCorp_1F_Text_YoureAlwaysWelcomeHere:
# 46 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "Hi, there!\n"
# 47 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "You're always welcome here!$"
# 48 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"

# 49 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
RustboroCity_DevonCorp_1F_Text_RocksMetalDisplay:
# 50 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "Samples of rocks and metal are\n"
# 51 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "displayed in the glass case.\p"
# 52 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "There's a panel with some writing\n"
# 53 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "on it…\p"
# 54 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "“Devon Corporation got its start as\n"
# 55 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "a producer of stones from quarries.\p"
# 56 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "“The company also produced iron from\n"
# 57 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "filings in the sand.\p"
# 58 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "“From that humble start as a producer\n"
# 59 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "of raw materials, Devon developed.\p"
# 60 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "“Devon is now a manufacturer of a wide\n"
# 61 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "range of industrial products.”$"
# 62 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"

# 63 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
RustboroCity_DevonCorp_1F_Text_ProductDisplay:
# 64 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "Prototypes and test products fill\n"
# 65 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "the glass display case.\p"
# 66 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "There's a panel with a description…\p"
# 67 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "“In addition to industrial products,\n"
# 68 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "Devon now markets sundries and\l"
# 69 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "pharmaceuticals for better lifestyles.\p"
# 70 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "“Recently, Devon has begun marketing\n"
# 71 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "tools for Pokémon Trainers, including\l"
# 72 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "Poké Balls and Pokénav systems.”$"

RustboroCity_DevonCorp_1F_MapScripts::
# 80 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION
# 107 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_LOAD
# 127 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE
	.byte 0

RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION:
# 81 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	goto_if_unset FLAG_RETURNED_DEVON_GOODS, RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_2
# 86 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	compare VAR_LOOKER_ROCKET, 3
	goto_if_ge RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_5
RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_4:
# 94 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setflag FLAG_TEMP_1
RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_1:
# 96 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	compare VAR_LOOKER_ROCKET, 3
	goto_if_eq RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_10
RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_9:
# 105 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	clearflag FLAG_DONT_TRANSITION_MUSIC
	return

RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_2:
# 82 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setobjectxyperm 2, 21, 2
# 83 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setobjectmovementtype 2, MOVEMENT_TYPE_FACE_DOWN
# 84 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setflag FLAG_TEMP_1
	goto RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_1

RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_3:
# 87 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setobjectxyperm 2, 6, 5
# 88 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setobjectmovementtype 2, MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT
# 89 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setobjectxyperm 1, 0, 7
# 90 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setobjectmovementtype 1, MOVEMENT_TYPE_FACE_RIGHT
# 91 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setobjectxyperm 3, 1, 5
	goto RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_1

RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_5:
# 86 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	compare VAR_LOOKER_ROCKET, 5
	goto_if_le RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_3
	goto RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_4

RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_10:
# 97 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	getplayerxy VAR_TEMP_0, VAR_TEMP_1
# 98 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	compare VAR_TEMP_0, 13
	goto_if_eq RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_12
# 102 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setobjectxyperm 3, 20, 6
	goto RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_9

RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_12:
# 99 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setobjectxyperm 3, 21, 6
	goto RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_TRANSITION_9

RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_LOAD:
# 108 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	compare VAR_LOOKER_ROCKET, 3
	goto_if_ge RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_LOAD_2
	return

RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_LOAD_1:
# 109 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	playbgm MUS_HG_ROCKET_TAKEOVER, FALSE
# 110 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 3, 3, 0x381, FALSE
# 111 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 3, 4, 0x381, FALSE
# 112 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 4, 3, 0x380, FALSE
# 113 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 4, 4, 0x380, FALSE
# 114 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 4, 5, 0x380, FALSE
# 115 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 5, 3, 0x380, FALSE
# 116 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 5, 4, 0x380, FALSE
# 117 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 5, 5, 0x380, FALSE
# 118 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 20, 3, 0x386, FALSE
# 119 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 20, 4, 0x38E, TRUE
# 120 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 21, 3, 0x387, FALSE
# 121 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 21, 4, 0x38F, TRUE
# 122 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 21, 5, 0x383, FALSE
# 123 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 22, 4, 0x384, FALSE
# 124 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setmetatile 22, 5, 0x385, FALSE
	return

RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_LOAD_2:
# 108 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	compare VAR_LOOKER_ROCKET, 5
	goto_if_le RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_LOAD_1
	return

RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE:
# 128 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	map_script_2 VAR_TEMP_2, 0, RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE_0
# 134 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	map_script_2 VAR_LOOKER_ROCKET, 3, Devoncorp_RocketEntrance
	.2byte 0

RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE_0:
# 129 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	compare VAR_LOOKER_ROCKET, 3
	goto_if_ge RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE_0_3
RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE_0_1:
# 132 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setvar VAR_TEMP_2, 1
	return

RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE_0_2:
# 130 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	playbgm MUS_HG_ROCKET_TAKEOVER, FALSE
	goto RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE_0_1

RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE_0_3:
# 129 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	compare VAR_LOOKER_ROCKET, 5
	goto_if_le RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE_0_2
	goto RustboroCity_DevonCorp_1F_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE_0_1


Devoncorp_RocketEntrance::
# 139 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox Devoncorp_RocketEntrance_Text_0
# 140 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	applymovement 3, GreeterRun
# 141 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	waitmovement 0
# 142 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	closemessage
# 143 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	applymovement 3, Common_Movement_WalkInPlaceFasterDown
# 144 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	waitmovement 0
# 145 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	playse SE_PIN
# 146 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	applymovement 3, Common_Movement_ExclamationMark
# 147 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	waitmovement 0
# 148 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	delay 60
# 149 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	applymovement 3, Common_Movement_WalkDown
# 150 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	waitmovement 0
# 151 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox Devoncorp_RocketEntrance_Text_1, MSGBOX_AUTOCLOSE
# 152 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	applymovement 3, GreeterRun
# 153 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	waitmovement 0
# 154 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setobjectxy 3, 1, 5
# 155 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	applymovement 3, Common_Movement_WalkInPlaceFasterDown
# 156 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	setvar VAR_LOOKER_ROCKET, 4
	return


# 159 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
GreeterRun:
# 160 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	walk_fast_left
# 160 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	walk_fast_left
# 160 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	walk_fast_left
# 160 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	walk_fast_left
# 160 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	walk_fast_left
# 160 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	walk_fast_left
# 160 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	walk_fast_left
# 160 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	walk_fast_left
	step_end

RustboroCity_DevonCorp_1F_EventScript_StairGuard::
# 164 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	lock
# 165 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	faceplayer
# 166 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	compare VAR_LOOKER_ROCKET, 3
	goto_if_ge RustboroCity_DevonCorp_1F_EventScript_StairGuard_10
RustboroCity_DevonCorp_1F_EventScript_StairGuard_9:
# 169 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	goto_if_set FLAG_RETURNED_DEVON_GOODS, RustboroCity_DevonCorp_1F_EventScript_StairGuard_3
# 172 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	goto_if_set FLAG_RECOVERED_DEVON_GOODS, RustboroCity_DevonCorp_1F_EventScript_StairGuard_4
# 172 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	goto_if_set FLAG_DEVON_GOODS_STOLEN, RustboroCity_DevonCorp_1F_EventScript_StairGuard_4
# 176 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox RustboroCity_DevonCorp_1F_Text_OnlyAuthorizedPeopleEnter, MSGBOX_DEFAULT
RustboroCity_DevonCorp_1F_EventScript_StairGuard_1:
# 178 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	release
	return

RustboroCity_DevonCorp_1F_EventScript_StairGuard_2:
# 167 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox RustboroCity_DevonCorp_1F_EventScript_StairGuard_Text_0
	goto RustboroCity_DevonCorp_1F_EventScript_StairGuard_1

RustboroCity_DevonCorp_1F_EventScript_StairGuard_3:
# 170 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox RustboroCity_DevonCorp_1F_Text_YoureAlwaysWelcomeHere, MSGBOX_DEFAULT
	goto RustboroCity_DevonCorp_1F_EventScript_StairGuard_1

RustboroCity_DevonCorp_1F_EventScript_StairGuard_4:
# 173 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox RustboroCity_DevonCorp_1F_Text_HowCouldWeGetRobbed, MSGBOX_DEFAULT
	goto RustboroCity_DevonCorp_1F_EventScript_StairGuard_1

RustboroCity_DevonCorp_1F_EventScript_StairGuard_10:
# 166 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	compare VAR_LOOKER_ROCKET, 5
	goto_if_le RustboroCity_DevonCorp_1F_EventScript_StairGuard_2
	goto RustboroCity_DevonCorp_1F_EventScript_StairGuard_9


RustboroCity_DevonCorp_1F_EventScript_Employee::
# 182 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	lock
# 183 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	faceplayer
# 184 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	compare VAR_LOOKER_ROCKET, 3
	goto_if_ge RustboroCity_DevonCorp_1F_EventScript_Employee_8
RustboroCity_DevonCorp_1F_EventScript_Employee_7:
# 187 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	goto_if_set FLAG_RETURNED_DEVON_GOODS, RustboroCity_DevonCorp_1F_EventScript_Employee_3
# 190 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	goto_if_set FLAG_DEVON_GOODS_STOLEN, RustboroCity_DevonCorp_1F_EventScript_Employee_4
# 194 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox RustboroCity_DevonCorp_1F_Text_ThoseShoesAreOurProduct, MSGBOX_DEFAULT
RustboroCity_DevonCorp_1F_EventScript_Employee_1:
# 196 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	release
	return

RustboroCity_DevonCorp_1F_EventScript_Employee_2:
# 185 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox RustboroCity_DevonCorp_1F_EventScript_Employee_Text_0
	goto RustboroCity_DevonCorp_1F_EventScript_Employee_1

RustboroCity_DevonCorp_1F_EventScript_Employee_3:
# 188 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox RustboroCity_DevonCorp_1F_Text_SoundsLikeStolenGoodsRecovered, MSGBOX_DEFAULT
	goto RustboroCity_DevonCorp_1F_EventScript_Employee_1

RustboroCity_DevonCorp_1F_EventScript_Employee_4:
# 191 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox RustboroCity_DevonCorp_1F_Text_RobberWasntVeryBright, MSGBOX_DEFAULT
	goto RustboroCity_DevonCorp_1F_EventScript_Employee_1

RustboroCity_DevonCorp_1F_EventScript_Employee_8:
# 184 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	compare VAR_LOOKER_ROCKET, 5
	goto_if_le RustboroCity_DevonCorp_1F_EventScript_Employee_2
	goto RustboroCity_DevonCorp_1F_EventScript_Employee_7


RustboroCity_DevonCorp_1F_EventScript_Greeter::
# 200 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	lock
# 201 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	faceplayer
# 202 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	compare VAR_LOOKER_ROCKET, 3
	goto_if_ge RustboroCity_DevonCorp_1F_EventScript_Greeter_10
RustboroCity_DevonCorp_1F_EventScript_Greeter_9:
# 205 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	goto_if_set FLAG_RETURNED_DEVON_GOODS, RustboroCity_DevonCorp_1F_EventScript_Greeter_3
# 208 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	goto_if_set FLAG_RECOVERED_DEVON_GOODS, RustboroCity_DevonCorp_1F_EventScript_Greeter_4
# 208 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	goto_if_set FLAG_DEVON_GOODS_STOLEN, RustboroCity_DevonCorp_1F_EventScript_Greeter_4
# 212 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox RustboroCity_DevonCorp_1F_Text_WelcomeToDevonCorp, MSGBOX_DEFAULT
RustboroCity_DevonCorp_1F_EventScript_Greeter_1:
# 214 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	release
	return

RustboroCity_DevonCorp_1F_EventScript_Greeter_2:
# 203 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox RustboroCity_DevonCorp_1F_EventScript_Greeter_Text_0
	goto RustboroCity_DevonCorp_1F_EventScript_Greeter_1

RustboroCity_DevonCorp_1F_EventScript_Greeter_3:
# 206 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox RustboroCity_DevonCorp_1F_Text_WelcomeToDevonCorp, MSGBOX_DEFAULT
	goto RustboroCity_DevonCorp_1F_EventScript_Greeter_1

RustboroCity_DevonCorp_1F_EventScript_Greeter_4:
# 209 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	msgbox RustboroCity_DevonCorp_1F_Text_StaffGotRobbed, MSGBOX_DEFAULT
	goto RustboroCity_DevonCorp_1F_EventScript_Greeter_1

RustboroCity_DevonCorp_1F_EventScript_Greeter_10:
# 202 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	compare VAR_LOOKER_ROCKET, 5
	goto_if_le RustboroCity_DevonCorp_1F_EventScript_Greeter_2
	goto RustboroCity_DevonCorp_1F_EventScript_Greeter_9


Devoncorp_RocketEntrance_Text_0:
# 139 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "Iyaaaaa!!$"

Devoncorp_RocketEntrance_Text_1:
# 151 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "Oh! Please, you've got to help!\p"
	.string "A group of jackbooted thugs stormed in\n"
	.string "and went upstairs!\p"
	.string "I've got friends up there in other\n"
	.string "departments!\l"
	.string "Oh no…$"

RustboroCity_DevonCorp_1F_EventScript_StairGuard_Text_0:
# 167 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "I saw a few of them go into the\nbasement here.\pIt's probably a safer bet than charging\nupstairs.\pI can watch over the others if you want\nto try it, but be careful.$"

RustboroCity_DevonCorp_1F_EventScript_Employee_Text_0:
# 185 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "Trust me, if I could be a hero here,\nI would.\pI don't have it in me to take on all\nthose goons that ran in!$"

RustboroCity_DevonCorp_1F_EventScript_Greeter_Text_0:
# 203 "data/maps/RustboroCity_DevonCorp_1F/scripts.pory"
	.string "No, no, no. This can't be happening.$"
