MauveIslandSoutheast_MapScripts::
	.byte 0


MauveIslandSoutheast_EventScript_Lars::
# 4 "data/maps/MauveIslandSoutheast/scripts.pory"
	trainerbattle_single TRAINER_LARS, MauveIslandSoutheast_EventScript_Lars_Text_0, MauveIslandSoutheast_EventScript_Lars_Text_1
# 5 "data/maps/MauveIslandSoutheast/scripts.pory"
	msgbox MauveIslandSoutheast_EventScript_Lars_Text_2, MSGBOX_AUTOCLOSE
	return


MauveIslandSoutheast_EventScript_Keela::
# 9 "data/maps/MauveIslandSoutheast/scripts.pory"
	trainerbattle_single TRAINER_KEELA, MauveIslandSoutheast_EventScript_Keela_Text_0, MauveIslandSoutheast_EventScript_Keela_Text_1
# 10 "data/maps/MauveIslandSoutheast/scripts.pory"
	msgbox MauveIslandSoutheast_EventScript_Keela_Text_2, MSGBOX_AUTOCLOSE
	return


MauveIslandSoutheast_EventScript_Gordon::
# 14 "data/maps/MauveIslandSoutheast/scripts.pory"
	trainerbattle_single TRAINER_GORDON, MauveIslandSoutheast_EventScript_Gordon_Text_0, MauveIslandSoutheast_EventScript_Gordon_Text_1
# 15 "data/maps/MauveIslandSoutheast/scripts.pory"
	msgbox MauveIslandSoutheast_EventScript_Gordon_Text_2, MSGBOX_AUTOCLOSE
	return


MauveIslandSoutheast_EventScript_Vernon::
# 19 "data/maps/MauveIslandSoutheast/scripts.pory"
	trainerbattle_single TRAINER_VERNON, MauveIslandSoutheast_EventScript_Vernon_Text_0, MauveIslandSoutheast_EventScript_Vernon_Text_1
# 20 "data/maps/MauveIslandSoutheast/scripts.pory"
	msgbox MauveIslandSoutheast_EventScript_Vernon_Text_2, MSGBOX_AUTOCLOSE
	return


MauveIslandSoutheast_EventScript_Woman::
# 24 "data/maps/MauveIslandSoutheast/scripts.pory"
	msgbox MauveIslandSoutheast_EventScript_Woman_Text_0, MSGBOX_NPC
	return


MauveIslandSoutheast_EventScript_Lars_Text_0:
# 4 "data/maps/MauveIslandSoutheast/scripts.pory"
	.string "I can't find a good start for my climb,\nso distract me with a battle!$"

MauveIslandSoutheast_EventScript_Lars_Text_1:
# 4 "data/maps/MauveIslandSoutheast/scripts.pory"
	.string "Urgh!$"

MauveIslandSoutheast_EventScript_Lars_Text_2:
# 5 "data/maps/MauveIslandSoutheast/scripts.pory"
	.string "Not even I can make it up these cliff\nwalls.$"

MauveIslandSoutheast_EventScript_Keela_Text_0:
# 9 "data/maps/MauveIslandSoutheast/scripts.pory"
	.string "I'm borrowing daddy's Pokémon!\pMake them stronger for me!$"

MauveIslandSoutheast_EventScript_Keela_Text_1:
# 9 "data/maps/MauveIslandSoutheast/scripts.pory"
	.string "No!\nThat's not stronger!$"

MauveIslandSoutheast_EventScript_Keela_Text_2:
# 10 "data/maps/MauveIslandSoutheast/scripts.pory"
	.string "Daddy couldn't come, so he told us\nto bring his Pokémon with us!$"

MauveIslandSoutheast_EventScript_Gordon_Text_0:
# 14 "data/maps/MauveIslandSoutheast/scripts.pory"
	.string "Fight my Pokémon, mister!$"

MauveIslandSoutheast_EventScript_Gordon_Text_1:
# 14 "data/maps/MauveIslandSoutheast/scripts.pory"
	.string "Aww.$"

MauveIslandSoutheast_EventScript_Gordon_Text_2:
# 15 "data/maps/MauveIslandSoutheast/scripts.pory"
	.string "Mommy said she's getting a dee-vorse.\nWhat's that?\lI hope it's something fun!$"

MauveIslandSoutheast_EventScript_Vernon_Text_0:
# 19 "data/maps/MauveIslandSoutheast/scripts.pory"
	.string "Halt, villain!\pThis item is mine!$"

MauveIslandSoutheast_EventScript_Vernon_Text_1:
# 19 "data/maps/MauveIslandSoutheast/scripts.pory"
	.string "And to the victor, the spoils…$"

MauveIslandSoutheast_EventScript_Vernon_Text_2:
# 20 "data/maps/MauveIslandSoutheast/scripts.pory"
	.string "You overcame my strategy like nothing.$"

MauveIslandSoutheast_EventScript_Woman_Text_0:
# 24 "data/maps/MauveIslandSoutheast/scripts.pory"
	.string "A trip to the beach is a great way to\nrelieve some stress, isn't it?$"
